### ISSUE TITLE
Repoman doesn't have an icon on GNOME Shell's dash

### ISSUE THREAD

**Issue by dcominottim** [pop-os/pop#743] opened 2019-11-08 16:43 UTC
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

repoman:
  Installed: 1.0.2~1571155793~19.10~c4051b4
  Candidate: 1.0.2~1571155793~19.10~c4051b4
  Version table:
 *** 1.0.2~1571155793~19.10~c4051b4 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

Shows a blank/missing icon on the dash when open.

**Steps to reproduce (if you know):**

1. Open the Pop Store.
2. Click on the cog/"Edit Software Sources"
3. Open GNOME Shell's dash by clicking on Activities

**Expected behavior:**

There should be an icon for Repoman on the dash.

**Other Notes:**

**Comment by brs17** [comment] 2019-11-08 16:44
This is a duplicate of https://github.com/pop-os/repoman/issues/13

**Closed by brs17** 2019-11-08 16:44 UTC
