### ISSUE TITLE
Tile Windows: full screen is broken for some apps

### ISSUE THREAD

**Issue by aral** [pop-os/pop#957] opened 2020-05-02 01:30 UTC
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
n/a

**Issue/Bug Description:**

Full screen view is broken when tile windows is active.

**Steps to reproduce (if you know):**

1. Launch an app that supports full screen (e.g., Firefox)
2. Press F11 to enter full screen

**Expected behavior:**

The app should enter full screen.

**Actual behavior:**

![Screenshot from 2020-05-02 02-29-30](https://user-images.githubusercontent.com/41798/80851996-de040600-8c1c-11ea-84f4-e62afd04bd9a.png)

PS. When I tried this with Text Editor, it did fill the screen after a delay. VSCodium behaves like Firefox. GNOME Web behaves properly.

**Comment by mmstick** [comment] 2020-05-04 15:19
Duplicate of https://github.com/pop-os/shell/issues/248

**Closed by mmstick** 2020-05-04 15:19 UTC
