### ISSUE TITLE
Mouse going to the upper-left corner of windows

### ISSUE THREAD

**Issue by Metaph413** [pop-os/pop#1504] opened 2021-01-22 02:49 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
When I drag on windows to change their size, my mouse cursor goes to the upper-left corner of them for some reason. I have tested this with a Redragon M801, a Logitech M310, and a Dell 09RRC7 and they have shown the same problem.

Every window but the ones for Steam and Brave Browser I open up has been affected so far. And even then, this happens with Steam and Brave too.

**Steps to reproduce (if you know):**
Drag on the window border to change its size.

**Expected behavior:**
For the cursor to stay where it is when dragging.

**Comment by mmstick** [comment] 2021-01-22 02:52
Duplicate of https://github.com/pop-os/shell/issues/841

**Closed by mmstick** 2021-01-22 02:52 UTC
