### ISSUE TITLE
Clicking Edit Software Resources does nothing in PopShop

### ISSUE THREAD

**Issue by BigB86** [pop-os/pop#892] opened 2020-03-29 17:31 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
When I open the Pop Shop and click on the gear on the upper right that says 'Edit Software Resources' nothing happens.

**Steps to reproduce (if you know):**
Open Pop Shop > Click on gear on upper right of Pop Shop

**Expected behavior:**
Should open the settings for the 'Edit Software Resources.'

**Other Notes:**
I did use this a couple weeks ago, but there has been various updates since last using it.

**Comment by louisthomas69** [comment] 2020-03-29 23:05
i have been having the same problem i used timeshift  and it started working and noticed in conky which app was trying to start when clicking the gear, and its repoman. i tried launching it in terminal i got the following errors
Failed to load module "appmenu-gtk-module"
Traceback (most recent call last):
  File "/usr/bin/repoman", line 50, in <module>
    from repoman import main
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 32, in <module>
    from .window import Window
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 26, in <module>
    from .stack import Stack
  File "/usr/lib/python3/dist-packages/repoman/stack.py", line 27, in <module>
    from .list import List
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 28, in <module>
    from .dialog import AddDialog, EditDialog, ErrorDialog, DeleteDialog
  File "/usr/lib/python3/dist-packages/repoman/dialog.py", line 31, in <module>
    from . import flatpak_helper 
  File "/usr/lib/python3/dist-packages/repoman/flatpak_helper.py", line 27, in <module>
    gi.require_version('Flatpak', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Flatpak not available

**Comment by louisthomas69** [comment] 2020-03-29 23:11
i just been using synaptic package manager or straight apt until they fix it. the old fallbacks always help when the newer graphical things fail,lol

**Comment by leviport** [comment] 2020-03-30 14:33
This is a duplicate of https://github.com/pop-os/repoman/issues/60
We hope to have this one fixed very soon, sorry for the inconvenience.

**Closed by leviport** 2020-03-30 14:33 UTC
