### ISSUE TITLE
Latest OS update failing due to nvidia-driver-460

### ISSUE THREAD

**Issue by andre-fuchs** [pop-os/pop#1682] opened 2021-05-05 15:56 UTC
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 20.10 x86_64
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop!_Shop, Operating System Update

**Issue/Bug Description:**
The latest OS update fails with unmet dependencies:

```
The following packages have unmet dependencies:
  nvidia-driver-460: Depends: libnvidia-gl-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Depends: nvidia-kernel-source-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Depends: libnvidia-compute-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Depends: libnvidia-extra-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Depends: nvidia-compute-utils-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Depends: libnvidia-decode-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Depends: libnvidia-encode-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Depends: nvidia-utils-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Depends: xserver-xorg-video-nvidia-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Depends: libnvidia-cfg1-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Depends: libnvidia-ifr1-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Depends: libnvidia-fbc1-460 (= 460.67-1pop0~1616430777~20.10~71e1ad1) but 460.73.01-0ubuntu0.20.10.1 is to be installed
                     Recommends: libnvidia-compute-460:i386 (= 460.67-1pop0~1616430777~20.10~71e1ad1)
                     Recommends: libnvidia-decode-460:i386 (= 460.67-1pop0~1616430777~20.10~71e1ad1)
                     Recommends: libnvidia-encode-460:i386 (= 460.67-1pop0~1616430777~20.10~71e1ad1)
                     Recommends: libnvidia-ifr1-460:i386 (= 460.67-1pop0~1616430777~20.10~71e1ad1)
                     Recommends: libnvidia-fbc1-460:i386 (= 460.67-1pop0~1616430777~20.10~71e1ad1)
                     Recommends: libnvidia-gl-460:i386 (= 460.67-1pop0~1616430777~20.10~71e1ad1)
```

**Steps to reproduce (if you know):**
Desktop PC
CPU: Intel i7-8700
GPU: NVIDIA GeForce GTX 1080 Ti
no custom/additional drivers installed

**Expected behavior:**
The Pop!_OS updates usually ran without any hickups. First fail in the last couple of years using it. There were issues regarding the nvidia driver updates before, but never affecting the OS updates.

**Comment by leviport** [comment] 2021-05-05 16:03
Duplicate of https://github.com/pop-os/nvidia-graphics-drivers/issues/94

**Closed by leviport** 2021-05-05 16:03 UTC
