### ISSUE TITLE
Random freezing of pop OS (not fixed for 4 years!)

### ISSUE THREAD

**Issue by abbasnaqdi** [pop-os/pop#3327] opened 2024-07-11 17:06 UTC
Hello, I have been using Pop OS for years, but there was a major problem: the freezing of the operating system. So I migrated to Ubuntu and the problem was solved.

To make sure that it is not a hardware problem, I have already installed this operating system (in 2023) on different hardware (a powerful Ryzen 5 PC, an Asus Vivobook laptop, and a powerful i5 11th PC) in all They had the same problem with different configs.

Unfortunately, yesterday I installed this operating system on my new hardware (a powerful mini PC) and I realized that the freezing problem has not been solved! Today, my system has completely frozen 3 times and I had to restart it.

My system:
```
OS: Pop!_OS 22.04
Host: MINIPC PN64
Kernel: 6.9.3-7606
DE: GNOME 42.9
WM: Mutter
CPU: 13th Gen Intel i7-13700H (20) @ 4.800GHz
GPU: Intel Device a7a0
Memory: 10334MiB / 31820MiB
```

You may need to set up an error reporting system like Sentry.

**This problem has existed in this operating system for 4 years!
In 4 years, a generation of technology changes, and pop os still can't fix a bug!**

https://github.com/pop-os/pop/issues/2128
https://github.com/pop-os/pop/issues/1172
https://github.com/pop-os/pop/issues/3130
https://www.reddit.com/r/pop_os/comments/o6ak72/i_just_installed_popos_and_random_freezes_keep/
https://unix.stackexchange.com/questions/754512/random-freezes-on-pop-os-based-on-ubuntu-22-04
https://community.frame.work/t/responded-screen-freezing-jumping-pop-os-22-04/24984
https://www.reddit.com/r/pop_os/search/?q=freez&sort=new&restrict_sr=on

**Comment by leviport** [comment] 2024-07-11 17:32
>This problem has existed in this operating system for 4 years!
>In 4 years, a generation of technology changes, and pop os still can't fix a bug!

We have all mentioned this countless times, but apparently I need to say it again: freezing can be caused by numerous things. If you look through all of the reports you linked, you will see that a large number of them were hardware issues. The ones that weren't hardware varied massively in symptoms and causes. This isn't "just one bug" that we refuse to fix. 

Since there are already numerous issues open for vague reports of "freezing", I'm going to close this one as a duplicate. If you can find anything more specific and actionable that is unrelated to prior reports, this issue can be reopened.

**Closed by leviport** 2024-07-11 17:32 UTC
