### ISSUE TITLE
Custom shell theme reverted after reboot.

### ISSUE THREAD

**Issue by petepall** [pop-os/pop#939] opened 2020-05-01 11:22 UTC
**Distribution (run `cat /etc/os-release`):**

- NAME="Pop!_OS"
- VERSION="20.04 LTS"
- ID=pop
- ID_LIKE="ubuntu debian"
- PRETTY_NAME="Pop!_OS 20.04 LTS"
- VERSION_ID="20.04"
- HOME_URL="https://system76.com/pop"
- SUPPORT_URL="http://support.system76.com"
- BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
- PRIVACY_POLICY_URL="https://system76.com/privacy"
- VERSION_CODENAME=focal
- UBUNTU_CODENAME=focal
- LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
After reboot the installed shell theme is reverted back to standard.
Manual update of the shell theme is required each time.

**Steps to reproduce (if you know):**
Install a custom shell theme and apply this using the tweak tools.
Reboot the PC and see that the theme is no longer applied.

My current installed theme is:
![image](https://user-images.githubusercontent.com/42099752/80802094-9a72b300-8bae-11ea-9a7c-616321505c4b.png)

**Expected behavior:**
Theme should remain applied after reboot.

**Other Notes:**

**Comment by amazingAB** [comment] 2020-05-02 12:07
This happens when pop shell is enabled/installed. I installed pop shell on ubuntu, same problem occurred.

**Comment by mmstick** [comment] 2020-05-04 15:16
Duplicate of https://github.com/pop-os/shell/issues/231

**Closed by mmstick** 2020-05-04 15:16 UTC
