### ISSUE TITLE
Spotify Local File Support - Adding source = CTD

### ISSUE THREAD

**Issue by rholman-PRFT** [pop-os/pop#1333] opened 2020-10-26 21:00 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Spotify (.deb OR fltapak)

**Issue/Bug Description:**

Select to manage local files. Click to add source, crash.

**Steps to reproduce (if you know):**

Select to manage local files. Click to add source, crash.

**Expected behavior:**

UI brings up file chooser.

**Other Notes:**

**Comment by leviport** [comment] 2020-10-26 21:10
Duplicate of https://github.com/pop-os/pop/issues/1333

**Closed by leviport** 2020-10-26 21:10 UTC
