### ISSUE TITLE
Cursor disappearance when touchscreen is used and cannot be brought back, Asus Vivo AiO v272UA

### ISSUE THREAD

**Issue by supercat7** [pop-os/pop#3266] opened 2024-04-10 18:57 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
Cursor Disappears when touchscreen is used and can only be brought back by pressing the super key

**Steps to reproduce (if you know):**
Touching the touchscreen

**Expected behavior:**
Cursor must be visible after input change

**Other Notes:**
Hardware Info:
Asus Vivo all-in-one (AiO) v272UA Touchscreen computer
8GB ddr4 ram
Intel i7-8550U

**Comment by leviport** [comment] 2024-04-10 19:26
Duplicate of https://github.com/pop-os/pop/issues/2902

**Closed by leviport** 2024-04-10 19:26 UTC
