### ISSUE TITLE
Since upgrading to 21.04, adding a keyboard input layout segfaults

### ISSUE THREAD

**Issue by jprobichaud** [pop-os/pop#1809] opened 2021-07-12 14:05 UTC
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
gnome-control-center:
  Installed: 1:3.38.3-1pop1~1625268318~21.04~2880306
  Candidate: 1:3.38.3-1pop1~1625268318~21.04~2880306
  Version table:
     1:3.38.5-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
 *** 1:3.38.3-1pop1~1625268318~21.04~2880306 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status

gnome-control-center-data:
  Installed: 1:3.38.3-1pop1~1625268318~21.04~2880306
  Candidate: 1:3.38.3-1pop1~1625268318~21.04~2880306
  Version table:
     1:3.38.5-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main i386 Packages
 *** 1:3.38.3-1pop1~1625268318~21.04~2880306 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
I need to add at least two input keyboards layout on top of En-Us.  With the previous installation (20.10 iirc) installed from the factory, I had no issues at all.  I've recently performed the upgrade to 21.04 (from the terminal, not the GUI) and any time I try to add a new input layout, gnome control center crashes.

When I try it from the command line, I see a segfault.  

**Steps to reproduce (if you know):**
type `gnome-control-center` on the terminal, pick the keyboard category, click on the `+` sign to add a new layout.

**Expected behavior:**
getting the dialog to add new languages!

**Other Notes:**

I've collected system logs + strace + a code dump.

**Comment by jacobgkau** [comment] 2021-07-12 14:10
Duplicate of https://github.com/pop-os/gnome-control-center/issues/185.

**Closed by jacobgkau** 2021-07-12 14:10 UTC

**Comment by jprobichaud** [comment] 2021-07-12 14:16
wow, that was quick.  I missed that other ticket in my searches!  Thanks, the solution in that other ticket did indeed fix my issue.

**Comment by dxps** [comment] 2021-07-13 16:38
@jacobgkau Lucky for you! :blush: I can't say the same for now.
