### ISSUE TITLE
[ACER Aspire] The application launcher appears zoomed

### ISSUE THREAD

**Issue by flexo44** [pop-os/pop#1821] opened 2021-07-20 12:37 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
The problem happens in application launcher  

**Issue/Bug Description:**
The application launcher appears zoomed The application launcher appears zoomed, after a normal start and the bug disappears after a restart 

**Steps to reproduce (if you know):**
Just normal boot and start applications launcher  

**Expected behavior:**
Reboot device 

Device information : https://linux-hardware.org/?probe=752b78a545#Logs

**Comment by jacobgkau** [comment] 2021-07-20 14:06
Based on the description and the screen resolution indicated by the URL you provided, I'm closing this as a duplicate of https://github.com/pop-os/pop/issues/1786. If this is a different issue, please provide a screenshot to demonstrate.

**Closed by jacobgkau** 2021-07-20 14:06 UTC
