### ISSUE TITLE
Plethora of issues in 20.04

### ISSUE THREAD

**Issue by 7f043** [pop-os/pop#1136] opened 2020-07-09 04:05 UTC
"Printer added" will constantly pop-up as a notification, even after a printer is connected previously. There are various other nuisance notifications as well. Meaning a notification will pop up several times to say the same thing. (GS connect: "file storage not selected", etc) 
This was not an issue before, bu

Screen will black out at random intervals for about 2 seconds total. Completely black. No rhyme or reason. A display issue perhaps? No clue what is causing this at all.

Keyboard shortcuts seem to be broken, (WIN key + [1/2/3/4...] does not bring up favorite apps, it seems to be conflicting with caribou for some reason. Also: Caribou on screen keyboard will come up anytime a keyboard shortcut is activated, for me this is always. 
Installing the "Block caribou" extension through firefox causes this. The only way I can get it to reset is by doing a "refreshed install"

Pulse audio is having various new issues. Random "mute" intervals where the sound won't work."Pactl" commands no longer work to increase volume from terminal consistantly. Sometimes, I have to kill and start pulseaudio to do that. Where it has never been an issue before.
Do not know how to reproduce, seemingly random.

I run sudo apt update/upgrade. Everything should be up to date. Don't understand why this version of pop is giving my computer so much trouble. It's a Lenovo, which are generally very linux-friendly. I'm stumped. About to drop POP_Os over this. I have been dealing with this for months now. Need help fast

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Comment by leviport** [comment] 2020-07-09 15:56
Please open individual issues for individual issues. The printer notification pop up you mentioned is a duplicate of https://github.com/pop-os/pop/issues/8 .The keyboard shortcut for launching apps was intentionally removed: https://github.com/pop-os/session/pull/20 .

It's hard to say what the other two issues you're running into are caused by, but you may want to drop by chat.pop-os.org for assistance. That's a much better venue for troubleshooting and technical assistance than github issues. If the cause can be determined to be a bug in Pop!_OS, then opening issues is the right course of action.

**Closed by leviport** 2020-07-09 15:56 UTC

**Comment by azriel91** [comment] 2020-07-10 06:01
See https://github.com/pop-os/session/issues/21 for the <kbd>super</kbd> + <kbd>num</kbd> hotkey issue.
