### ISSUE TITLE
apt update or upgrade returns lots of 404s

### ISSUE THREAD

**Issue by sizief** [pop-os/pop#1451] opened 2020-12-19 16:51 UTC
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
**Issue/Bug Description:**
Running `apt update; apt upgrade` shows 404 errors. I have Pop OS 20.10 on X1 carbon. 

```

pop-os ➜ ~ sudo apt upgrade --fix-missing

Reading package lists... Done

Building dependency tree

Reading state information... Done

Calculating upgrade... Done

The following packages will be upgraded:

firmware-manager-notify firmware-manager-shared libfirmware-manager libpop-theme-switcher libs76-hidpi-widget

pop-default-settings pop-shell

7 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Need to get 2,832 kB of archives.

After this operation, 38.9 kB of additional disk space will be used.

Do you want to continue? [Y/n] Y

Err:1 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 firmware-manager-notify amd64 0.1.2~1607014663~20.10~0fdfd96

404 Not Found [IP: 91.189.95.85 80]

Ign:2 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 firmware-manager-shared all 0.1.2~1607014663~20.10~0fdfd96

Err:3 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 libfirmware-manager amd64 0.1.2~1607014663~20.10~0fdfd96

404 Not Found [IP: 91.189.95.85 80]

Err:4 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 libpop-theme-switcher amd64 0.1.1~1607014660~20.10~66b6888

404 Not Found [IP: 91.189.95.85 80]

Err:5 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 libs76-hidpi-widget amd64 0.1.1~1607640801~20.10~6398f4b

404 Not Found [IP: 91.189.95.85 80]

Ign:6 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 pop-default-settings all 4.0.6~1606921458~20.10~c920ed7

Ign:7 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 pop-shell all 1.1.0~1607723907~20.10~d72a2f3

Err:2 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 firmware-manager-shared all 0.1.2~1607014663~20.10~0fdfd96

404 Not Found [IP: 91.189.95.85 80]

Err:6 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 pop-default-settings all 4.0.6~1606921458~20.10~c920ed7

404 Not Found [IP: 91.189.95.85 80]

Err:7 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 pop-shell all 1.1.0~1607723907~20.10~d72a2f3

404 Not Found [IP: 91.189.95.85 80]

E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/f/firmware-manager/firmware-manager-notify_0.1.2~1607014663~20.10~0fdfd96_amd64.deb 404 Not Found [IP: 91.189.95.85 80]

E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/f/firmware-manager/firmware-manager-shared_0.1.2~1607014663~20.10~0fdfd96_all.deb 404 Not Found [IP: 91.189.95.85 80]

E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/f/firmware-manager/libfirmware-manager_0.1.2~1607014663~20.10~0fdfd96_amd64.deb 404 Not Found [IP: 91.189.95.85 80]

E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-theme-switcher/libpop-theme-switcher_0.1.1~1607014660~20.10~66b6888_amd64.deb 404 Not Found [IP: 91.189.95.85 80]

E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/s/system76-hidpi-widget/libs76-hidpi-widget_0.1.1~1607640801~20.10~6398f4b_amd64.deb 404 Not Found [IP: 91.189.95.85 80]

E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-default-settings/pop-default-settings_4.0.6~1606921458~20.10~c920ed7_all.deb 404 Not Found [IP: 91.189.95.85 80]

E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-shell/pop-shell_1.1.0~1607723907~20.10~d72a2f3_all.deb 404 Not Found [IP: 91.189.95.85 80]
```

**Steps to reproduce (if you know):**

run `apt upgrade`

**Expected behaviour:**
run without error.

**Other Notes:**
I check the URLs, they are not available. I am not sure how to update the package list to have the latest URLs.

**Comment by jacobgkau** [comment] 2020-12-21 19:27
> I check the URLs, they are not available. I am not sure how to update the package list to have the latest URLs.

The package lists are updated when you run `sudo apt update`. I don't see output from that command, so I assume you haven't run it yet.

I see that the packages you were trying to download are not on the server because they're older versions, and I've confirmed the current versions are available for download, so I'm going to close this issue. Please try running the upgrade again after running `sudo apt update`, and if you have errors from that command as well, you would need to post the output for others to know what's happening (as well as the output of `cat /etc/apt/sources.list`, `ls -al /etc/apt/sources.list.d/`, and `cat /etc/apt/sources.list.d/*` to see what sources you have configured.)

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Closed by jacobgkau** 2020-12-21 19:27 UTC
Labels: support request
