### ISSUE TITLE
S3 sleep is still broke (even on my new laptop) 

### ISSUE THREAD

**Issue by realKarthikNair** [pop-os/pop#3151] opened 2023-10-06 11:13 UTC
I hate making duplicate issues as much as devs do but here we go 

Issue summary: device cant wake from S3 sleep at all.. modern stanby works and cant repro issue on other linux based OSes or Windows.. more at #3078 

Pop!_OS installation was fresh on my new machine but the only common ground between both of these machines are that they use AMD processors instead of Intel.... The former machine (Asus) from which I reported #3078  for the first time was using AMD Ryzen 5 4500U with no dedicated GPU and my current one (OMEN) is using Ryzen 7 7840HS with RTX 4060... 

Now I have 2 laptops with the exact same issue with Pop!_OS.... The only apparent working solution currently being disabling S3 sleep from BIOS and falling back to the inefficient Modern Standby mode (S0)

@mmstick in https://github.com/pop-os/pop/issues/3078#issuecomment-1634837591 stated that it is a hardware based issue but now I am using a laptop from a different OEM and nothing except having an AMD processor is common between these devices. I understand how open source works and neither am I capable of fixing the issue myself... But atleast acknowledge that this IS AN ISSUE WITH POP_OS instead of just narrowing it down to "specific niche hardware based issue thus cant fix" thingy since both WIndows and Fedora does wake from S3 mode I tested myself. 

I really am disappointed

Previous laptop motherboard/UEFI info 

```
karthik@cosmic:~$ sudo inxi -M
Machine:
  Type: Laptop System: ASUSTeK product: VivoBook_ASUSLaptop X421IAY_M413IA
    v: 1.0 
  Mobo: ASUSTeK model: X421IAY v: 1.0 
  UEFI: American Megatrends v: X421IAY.314 date: 05/24/2022
```

neofetch
```
karthik@cosmic:~$ neofetch
             /////////////                 karthik@cosmic
         /////////////////////             --------------
      ///////*767////////////////          OS: Pop!_OS 22.04 x86_64
    //////7676767676*//////////////        Host: VivoBook_ASUSLaptop X421IAY_M413IA 1.0
   /////76767//7676767//////////////       Kernel: 6.2.6-76060206-generic
  /////767676///*76767///////////////      Uptime: 4 mins
 ///////767676///76767.///7676*///////     Packages: 3308 (dpkg), 1 (flatpak)
/////////767676//76767///767676////////    Shell: bash 5.1.16
//////////76767676767////76767/////////    Resolution: 1920x1080 @ 60Hz
///////////76767676//////7676//////////    DE: GNOME 42.5
////////////,7676,///////767///////////    WM: Mutter (Wayland)
/////////////*7676///////76////////////    WM Theme: Pop-dark
///////////////7676////////////////////    Theme: Pop-dark [GTK2/3/4]
 ///////////////7676///767////////////     Icons: Numix-Circle [GTK2/3/4]
  //////////////////////'////////////      Font: Bahnschrift (11pt) [GTK2/3/4]
   //////.7676767676767676767,//////       Cursor: breeze (24px)
    /////767676767676767676767/////        Terminal: gnome-terminal-server
      ///////////////////////////          Terminal Font: JetBrains Mono (14pt)
         /////////////////////             CPU: AMD Ryzen 5 4500U (6) @ 4.011 GHz
             /////////////                 GPU: AMD Renoir
                                           Memory: 1.78 GiB / 7.18 GiB (24%)
                                           Disk (/): 88.36 GiB / 146 GiB (60%)
                                           Battery: 77% [Discharging]
                                           Locale: en_GB.UTF-8

                                           ████████████████████████
                                           ████████████████████████
```

New laptop motherboard/UEFI info:

```
karthik@cosmic:~$ sudo inxi -M
Machine:
  Type: Laptop System: HP product: OMEN by HP Gaming Laptop 16-xf0xxx
    v: Type1ProductConfigId 
  Mobo: HP model: 8BCA v: 77.39 UEFI: Insyde v: F.10
    date: 08/10/2023
```

New laptop neofetch:
```
karthik@cosmic:~$ neofetch
             /////////////                karthik@cosmic 
         /////////////////////            -------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: OMEN by HP Gaming Laptop 16-xf0xxx 
   /////76767//7676767//////////////      Kernel:  6.5.4-76060504-generic
  /////767676///*76767///////////////     Uptime: 20 mins 
 ///////767676///76767.///7676*///////    Packages: 2280 (dpkg) 
/////////767676//76767///767676////////   Shell: bash 5.1.16 
//////////76767676767////76767/////////   Resolution: 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 42.5 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16) @ 5. 
    /////767676767676767676767/////       GPU: NVIDIA 01:00.0 NVIDIA Corporation Device 28a0 
      ///////////////////////////         GPU: AMD ATI 05:00.0 Device 15bf 
         /////////////////////            Memory: 2549MiB / 15172MiB 
             /////////////
                                                                  
```

**Comment by leviport** [comment] 2023-10-06 14:08
I understand issues like this are frustrating, but please don't make duplicate issues. It makes our bug tracker messy and makes it harder to track important info about issues, which makes it harder for us to actually work on those issues.

Closing as a duplicate of https://github.com/pop-os/pop/issues/3078

**Closed by leviport** 2023-10-06 14:08 UTC

**Comment by ron-hs** [comment] 2026-04-07 01:15
## Confirmed fix for AMD 7730U (Barcelo) on BANGHO MAX L5 R7 Z3 / Clevo NS50/NS70

After debugging, confirmed root cause and working fix for
this class of hardware.

**Root cause**: The BIOS (Insyde Corp, BANGHO/Clevo ODM) incorrectly sets
`LOW_POWER_S0_IDLE_CAPABLE` (FADT bit 21) to 1, which causes Linux to
suppress S3 entirely. The DSDT correctly defines `_S3_` with valid values
`{3,3,0,0}` — the hardware fully supports S3 but the BIOS misconfiguration
hides it from the kernel.

**Fix**: [Smokeless UMAF](https://github.com/DavidS95/Smokeless_UMAF)
→ Device Manager → AMD PBS → S3/Modern Standby Support → **S3 Enable**

This clears `LOW_POWER_S0_IDLE_CAPABLE` at the firmware level.

**Before**:
cat /sys/power/mem_sleep → [s2idle]
ACPI: PM: (supports S0 S4 S5)

**After**:
cat /sys/power/mem_sleep → s2idle [deep]
ACPI: PM: (supports S0 S3 S4 S5)


**Also needed** (AMD GPU hang on s2idle resume):
sudo kernelstub -a "amdgpu.runpm=0"


A kernel ACPI quirk has been filed at bugzilla.kernel.org to fix this
automatically for all Linux users on this hardware without requiring
BIOS modification.

Hardware: BANGHO MAX L5 R7 Z3, AMD Ryzen 7 7730U, Insyde BIOS 1.07.30RPC1
Kernel: 6.18.7, Pop!_OS 24.04
