### ISSUE TITLE
应用商店有时卡住。

### ISSUE THREAD

**Issue by zrrzw** [pop-os/pop#362] opened 2018-10-05 09:02 UTC
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**
只要在安装更新时按主页，就会未响应。

**Expected behavior:**

**Other Notes:**

**Comment by jacobgkau** [comment] 2021-06-22 20:58
The title translates to "App store sometimes gets stuck." Closing as a duplicate of https://github.com/pop-os/shop/issues/240.

**Closed by jacobgkau** 2021-06-22 20:58 UTC
