### ISSUE TITLE
Scaling errors on lates updates

### ISSUE THREAD

**Issue by Anirudh-C** [pop-os/pop#1170] opened 2020-07-30 12:56 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 **Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
hidpi-daemon:
  Installed: 18.04.6~1594738317~20.04~cfe8850
  Candidate: 18.04.6~1594738317~20.04~cfe8850
  Version table:
 *** 18.04.6~1594738317~20.04~cfe8850 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
After the latest updates at each reboot the scaling is at 200% and it gets fixed for the session if the font-scaling is changed as shown [here](https://imgur.com/gallery/gqyBIQB) but the issue persists across reboots.

**Steps to reproduce (if you know):**

**Expected behavior:**
The scaling must be at the default 100% at boot rather than 200%.

**Comment by alesspalma** [comment] 2020-07-30 15:25
Same problem but got scale 100% at startup (apparently normal), with still strange font size. To resolve it, is sufficient to go on tweaks->font->font size and just move up and down or down and up, it will fix automatically but ONLY for that session. Upon restart same problem. 

on startup (wrong font size):
![Screenshot from 2020-07-30 17-21-42](https://user-images.githubusercontent.com/48835050/88941607-83b12a80-d289-11ea-9a0a-1eba2ae81154.png)
![Screenshot from 2020-07-30 17-22-01](https://user-images.githubusercontent.com/48835050/88941659-93c90a00-d289-11ea-9524-d3f00df87b08.png)

after playing wiyth font size (adjusted):
![Screenshot from 2020-07-30 17-22-03](https://user-images.githubusercontent.com/48835050/88941702-9f1c3580-d289-11ea-8047-89bd3b5fe308.png)
![Screenshot from 2020-07-30 17-22-06](https://user-images.githubusercontent.com/48835050/88941707-a04d6280-d289-11ea-9c76-2689d74dd425.png)

**Comment by brs17** [comment] 2020-07-30 15:31
`/var/log/apt/history.log` logs showing which programs were updated before I rebooted and saw weird scaling issues:

```
Start-Date: 2020-07-30  08:59:55
Commandline: apt upgrade
Requested-By: shpurk (1000)
Install: libstd-rust-1.43:amd64 (1.43.0+dfsg1+llvm-1~exp1ubuntu1~20.04.1, automatic)
Upgrade: gnome-control-center-data:amd64 (1:3.36.3-0ubuntu1pop1~1595273700~20.04~034354a, 1:3.36.4-0ubuntu1pop1~1596049125~20.04~426adb3), gnome-shell-extension-prefs:amd64 (3.36.3-1ubuntu1~20.04.2pop1~1594933802~20.04~0deca58, 3.36.4-1ubuntu1~20.04.1pop1~1596049193~20.04~dac12e5), gir1.2-mutter-6:amd64 (3.36.3-0ubuntu0.20.04.1pop1~1594405059~20.04~8e2b857, 3.36.4-0ubuntu0.20.04.1pop1~1596049152~20.04~afeacee), gnome-control-center:amd64 (1:3.36.3-0ubuntu1pop1~1595273700~20.04~034354a, 1:3.36.4-0ubuntu1pop1~1596049125~20.04~426adb3), rustc:amd64 (1.41.0+dfsg1+llvm-0ubuntu2, 1.43.0+dfsg1+llvm-1~exp1ubuntu1~20.04.1), firefox-locale-zh-hans:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), firefox-locale-zh-hant:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), popsicle-gtk:amd64 (0.1.5~1595514274~20.04~75f62c9, 0.1.5~1595969175~20.04~57718b2), libsystemd0:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b), grub-common:amd64 (2.04-1ubuntu26, 2.04-1ubuntu26.1), libsystemd-dev:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b), popsicle:amd64 (0.1.5~1595514274~20.04~75f62c9, 0.1.5~1595969175~20.04~57718b2), grub2-common:amd64 (2.04-1ubuntu26, 2.04-1ubuntu26.1), udev:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b), libstd-rust-dev:amd64 (1.41.0+dfsg1+llvm-0ubuntu2, 1.43.0+dfsg1+llvm-1~exp1ubuntu1~20.04.1), libmutter-6-0:amd64 (3.36.3-0ubuntu0.20.04.1pop1~1594405059~20.04~8e2b857, 3.36.4-0ubuntu0.20.04.1pop1~1596049152~20.04~afeacee), grub-pc:amd64 (2.04-1ubuntu26, 2.04-1ubuntu26.1), libudev1:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b), mutter-common:amd64 (3.36.3-0ubuntu0.20.04.1pop1~1594405059~20.04~8e2b857, 3.36.4-0ubuntu0.20.04.1pop1~1596049152~20.04~afeacee), systemd-timesyncd:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b), grub-pc-bin:amd64 (2.04-1ubuntu26, 2.04-1ubuntu26.1), libudev-dev:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b), firefox-locale-ar:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), firefox-locale-de:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), systemd-sysv:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b), firefox-locale-en:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), firefox-locale-es:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), firefox-locale-fr:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), firefox-locale-it:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), firefox-locale-ja:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), firefox-locale-pt:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), firefox-locale-ru:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), cargo:amd64 (0.42.0-0ubuntu1, 0.44.1-0ubuntu1~20.04.1), gnome-shell-common:amd64 (3.36.3-1ubuntu1~20.04.2pop1~1594933802~20.04~0deca58, 3.36.4-1ubuntu1~20.04.1pop1~1596049193~20.04~dac12e5), libpam-systemd:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b), systemd:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b), libnss-systemd:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b), pop-shop:amd64 (3.3.0pop0~1589405854~20.04~72b0ae9, 3.3.0pop0~1595605854~20.04~a0600bb), gnome-control-center-faces:amd64 (1:3.36.3-0ubuntu1pop1~1595273700~20.04~034354a, 1:3.36.4-0ubuntu1pop1~1596049125~20.04~426adb3), firefox:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1), systemd-container:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b), gnome-shell:amd64 (3.36.3-1ubuntu1~20.04.2pop1~1594933802~20.04~0deca58, 3.36.4-1ubuntu1~20.04.1pop1~1596049193~20.04~dac12e5), mutter:amd64 (3.36.3-0ubuntu0.20.04.1pop1~1594405059~20.04~8e2b857, 3.36.4-0ubuntu0.20.04.1pop1~1596049152~20.04~afeacee)
```

**Comment by leviport** [comment] 2020-07-30 15:32
I'm also seeing this happen in GDM
After reboot: 
![smalltext-lockscreen](https://user-images.githubusercontent.com/13512097/88942071-01077b80-d247-11ea-8675-f34770c2b534.png)
What lock screen should look like:
![normal-lockscreen](https://user-images.githubusercontent.com/13512097/88942142-15e40f00-d247-11ea-9dbe-39fa9c8f9313.png)

Note: Scaling goes back to normal after restarting Gnome (Alt+F2, r, enter)

**Comment by jackpot51** [comment] 2020-07-30 15:34
Here's your update list prettified:

```
cargo:amd64 (0.42.0-0ubuntu1, 0.44.1-0ubuntu1~20.04.1)
firefox:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
firefox-locale-ar:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
firefox-locale-de:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
firefox-locale-en:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
firefox-locale-es:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
firefox-locale-fr:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
firefox-locale-it:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
firefox-locale-ja:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
firefox-locale-pt:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
firefox-locale-ru:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
firefox-locale-zh-hans:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
firefox-locale-zh-hant:amd64 (78.0.2+build2-0ubuntu0.20.04.1, 79.0+build1-0ubuntu0.20.04.1)
gir1.2-mutter-6:amd64 (3.36.3-0ubuntu0.20.04.1pop1~1594405059~20.04~8e2b857, 3.36.4-0ubuntu0.20.04.1pop1~1596049152~20.04~afeacee)
gnome-control-center:amd64 (1:3.36.3-0ubuntu1pop1~1595273700~20.04~034354a, 1:3.36.4-0ubuntu1pop1~1596049125~20.04~426adb3)
gnome-control-center-data:amd64 (1:3.36.3-0ubuntu1pop1~1595273700~20.04~034354a, 1:3.36.4-0ubuntu1pop1~1596049125~20.04~426adb3)
gnome-control-center-faces:amd64 (1:3.36.3-0ubuntu1pop1~1595273700~20.04~034354a, 1:3.36.4-0ubuntu1pop1~1596049125~20.04~426adb3)
gnome-shell:amd64 (3.36.3-1ubuntu1~20.04.2pop1~1594933802~20.04~0deca58, 3.36.4-1ubuntu1~20.04.1pop1~1596049193~20.04~dac12e5)
gnome-shell-common:amd64 (3.36.3-1ubuntu1~20.04.2pop1~1594933802~20.04~0deca58, 3.36.4-1ubuntu1~20.04.1pop1~1596049193~20.04~dac12e5)
gnome-shell-extension-prefs:amd64 (3.36.3-1ubuntu1~20.04.2pop1~1594933802~20.04~0deca58, 3.36.4-1ubuntu1~20.04.1pop1~1596049193~20.04~dac12e5)
grub2-common:amd64 (2.04-1ubuntu26, 2.04-1ubuntu26.1)
grub-common:amd64 (2.04-1ubuntu26, 2.04-1ubuntu26.1)
grub-pc:amd64 (2.04-1ubuntu26, 2.04-1ubuntu26.1)
grub-pc-bin:amd64 (2.04-1ubuntu26, 2.04-1ubuntu26.1)
libmutter-6-0:amd64 (3.36.3-0ubuntu0.20.04.1pop1~1594405059~20.04~8e2b857, 3.36.4-0ubuntu0.20.04.1pop1~1596049152~20.04~afeacee)
libnss-systemd:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b)
libpam-systemd:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b)
libstd-rust-dev:amd64 (1.41.0+dfsg1+llvm-0ubuntu2, 1.43.0+dfsg1+llvm-1~exp1ubuntu1~20.04.1)
libsystemd0:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b)
libsystemd-dev:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b)
libudev1:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b)
libudev-dev:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b)
mutter:amd64 (3.36.3-0ubuntu0.20.04.1pop1~1594405059~20.04~8e2b857, 3.36.4-0ubuntu0.20.04.1pop1~1596049152~20.04~afeacee)
mutter-common:amd64 (3.36.3-0ubuntu0.20.04.1pop1~1594405059~20.04~8e2b857, 3.36.4-0ubuntu0.20.04.1pop1~1596049152~20.04~afeacee)
pop-shop:amd64 (3.3.0pop0~1589405854~20.04~72b0ae9, 3.3.0pop0~1595605854~20.04~a0600bb)
popsicle:amd64 (0.1.5~1595514274~20.04~75f62c9, 0.1.5~1595969175~20.04~57718b2)
popsicle-gtk:amd64 (0.1.5~1595514274~20.04~75f62c9, 0.1.5~1595969175~20.04~57718b2)
rustc:amd64 (1.41.0+dfsg1+llvm-0ubuntu2, 1.43.0+dfsg1+llvm-1~exp1ubuntu1~20.04.1)
systemd:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b)
systemd-container:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b)
systemd-sysv:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b)
systemd-timesyncd:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b)
udev:amd64 (245.4-4ubuntu3.1pop0~1590695674~20.04~eaac747, 245.4-4ubuntu3.2pop1~1596049172~20.04~c9d8f2b)
```

**Comment by alesspalma** [comment] 2020-07-30 15:38
> I'm also seeing this happen in GDM
> After reboot:
> ![smalltext-lockscreen](https://user-images.githubusercontent.com/13512097/88942071-01077b80-d247-11ea-8675-f34770c2b534.png)
> What lock screen should look like:
> ![normal-lockscreen](https://user-images.githubusercontent.com/13512097/88942142-15e40f00-d247-11ea-9dbe-39fa9c8f9313.png)
> 
> Note: Scaling goes back to normal after restarting Gnome (Alt+F2, r, enter)

on my laptop restarting Gnome (Alt+F2, r, enter) doesn't resolve anything

**Comment by leviport** [comment] 2020-07-30 15:46
People with the issue: can you :+1: this comment if you have Nvidia graphics? If not, please :-1: instead.

**Comment by leviport** [comment] 2020-07-30 20:51
Fixed via https://github.com/pop-os/mutter/pull/7

**Closed by leviport** 2020-07-30 20:51 UTC

**Comment by alesspalma** [comment] 2020-07-31 00:01
as a normal user, how do I fix the scaling error issue on my laptop?

**Comment by A-Random-Lantern** [comment] 2020-07-31 00:09
Set scaling to 200% in settings then change it back to 100%, it'll fix it for the session.

**Comment by alesspalma** [comment] 2020-07-31 00:13
> Set scaling to 200% in settings then change it back to 100%, it'll fix it for the

Sir, we already know it as stated in my first comment. We need a definitive solution.

**Comment by mmstick** [comment] 2020-07-31 03:11
@alesspalma When we merge PRs, they get automatically packaged for Proposed, and once they build from Proposed, it isn't long before the updates are released to everyone. It's been released as of this moment.

**Comment by Anirudh-C** [comment] 2020-07-31 03:29
Just got the updates and its been fixed! Thank you so much devs.

**Comment by alesspalma** [comment] 2020-07-31 08:24
Thanks!

**Comment by jacobgkau** [comment] 2020-08-24 17:01
> At boot scaling factor seems to reset always to 200%. Is there some setting I have to apply that I am not applying in order to fix it?

Are you saying the scaling factor in Settings -> Displays is set to 200%? The issue you're commenting on was with the scaling factor appearing set to 100%, but font sizes being slightly larger (or smaller, in some cases) than they should have been.

There was a brief period last Thursday where an update was pushed that re-introduced this issue. A subsequent update was pushed a few hours later to fix it again. This bug was in Mutter (not related to the HiDPI daemon-- the daemon actually mitigated the issue by changing scaling settings on login.) Can you please install all updates, reboot, and if the issue is still occurring, show us what version of Mutter you have installed:

`apt policy libmutter-6-0`

Does your non-System76 machine have NVIDIA, AMD, or Intel graphics? What are the resolution of your displays, and are any of them HiDPI? Does the issue continue to occur if you disable the HiDPI daemon?

**Comment by Befo** [comment] 2020-08-25 20:03
Hi @jacobgkau,
I believe I have misunderstood the issue then. The stated scaling factor in Gnome settings was correctly reported at 200% but I needed it at 100%. After having set it at 100% whenever I restarted the system Gnome was starting at 200%, with stated scaling factor at 200% to clear any doubts. I don't know if it is an issue of the HiDpi Daemon at this point. I thought this thread was describing this same bug.

But I believe the bug still persists as I was experiencing the issue on Sunday after a clean install and subsequent updates. Sadly, I am now on Ubuntu 20.04 (please forgive me, I could not use the multimonitor :-) with just text scaling) and here scaling is behaving correctly and also in multimonitor setup (fractional scaling also after having enabled it).

I am using an LG gram 17" 2020, so the graphics is the Intel Iris plus in the chipset i7-1065g7 and resolution is 2560 x 1600 (16:10).
I tried to disable the hidpi daemon but I can't remember if I rebooted with it disabled. I don't think I have, but I would not swear by it.
