### ISSUE TITLE
Screen tearing and low frame rates while using external display  in hybrid graphics mode

### ISSUE THREAD

**Issue by aswintb** [pop-os/pop#1283] opened 2020-10-09 06:10 UTC
I'm running Pop!_OS 20.04 LTS x86_64 on my Lenovo Legion 5i my kernel version is 5.4.0-7642-generic 
CPU: Intel i7-10750H (12) @ 2.600GHz
GPU: GeForce GTX 1650 Ti                                               
GPU driver version: 455.28

I am experiencing screen tearing issues and very low frame rates on my external monitor when i boot pop os in Hybrid Graphics mode.There is no issue using the external monitor when the graphics mode is set to Nvidia Graphics.,If I want to use my laptop on Hybrid Graphics I still need to rely on my Built in display

**Comment by leviport** [comment] 2020-10-09 13:16
Duplicate of https://github.com/pop-os/nvidia-graphics-drivers/issues/61

**Closed by leviport** 2020-10-09 13:16 UTC
