### ISSUE TITLE
Bluetooth not working in 21.10

### ISSUE THREAD

**Issue by allout58** [pop-os/pop#2097] opened 2021-12-20 16:49 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Unable to start bluetooth after upgrading from 21.04 to 21.10.
When enabling bluetooth in the settings app, only the toggle switch changes, and closing and reopening the settings app shows the toggle switch as off again.

**Steps to reproduce (if you know):**
Upgrade to 21.10
Try to toggle bluetooth in the settings app or the dropdown control menu in the top right.

**Expected behavior:**

Bluetooth to work

**Other Notes:**

Related to #2079 and #2093.

**Hardware**
Dell Inspiron 15-7579

**Comment by jacobgkau** [comment] 2021-12-20 16:51
Closing as a duplicate of https://github.com/pop-os/pop/issues/2093, will rename that one to be more generic.

**Closed by jacobgkau** 2021-12-20 16:51 UTC

**Comment by jacobgkau** [comment] 2021-12-20 16:54
Just to be clear, does your screenshot show the "Plug a dongle in to use Bluetooth." message that #2093 shows? I assume you're seeing the exact same thing since you said it's related. Otherwise, I don't know why these would be related.

**Comment by allout58** [comment] 2021-12-20 17:14
Sorry, I didn't see the screenshot on that one. No, my laptop has integrated bluetooth.

... Just went to go take a screenshot of my settings page and suddenly previously connected devices show up and I can interact correctly, very weird.

**Comment by allout58** [comment] 2021-12-21 16:20
And now it's not working again...

Here's what the settings page starts as:
![image](https://user-images.githubusercontent.com/2939703/146963530-8ab027fe-d2f4-449d-8da2-899f55cafb7f.png)

And here it is after clicking the toggle.
![image](https://user-images.githubusercontent.com/2939703/146963595-0695833f-1931-41dd-86e3-3fc29082797a.png)

**Comment by jacobgkau** [comment] 2021-12-21 16:23
Thank you for the screenshots. Those look like the screenshots in https://github.com/pop-os/pop/issues/1153.

**Comment by allout58** [comment] 2021-12-21 16:29
Thanks! I'm sorry I didn't look more, I wasn't having this problem on 21.04 so I assumed it was a new issue and didn't look back too far, whooops :grimacing:
