### ISSUE TITLE
Applications don't close with the close shortcut

### ISSUE THREAD

**Issue by frogtd** [pop-os/pop#1056] opened 2020-05-25 00:30 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Applications don't close with the close shortcut
**Steps to reproduce (if you know):**

1. Open a application
2. Close it using the close Shortcut
3. It still shows up on the left in the app switcher

**Expected behavior:**

The application closes.

**Other Notes:**

**Comment by leviport** [comment] 2020-05-26 18:30
Duplicate of https://github.com/pop-os/shell/issues/220

**Closed by leviport** 2020-05-26 18:30 UTC
