### ISSUE TITLE
java audio bug since moving to pipewire in 22.04

### ISSUE THREAD

**Issue by ryannathans** [pop-os/pop#2547] opened 2022-07-27 10:55 UTC
**Distribution (run `cat /etc/os-release`):**
 
 ```
 $ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
$ apt policy pipewire
pipewire:
  Installed: 0.3.56-0pop1~1658336739~22.04~a3894c2
  Candidate: 0.3.56-0pop1~1658336739~22.04~a3894c2
  Version table:
 *** 0.3.56-0pop1~1658336739~22.04~a3894c2 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu1 500
        500 http://au.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
```

**Issue/Bug Description:**
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2596

[javamusicissue.webm](https://user-images.githubusercontent.com/1307375/181230213-314a4701-6a87-4daf-b686-8f722f5ce3db.webm)

**Steps to reproduce (if you know):**
1. install java 11 (sudo apt install openjdk-11-jre)
2. launch game with 2009scape launcher - https://gitlab.com/2009scape/Saradomin-Launcher or via the classic launcher on https://2009scape.org/
3. play the game or sit on the main menu, the music is very start/stoppy but sound effects work fine (like cutting a tree)

**Expected behavior:**
music plays normally and smoothly like it does on other distros

**Other Notes:**
**this bug was introduced in 22.04, but does not seem to occur on all pipewire distros**

**Comment by 1player** [comment] 2022-09-04 15:59
Probably related: https://github.com/runelite/runelite/issues/14882

It's not unique to PopOS, it's caused by pipewire, but the jury is still out if it's a pipewire or application bug (which would mean OpenJDK bug this being a Java application)

**Comment by ryannathans** [comment] 2022-09-13 05:27
> Probably related: https://github.com/runelite/runelite/issues/14882
very interesting! looks like it's fixed in the latest pipewire according to that thread - hopefully pop push that out to us soon

> It's not unique to PopOS, it's caused by pipewire, but the jury is still out if it's a pipewire or application bug (which would mean OpenJDK bug this being a Java application)

updated description/title

**Comment by ryannathans** [comment] 2022-09-13 05:30
https://github.com/pop-os/pipewire/issues/25
same/related

**Comment by mmstick** [comment] 2022-09-13 12:23
I'll update Pipewire when that version is released with the fix

**Comment by mmstick** [comment] 2022-09-15 16:51
Closing since this is a duplicate

**Closed by mmstick** 2022-09-15 16:51 UTC
