### ISSUE TITLE
Sound Dummy Output after system's previous update

### ISSUE THREAD

**Issue by Alex-Rzh** [pop-os/pop#2686] opened 2022-11-07 12:28 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
-- 

**Issue/Bug Description:**
After system updates from 03 Nov 2022 my laptop can't recognize all audio devices such as speakers and microphones. There is only  'Dummy Output' in the Output chapter of the Sound Settings tab.
How can I fix it?

**Steps to reproduce (if you know):**
-- 

**Expected behavior:**
Get my sound back

**Other Notes:**

![Screenshot from 2022-11-07 15-05-31](https://user-images.githubusercontent.com/80095152/200310077-d448f7da-2e46-4a56-9fad-14102713f9da.png)
![Screenshot from 2022-11-07 14-59-25](https://user-images.githubusercontent.com/80095152/200310084-2983c921-3ae3-4544-a1d9-8d5757ac22f6.png)
![Screenshot from 2022-11-07 14-58-18](https://user-images.githubusercontent.com/80095152/200310087-5ea7bde0-a403-40f7-b566-d40d3080f085.png)

**Comment by devsquad-lucas-tomaz** [comment] 2022-11-07 16:28
Same here, I even tried a new fresh install.

**Comment by leviport** [comment] 2022-11-07 16:49
I believe this is a duplicate of https://github.com/pop-os/pop/issues/2487

If so, kernel 6.0.6 should fix the problem.

**Closed by leviport** 2022-11-07 16:49 UTC
