### ISSUE TITLE
19.10- Shutdown and reboot do not work before login

### ISSUE THREAD

**Issue by MichaelVash7886** [pop-os/pop#776] opened 2019-12-05 13:07 UTC
**Distribution (run `cat /etc/os-release`):**
19.10
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
I just did sudo apt update, sudo apt upgrade before trying this again. 

**Issue/Bug Description:**
Before logging into the machine there is a reboot/shutdown button in the top right. I can bring up the reboot shutdown menu but when I choose shutdown or reboot, nothing happens. 

**Steps to reproduce (if you know):**
Boot to login screen. Before logging in go to top right corner click menu. Click power button. Click shutdown or reboot. 

**Expected behavior:**
Machine should reboot or shutdown 

**Other Notes:**
Nothing happens when I click shutdown or reboot.

**Comment by brs17** [comment] 2019-12-05 15:56
This is a duplicate of https://github.com/pop-os/pop/issues/708 . Please read there for link to upstream bug report and progress on fixing the issue.

**Closed by brs17** 2019-12-05 15:56 UTC

**Comment by MichaelVash7886** [comment] 2019-12-05 16:00
Thanks.
