### ISSUE TITLE
Pop!_OS 18.04 LTS will not log in to the desktop environment from GDM

### ISSUE THREAD

**Issue by cdknight** [pop-os/pop#238] opened 2018-04-29 12:44 UTC
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
gdm3:
  Installed: 3.28.0-0ubuntu1pop2
  Candidate: 3.28.0-0ubuntu1pop2
  Version table:
 *** 3.28.0-0ubuntu1pop2 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     3.28.0-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
pop-session:
  Installed: 2.0.4~1524969709~18.04~8c55250
  Candidate: 2.0.4~1524969709~18.04~8c55250
  Version table:
 *** 2.0.4~1524969709~18.04~8c55250 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description**

Upon typing in the password in gdm3 and attempting to log in, the computer stays at a grey screen and does not start the GNOME desktop environment.

**Steps to reproduce (if you know)**
Power up a Pop!_OS 18.04 LTS computer, and attempt to log in normally. The computer will not enter the GNOME desktop environment.

**Expected behavior**
The computer logs in successfully to the desktop environment.

**Other Notes**
The solution for this issue for the time being is not click the "Not listed?" in gdm, and log in that way.
This issue also only happens on my laptop with Intel graphics (I used the Intel/AMD ISO file as well)

**Comment by jackpot51** [comment] 2018-04-29 13:02
What is your `apt-cache policy pop-session`?

**Comment by cdknight** [comment] 2018-04-29 13:25
pop-session:
  Installed: 2.0.4~1524969709~18.04~8c55250
  Candidate: 2.0.4~1524969709~18.04~8c55250
  Version table:
 *** 2.0.4~1524969709~18.04~8c55250 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by jackpot51** [comment] 2018-04-29 13:28
After clicking on your user account, there should be a gear icon next to the green button for selecting the session type. The session type should be set to `Pop`. Please let me know what it is set to, or if the gear icon appears. If it does not appear, that means only one session type is available.

**Comment by cdknight** [comment] 2018-04-29 14:14
The gear is set to Pop, not Pop on Wayland

**Comment by jackpot51** [comment] 2018-04-29 14:51
Out of curiosity, does it work if you switch to Pop on Wayland?

**Comment by kristho91** [comment] 2018-05-01 18:59
I have an issue that sounds exactly what @cdknight is describing. Newly installed Pop!_OS 18.04.
But I can not log into either Pop or Pop on Wayland sessions

**Comment by cdknight** [comment] 2018-05-01 19:26
Hm. What about from "Not listed?"

**Comment by cdknight** [comment] 2018-05-01 22:06
Edit: the bug is back, this time on my NVIDIA machine! I think it has to do with entering the BIOS/UEFI setup, exiting, and booting (that doesn't make any sense though). After switching ttys, then coming back to tty1 (gdm), it gave my an authentication error message, threw me back to the login screen, I logged in, and the computer works as normal.

**Comment by kristho91** [comment] 2018-05-02 07:03
@cdknight 
Nope - "Not listed" doesn't work either :) I simply can't get to the desktop at all :(

**Comment by jasonflindt** [comment] 2018-05-07 23:33
This is the same issue I had with ubuntu 18.04 . Hence the reason im on pop! now full time .

**Comment by cdknight** [comment] 2018-05-07 23:34
It seems to me that many of these preliminary issues with pop have been mostly resolved. Now pop is pretty stable, and with a latest ISO or "sudo apt update && sudo apt upgrade" you should be able to fix most problems.

**Comment by linuxgnuru** [comment] 2018-05-22 13:56
Same issue here; I have a system 76 bonobo (nvidia 1070)  that came with 17.10.  I installed the nvidia 396.24 via the PPA (`add-apt-repository ppa:graphics-drivers/ppa`) before upgrading to 18.04 via do-release-upgrade but after rebooting, I could not login.  One difference that I have is I could not even switch to console via ctrl+alt+f[2-6] and had to instead ssh into it to do anything.  I can get it running in multi-user.target and startx but gdm3 is a no go. 


Distribution:
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

gdm3:
  Installed: 3.28.0-0ubuntu1pop3
  Candidate: 3.28.0-0ubuntu1pop3
  Version table:
 *** 3.28.0-0ubuntu1pop3 776
        776 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     3.28.0-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

**Comment by cdknight** [comment] 2018-05-24 10:38
For me when this happens I do Ctrl alt f2, and then switch to gdm with f1. Not sure, but if you try kill -9 -1 in ssh, gdm might restart, and you can try logging in again.

**Comment by luisfmrosa** [comment] 2018-05-27 10:59
+1 having the same issue after upgrading to 18.04. Unable to logging in.

**Comment by HennieLouw** [comment] 2018-05-30 06:32
Hi All,
I've been having the same issue and was following the bug tracker for GDM3.
[https://bugs.launchpad.net/ubuntu/+source/gdm3/+bug/1766137](https://bugs.launchpad.net/ubuntu/+source/gdm3/+bug/1766137)

The  bug has been fixed and relased to Ubuntu 18.04 Proposed repo. 
Tested by using the following procedure.

1. Update apt source list to include ubuntu proposed.
`deb http://au.archive.ubuntu.com/ubuntu/ bionic-proposed main restricted universe multiverse`

2. Setup a apt pinnig policy to ensure we get the latest GDM3 and depedencies from the proposed repo instead of PopOS repo, **but nothing else to maintain stablity of the system.**
`nano /etc/apt/preferences.d/gdm-proposed-fix`

```
Package: gdm3
Pin: release o=*
Pin-Priority: 1001

Package: libgdm1
Pin: release o=*
Pin-Priority: 1001

Package: gir1.2-gdm-1.0
Pin: release o=*
Pin-Priority: 1001

Package: *
Pin: release a=bionic-proposed
Pin-Priority: 400
``` 
3. Verify that the proposed fix is installable.
`apt policy gdm3`

```
gdm3:
  Installed: 3.28.0-0ubuntu1.1pop1
  Candidate: 3.28.2-0ubuntu1.1
  Version table:
     3.28.2-0ubuntu1.1 1001
        400 http://au.archive.ubuntu.com/ubuntu bionic-proposed/main amd64 Packages
 *** 3.28.0-0ubuntu1.1pop1 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
     3.28.0-0ubuntu1 1001
        500 http://au.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```
4. Perform upgrade
`sudo apt update && apt upgrade`

5. Restart GDM service.
`sudo systemctrl restart gdm`

Worked well for me and should allow for gdm3 updates from PopOs repos once the proposed is premoted.

**Comment by jackpot51** [comment] 2018-05-30 11:47
We have our own patches to GDM, so we will be releasing our patched version soon

**Comment by jackpot51** [comment] 2018-05-30 16:10
We have released the package in proposed, migration will happen shortly

**Comment by HennieLouw** [comment] 2018-05-31 01:12
Great news :)
I see it is in the Pop!_OS proposed PPA, which is not enabled on the default install.
https://launchpad.net/~system76/+archive/ubuntu/proposed

Would you consider the proposed PPA stable for a daily driver or should I wait till it's promoted to the 'stable' PPA?
https://launchpad.net/~system76/+archive/ubuntu/pop

**Comment by mmstick** [comment] 2018-05-31 01:39
@HennieLouw Only if you don't mind the occasional possibility of breakage. By definition, it's a testing repository.

**Comment by HennieLouw** [comment] 2018-05-31 04:14
@mmstick 
Naturally, it's a testing repo. But there is are varying levels of stability in testing repositories. 
Some can be used for daily drivers and some are just outright unstable :) 

My question was more to determine for your average non-power user if it would be a good idea to enable this repo from the System76 PPA team's point of view as they have the knowledge of when they release items into it.

**Comment by jackpot51** [comment] 2018-05-31 17:28
The package has been released, so you do not need the proposed PPA anymore

**Closed** 2018-05-31 17:28 UTC

**Comment by HennieLouw** [comment] 2018-06-01 02:05
Hi Jeremy.
Thanks for the quick turn-around.

I can confirm for anybody else that used my steps for ubuntu-proposed repo, that GDM3 is updated to the one from Pop!_Os without me needing to do anything. (Could now remove the residual config)

I've been dabbling with *nix for a bit, but it was actually Pop!_Os that made me decide to redo my laptop and drop windows all together :)

This experience with the turn-around on defects has simply confirmed it for me that it was the right decision.

**Comment by igorbzin** [comment] 2018-08-06 17:43
The issue is still present, after a couple of restarts suddenly I can not log in any more, also tried to reinstall the entire OS again, happens every time. I tried every suggestion to make it work, nothing fixed the issue. Too bad this bug is preventing me from using PopOS

**Comment by apmmadeira** [comment] 2018-09-14 14:28
Is there an update on this issue?
A colleague of mine has just become unable to login today after running the last updates.

**Comment by jackpot51** [comment] 2018-09-14 14:45
@igorbzin @io-ma @apmmadeira This issue as described by the original reporter has been fixed. Please open a new issue.

**Comment by io-ma** [comment] 2018-09-15 17:29
I was able to solve the problem with a fresh install.

**Comment by vgjenks** [comment] 2019-02-04 20:45
Same. I’m completely screwed, after a month of solid use. None of the workarounds above are working for me. And thus, Linux on the desktop is still a minefield after all these years.

**Comment by mmstick** [comment] 2019-02-04 21:09
@vgjenks For what it's worth, I've been on the same install for almost ~9 months now, upgraded from bionic to cosmic. I haven't seen this issue occur during that time, despite ~10 hours of use per day.

**Comment by cdknight** [comment] 2019-02-04 23:47
#### Taken from the new issue opened about this - 
Not a fix (temporary solutions), but:
* You can change the theme to Pop!_OS's theme from `gnome-tweak-tool` after running startx. I think this is what I did when I had the problem when I clean-upgraded to 18.04 (mind you, nearly 20 minutes after release)
* You could also replace GDM with SDDM or another display manager (used to log you in ) - LightDM and SDDM are popular DMs
* You can also run `systemctl set-target multi-user.target` which will boot your system to a TTY (I think TTY1), from which you can also append to your `~/.bash_profile` (so edit the file and add to the end: (thanks Gentoo wiki) `
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec startx; fi
` and replace tty1 with the tty your system boots into (if it isn't TTY1). What this will do is when you log in on the terminal, your system will automatically start GNOME thereby getting rid of buggy GDM.

**Comment by 0p3r4t0r** [comment] 2020-05-11 15:17
I just ran into this issue. For me the fix was...

1. From the login screen (BEFORE ENTERING YOUR PASSWORD) use `ctrl + alt + f2` to access the shell.
2. Login from the shell.
3. Run `startx` from there and then popOS will boot into the desktop env. It should be working on subsequent reboots as well.

**Comment by zink-chimaera** [comment] 2020-06-29 07:21
Can confirm that this is still an issue on 20.04.
The proposed workarounds do work but are not a viable solution for most consumers.

Is there anything to resolve this issue beside reinstalling Pop!_OS?

**Comment by kaineer** [comment] 2021-07-08 10:36
Got same problem today.
Solved it from console, making `/home/username` readable/writable by me.

**Comment by svrdoljak** [comment] 2022-01-17 23:31
Got the same issue. I need to run `systemctl restart gdm` in the tty and after that I get my login screen. I don't know how it happend. At the moment this is just a temporary fix. I need to do this on each startup, which kinda sucks.
