### ISSUE TITLE
Pop OS (shop / repos) overwrites latest VS Code (1.57) with 1.56 on 'update' 

### ISSUE THREAD

**Issue by rodericktech** [pop-os/pop#1741] opened 2021-06-22 14:59 UTC
**Distribution:** 20.10
 
 
 
**Related Application and/or Package Version:** Visual Studio Code (VSCode)

**Issue/Bug Description:** The Pop repository wants to 'update' VSCode, but if I run that update it installs 1.56 rather than 1.57 (latest release from May 2021).  Pop detects 1.57.* as out-of-date and wants to install 1.56 over 1.57.

**Steps to reproduce (if you know):** Install the 1.57 (latest) deb for VSCode from https://code.visualstudio.com/ ; run apt update or open the Pop Shop; you will see that it wants to update VS Code, and it will show the version (in Pop Shop) as 1.57, but after update, the version of VS Code on the system will actually be 1.56.

**Expected behavior:** Pop repos should have the latest VS Code binaries labeled as 1.57 and not try to overwrite a newer version with an older version.

Thanks team!

**Comment by leviport** [comment] 2021-06-22 15:10
Duplicate of https://github.com/pop-os/vscode/issues/3

**Closed by leviport** 2021-06-22 15:10 UTC
