### ISSUE TITLE
Increasing number of freezes

### ISSUE THREAD

**Issue by dodalovic** [pop-os/pop#1293] opened 2020-10-14 19:23 UTC
Hi, 
I'm experiencing often freezes of my POP_OS 20.04. This now happens a couple of times a day. 
I'm running it on Dell XPS 17 (9700) 

Which kind of diagnostics I can help with?

Thanks!

**Comment by leviport** [comment] 2020-10-14 19:29
This sounds like a duplicate of https://github.com/pop-os/pop/issues/1172

Let me know if I am mistaken and I will reopen.

**Closed by leviport** 2020-10-14 19:29 UTC
