### ISSUE TITLE
My Screen/Page Gets Randomly Zoomed In And Out

### ISSUE THREAD

**Issue by ShahRahimtoola** [pop-os/pop#2743] opened 2022-12-31 14:44 UTC
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Bug occurs on any application where you can zoom in or zoom out a page. This includes the command line, FireFox, and PDF viewer. 

**Issue/Bug Description:**

The bug is that my screen/page gets randomly zoomed in and out to 120%, 60%, etc. even when I am not using my touchpad or keyboard. This happens when I am using FireFox, the command line, pdf viewers, etc. I am using a Dell Inspiron 15 5548 and I have dual booted Pop!_OS 22.04 with Windows Ten. I installed the linux distro a few days ago.

I tried disabling the HiDPI Daemon, but that did not work. I also can confirm that this is not a touchpad/hardware issue because this doesn't occur when I use windows ten.

I honestly think that the problem could be something with the drivers because my laptop is from 2015 and is pretty old.

**Steps to reproduce (if you know):**

N/A (Occurs randomly and irregularly) 

**Expected behavior:**

Page of the application gets randomly zoomed to 120%, 30%, etc.

**Other Notes:**

I was told to run `journalctl -f`, so I could see what was exactly happening when the bug occurred. These are my results:

Dec 31 19:00:18 pop-os gnome-shell[3570]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x300003e
Dec 31 19:00:19 pop-os gnome-shell[3570]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x300003e
Dec 31 19:00:20 pop-os gnome-shell[3570]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x300003e
Dec 31 19:00:24 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:24 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:24 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:24 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:25 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:25 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:25 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:25 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:26 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:26 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:26 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:26 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:26 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:26 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:26 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:26 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:27 pop-os wpa_supplicant[520]: wlp3s0: CTRL-EVENT-SIGNAL-CHANGE above=1 signal=-42 noise=9999 txrate=72200
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:27 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:29 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:29 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:29 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:29 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:30 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:30 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:30 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:30 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:30 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:30 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:30 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:30 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:32 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:32 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:32 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:32 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:33 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:33 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:33 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:33 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:33 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): EDID vendor "AUO", prod id 4588
Dec 31 19:00:33 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 31 19:00:33 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1526  768 771 777 800 +hsync -vsync (48.0 kHz eP)
Dec 31 19:00:33 pop-os /usr/libexec/gdm-x-session[3297]: (II) modeset(0): Modeline "1366x768"x0.0   73.30  1366 1406 1438 1908  768 771 777 800 +hsync -vsync (38.4 kHz e)
Dec 31 19:00:33 pop-os kernel: touchegg[3817]: segfault at 0 ip 000055b970a2330d sp 00007ffd56e56da0 error 4 in touchegg[55b970a21000+30000]
Dec 31 19:00:33 pop-os kernel: Code: 7c 24 04 89 44 24 04 e8 31 3e 01 00 48 8b 75 00 8b 43 2c 48 8b 7b 18 89 46 04 48 8b 44 24 18 64 48 2b 04 25 28 00 00 00 75 0f <48> 8b 07 48 8b 40 20 48 83 c4 28 5b 5d ff e0 e8 7f ef ff ff 90 48
Dec 31 19:00:34 pop-os systemd[3233]: app-gnome-touchegg-3817.scope: Consumed 1.616s CPU time.
Dec 31 19:00:34 pop-os touchegg[512]: Client disconnected
Dec 31 19:01:01 pop-os PackageKit[2418]: get-packages transaction /633_eacddabb from uid 1000 finished with success after 778ms
Dec 31 19:01:01 pop-os PackageKit[2418]: get-updates transaction /634_dcbecbdd from uid 1000 finished with success after 614ms

Someone just reviewed these logs for me and told me that this zooming in/out bug could have something to do with "touchegg segfaulting".

**Comment by jacobgkau** [comment] 2023-01-02 04:02
Thank you for the report. I am closing this as a duplicate of https://github.com/pop-os/touchegg/issues/9. (That issue can be transferred to another repository if it becomes necessary.)

**Closed by jacobgkau** 2023-01-02 04:02 UTC
