### ISSUE TITLE
Applications Crop in 21.04

### ISSUE THREAD

**Issue by Robin-MC** [pop-os/pop#1801] opened 2021-07-08 08:13 UTC
Just a little bug this one. The application menu in PopOS 21.04  sometimes comes up too large for the screen after a reboot (such that the icons at the edge are cropped off). if I click Workspace & then back to Applications it all comes good.I am sure this will get fixed ASAP & it will not disturb my sleep. ZZZZZZ

**Comment by jacobgkau** [comment] 2021-07-08 13:44
Duplicate of https://github.com/pop-os/pop/issues/1786.

**Closed by jacobgkau** 2021-07-08 13:44 UTC

**Comment by Robin-MC** [comment] 2021-07-09 06:39
Thanks Jacob,

That one a a bug that doesn't bite anyway.

I am much more bothered by the loss of my scanner.

Robin
