### ISSUE TITLE
Pop theme doesn't accurately indicate which scale percentage is currently active

### ISSUE THREAD

**Issue by bekips** [pop-os/pop#483] opened 2019-03-27 20:32 UTC
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Issue/Bug Description:**

by default, the scale section of gnome-settings completely whites out the currently seletected scale percentage in use, to the point it is unreadable. the other available option is marked in bold, easily readable letters. 

**Steps to reproduce (if you know):**
present on default installation. 

**Expected behavior:**

at best, this is misleading - the currently used option should be bold. ideally both should be readable at all times with a clear indication of which is being used and which is available as an alternative.

**Comment by brs17** [comment] 2019-03-28 01:01
This is a duplicate of https://github.com/pop-os/gtk-theme/issues/278 which looks like is potentially fixed here: https://github.com/pop-os/gtk-theme/pull/282

That pr should get looked at in the next week or so.

**Closed by brs17** 2019-03-28 01:01 UTC
