### ISSUE TITLE
Some weather icons are missing (blank squares are shown instead)

### ISSUE THREAD

**Issue by cesarrew** [pop-os/pop#2349] opened 2022-05-02 20:55 UTC
**Distribution (run `cat /etc/os-release`):**
 
 22.04 LTS
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

gnome-weather: 41.0-3

**Issue/Bug Description:**

Some weather icons are missing when I open the "center" menu at top panel. For some hours, only a blank square is shown. Which icons are missing depends on the day.

**Steps to reproduce (if you know):**

Open the center menu and check the icons at weather box. I don't know if the region interferes in this behavior, but my current location is Belo Horizonte, Minas Gerais, Brazil.

**Expected behavior:**

The correct icons should appear.

**Other Notes:**

![weather_app_showed_correct_icons_at_same_time](https://user-images.githubusercontent.com/17600341/166326030-686bf66e-578f-4666-b788-df3433c1d359.png)
![weather_with_missing_icons](https://user-images.githubusercontent.com/17600341/166326039-cad92e68-5e08-4dd0-ba29-88136552994a.png)

**Comment by leviport** [comment] 2022-05-02 20:58
duplicate of https://github.com/pop-os/icon-theme/issues/109

**Closed by leviport** 2022-05-02 20:58 UTC
