### ISSUE TITLE
Super key does show Workspaces despite being configured to Launcher

### ISSUE THREAD

**Issue by CyannGuiguet** [pop-os/pop#1875] opened 2021-08-19 14:02 UTC
**Distribution
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
**Issue/Bug Description:**
When I lockdown my computer and then reopen my session the super switches by it-self from opening the pop os launcher to showing the workspaces (just as if I click on workspaces or uses Super + D).

**Steps to reproduce:**
Just lock the PC then unlock your session. And now the super key stopped working as expected.

**Expected behavior:**
The super key should for me open the pop os launcher. I had been to the settings and the super key is still configure to launcher but is showing workspaces
Changing the behaviour of the super key does nothing.

**Other Notes:**
I have recently installed the extension called notes.

**Comment by ids1024** [comment] 2021-08-19 15:05
Duplicate of https://github.com/pop-os/cosmic/issues/195. Should be fixed.

**Closed by ids1024** 2021-08-19 15:05 UTC
