### ISSUE TITLE
POP Theme issue with Gnucash

### ISSUE THREAD

**Issue by nodupe** [pop-os/pop#739] opened 2019-11-06 16:15 UTC
**Distribution (run `cat /etc/os-release`):**
 
 cat /etc/os-release
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

pop-theme:
  Installed: 1.0.4~1571245319~19.10~ed52981
  Candidate: 1.0.4~1571245319~19.10~ed52981
  Version table:
 *** 1.0.4~1571245319~19.10~ed52981 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
        100 /var/lib/dpkg/status

gnucash:
  Installed: 1:3.7-1ubuntu1
  Candidate: 1:3.7-1ubuntu1
  Version table:
 *** 1:3.7-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

When running on the default theme there are problems with cascading menus under Transfer. The background will not show, making it really hard to read what is show.

**Steps to reproduce (if you know):**

On any populated account on Gnucash, under the column transfer, if the dropdown menu is clicked, the list of possible transfer destinations are show, without a background, leaving the user without the ability to clearly see the options.

**Expected behavior:**

The list of possible destinations should show properly, with a solid background, enabling the user to properly choose the option.

**Other Notes:**

After installing another theme on gnome, the problem is solved. When going back to Pop theme, the issue reappears. Please check attacked images.

![Gnucash-Aawaita-default-Theme](https://user-images.githubusercontent.com/8133687/68316747-04f8d980-00cb-11ea-9b06-ab2e74688ecf.png)
![Gnucash-poptheme](https://user-images.githubusercontent.com/8133687/68316861-34a7e180-00cb-11ea-92a4-8d5a396d8ea9.png)

**Comment by awsninja** [comment] 2020-06-06 14:33
One additional observation: if you move focus off of Gnucash to another application window, the transfer menu then appears correctly. It only appears incorrectly when the focus is on the Gnucash window.

**Comment by indrekots** [comment] 2020-11-07 11:31
Seems to be related to https://github.com/pop-os/gtk-theme/issues/467

**Comment by jacobgkau** [comment] 2020-11-09 15:42
Yes, this is a duplicate of https://github.com/pop-os/gtk-theme/issues/467 and that issue has been fixed. The dropdowns in GnuCash currently show up correctly in our light and dark themes:

![pop-i739](https://user-images.githubusercontent.com/7199422/98562523-67009780-2267-11eb-9719-abb75bbe67e3.png)

**Closed by jacobgkau** 2020-11-09 15:42 UTC
