### ISSUE TITLE
Super/Win key not showing activities overview on second keyboard layout 

### ISSUE THREAD

**Issue by markbref** [pop-os/pop#993] opened 2020-05-06 13:50 UTC
**Distribution (run `cat /etc/os-release`):**

 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

After fresh install.
Super key is showing activities overview when using keyboard layout selected at install. When adding additional keyboard layout afterwards from Settings -> Region and Language, and using that, then Super key does not show activities overview. 

**Steps to reproduce (if you know):**
1. Fresh install and select danish keyboard layout in installer.
2. After install, add additional keyboard layout, eg. english, or any other. 

**Expected behavior:**
The Super key should be showing activities overview on additional keyboard layout also. 

**Other Notes:**
- Have tried "Alt and meta are on Alt" from Gnome Tweaks, but still not working.
- For folks like me, using my native keyboard layout to communicate, but another keyboard layout to work, it's a bit frustrating.

**Comment by leviport** [comment] 2020-05-06 17:58
Duplicate of https://github.com/pop-os/beta/issues/98

**Closed by leviport** 2020-05-06 17:58 UTC
