### ISSUE TITLE
Pop!_os added an unknown display that cannot be deleted

### ISSUE THREAD

**Issue by RikardtheCard** [pop-os/pop#3257] opened 2024-03-30 18:31 UTC
**Pop!_os 22.04** I am a Linux novice and this is my first time using Github so let me know how I could have improved this post.
 
 
 
**Unknown Display**

**I now have an Unknown Display showing up and cursor is not constrained within screen border**

**suddenly showed up after OS update on March 29th 2024**

**tried getting rid of the unknown display but couldn't; ended up totally messing up system; reinstalled Pop!_os 22.04 and after update unknown display showed up and cursor is restrained within display top, bottom and left side but, on the right it is confined within display on the bottom but cursor will move off the display area at the top right**

I am sure the problem is caused by the Unknown Display showing up under display settings. The display settings indicate I am using a single display but cursor behavior suggests otherwise.

I tried     xrandr --query     and here is the output  (it looks like None-1-1 was added but, not by me)

Screen 0: minimum 8 x 8, current 2560 x 1080, maximum 32767 x 32767
DVI-D-0 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 598mm x 336mm
   1920x1080     60.00*+  59.94    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
None-1-1 connected (normal left inverted right x axis y axis)
   640x480       60.00 +

**Comment by leviport** [comment] 2024-04-01 14:07
I wonder if this is related to some of the [other display issues](https://github.com/pop-os/linux/issues/304) we saw with the 6.8.0 update. If you boot the previous kernel, does it act normally again? Also, can you describe your hardware?

**Comment by RikardtheCard** [comment] 2024-04-01 22:05
I'm pretty sure I do not have an old enough kernel to change things as I reinstalled my OS (I totally screwed it up trying all the fixes I could look up). Here's what I have. I've never reverted to an old kernel before and after screwing with my system all weekend I'm kind of soured on doing anything else for awhile. I've had other problems crop up and after a few months and some updates they are usually fixed so I'm hoping this will be the case here too.

rick@pop-os:~$ find /boot/vmli*
/boot/vmlinuz
/boot/vmlinuz-6.2.6-76060206-generic
/boot/vmlinuz-6.8.0-76060800daily20240311-generic
/boot/vmlinuz.old

Here's my system info (short)

rick@pop-os:~$ sudo lshw -short
[sudo] password for rick: 
H/W path               Device          Class          Description
=================================================================
                                       system         Precision Tower 3620 (06B7
/0                                     bus            0MWYPT
/0/0                                   memory         64KiB BIOS
/0/9                                   memory         32GiB System Memory
/0/9/0                                 memory         8GiB DIMM DDR4 Synchronous
/0/9/1                                 memory         8GiB DIMM DDR4 Synchronous
/0/9/2                                 memory         8GiB DIMM DDR4 Synchronous
/0/9/3                                 memory         8GiB DIMM DDR4 Synchronous
/0/f                                   memory         256KiB L1 cache
/0/10                                  memory         1MiB L2 cache
/0/11                                  memory         6MiB L3 cache
/0/12                                  processor      Intel(R) Core(TM) i5-7500 
/0/100                                 bridge         Xeon E3-1200 v6/7th Gen Co
/0/100/1                               bridge         6th-10th Gen Core Processo
/0/100/1/0                             display        TU117 [GeForce GTX 1650]
/0/100/1/0.1           card1           multimedia     NVIDIA Corporation
/0/100/1/0.1/0         input13         input          HDA NVidia HDMI/DP,pcm=3
/0/100/1/0.1/1         input14         input          HDA NVidia HDMI/DP,pcm=7
/0/100/1/0.1/2         input15         input          HDA NVidia HDMI/DP,pcm=8
/0/100/1/0.1/3         input16         input          HDA NVidia HDMI/DP,pcm=9
/0/100/14                              bus            100 Series/C230 Series Chi
/0/100/14/0            usb1            bus            xHCI Host Controller
/0/100/14/0/2          input11         input          Generic X-Box pad
/0/100/14/0/4          input6          input          Evision RGB Keyboard Mouse
/0/100/14/0/5          input10         input          PixArt Dell MS116 USB Opti
/0/100/14/1            usb2            bus            xHCI Host Controller
/0/100/14/1/6          scsi4           storage        My Book 25ED
/0/100/14/1/6/0.0.0    /dev/sda        disk           6001GB My Book 25ED
/0/100/14/1/6/0.0.0/1  /dev/sda1       volume         5589GiB Windows NTFS volum
/0/100/14/1/6/0.0.1                    generic        SES Device
/0/100/14.2                            generic        100 Series/C230 Series Chi
/0/100/16                              communication  100 Series/C230 Series Chi
/0/100/17              scsi1           storage        Q170/Q150/B150/H170/H110/Z
/0/100/17/0.0.0        /dev/cdrom      disk           DVD-RAM GH22NS30
/0/100/1b                              bridge         100 Series/C230 Series Chi
/0/100/1b/0            /dev/nvme1      storage        PC401 NVMe SK hynix 256GB
/0/100/1b/0/0          hwmon1          disk           NVMe disk
/0/100/1b/0/2          /dev/ng1n1      disk           NVMe disk
/0/100/1b/0/1          /dev/nvme1n1    disk           256GB NVMe disk
/0/100/1b/0/1/1        /dev/nvme1n1p1  volume         234GiB EXT4 volume
/0/100/1b/0/1/2        /dev/nvme1n1p2  volume         4095MiB Linux swap volume
/0/100/1c                              bridge         100 Series/C230 Series Chi
/0/100/1c/0                            bridge         XIO2001 PCI Express-to-PCI
/0/100/1c.4                            bridge         100 Series/C230 Series Chi
/0/100/1c.4/0          /dev/nvme0      storage        Samsung SSD 980 PRO with H
/0/100/1c.4/0/0        hwmon2          disk           NVMe disk
/0/100/1c.4/0/2        /dev/ng0n1      disk           NVMe disk
/0/100/1c.4/0/1        /dev/nvme0n1    disk           2TB NVMe disk
/0/100/1c.4/0/1/1      /dev/nvme0n1p1  volume         1863GiB EXT4 volume
/0/100/1f                              bridge         C236 Chipset LPC/eSPI Cont
/0/100/1f/0                            system         PnP device PNP0c02
/0/100/1f/1                            communication  PnP device PNP0501
/0/100/1f/2                            input          PnP device PNP0303
/0/100/1f/3                            input          PnP device PNP0f03
/0/100/1f/4                            system         PnP device PNP0c02
/0/100/1f/5                            system         PnP device PNP0c02
/0/100/1f/6                            system         PnP device PNP0b00
/0/100/1f/7                            generic        PnP device INT3f0d
/0/100/1f/8                            system         PnP device PNP0c02
/0/100/1f/9                            system         PnP device PNP0c02
/0/100/1f/a                            system         PnP device PNP0c02
/0/100/1f/b                            system         PnP device PNP0c02
/0/100/1f.2                            memory         Memory controller
/0/100/1f.3            card0           multimedia     100 Series/C230 Series Chi
/0/100/1f.3/0          input17         input          HDA Intel PCH Front Mic
/0/100/1f.3/1          input18         input          HDA Intel PCH Rear Mic
/0/100/1f.3/2          input19         input          HDA Intel PCH Line Out
/0/100/1f.3/3          input20         input          HDA Intel PCH Front Headph
/0/100/1f.4                            bus            100 Series/C230 Series Chi
/0/100/1f.6            enp0s31f6       network        Ethernet Connection (2) I2
/1                     /dev/fb0        display        simpledrmdrmfb
/2                     input0          input          Sleep Button
/3                     input1          input          Power Button
/4                     input12         input          Dell WMI hotkeys
/5                     input2          input          Power Button

**Comment by vanrohan** [comment] 2024-04-02 06:05
I'm experiencing the same issue here.  
`xrandr --query`
![image](https://github.com/pop-os/pop/assets/22074683/a1aa56e8-8067-445b-9c51-3425b3827022)
`find /boot/vmli*`
```
/boot/vmlinuz
/boot/vmlinuz-6.6.10-76060610-generic
/boot/vmlinuz-6.8.0-76060800daily20240311-generic
/boot/vmlinuz.old
```

**Comment by RikardtheCard** [comment] 2024-04-02 17:29
Thanxs vanrohan, I'll give that a try. I wonder if I opened up grub as an admin whether GRUB_CMDLINE_LINUX=--output None-2-1 --off       would turn off the display forever? I don't know enough about linux to know if that would work.

**Comment by RikardtheCard** [comment] 2024-04-02 17:55
sudo xrandr thing didn't work for me. This is what I got back- (Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  41
  Current serial number in output stream:  43)

**Comment by knackstedt** [comment] 2024-04-02 19:19
I'm also experiencing this behavior. 
I can no longer layout my 3 monitors correctly through the settings menu -- have to use the nvidia one now.

Feel free to ping me if you need any debugging :)

**Comment by RikardtheCard** [comment] 2024-04-02 19:56
Ha on me! I didn't even think of looking at the nvidia settings. I can't figure out how to use it to delete or disable the unknown display. It's marked as prime display so I can't change it with nvidia settings.

**Comment by RikardtheCard** [comment] 2024-04-02 20:07
I can't figure out why this will not work for me.........xrandr --output None-1-1 --off
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  41
  Current serial number in output stream:  43

**Comment by knackstedt** [comment] 2024-04-02 20:08
I used the system settings to change the primary display, and the nvidia one to posisition them since the system dialog just wouldn't set their positions correctly

**Comment by RikardtheCard** [comment] 2024-04-02 20:17
Here's the idiotic thing here

![Screenshot from 2024-04-02 13-16-01](https://github.com/pop-os/pop/assets/165507153/aa9d94f6-551e-41a3-9478-3843ce64a61a)

**Comment by knackstedt** [comment] 2024-04-02 20:19
Oddly, my stuck display is 1024*768. I ended up covering it with my ultrawide display, since it was the only thing that wanted to work

![image](https://github.com/pop-os/pop/assets/29349167/18cdead9-4eea-40b3-8b1d-f37c5e45b6e9)

**Comment by RikardtheCard** [comment] 2024-04-02 20:26
Well, it's been entertaining at least. My cursor goes past the edge of my screen at the top where the other screen is supposed to be so at least it's better than before I reinstalled my OS. Prior to that I had 2 27" monitors side by side and had to scroll a whole screen over to reach the other side! With your 1024x768 screen off to the side does your cursor move over to it or does the cursor follow the edge of your Acer?

**Comment by RikardtheCard** [comment] 2024-04-03 21:51
the only other one I have is 6.2.6-76060206-generic. can I run  (sudo update-initramfs -u -k 6.2.6-76060206-generic)? I've never done this before so I'm not sure.

**Comment by Nuxmin** [comment] 2024-04-05 10:36
> @RikardtheCard I managed to temporarily fix the issue (until the next boot) by just running `sudo xrandr --output None-2-1 --off` where "None-2-1" is the name of the ghost display.

I used this command without sudo being my ghost screen None-1-1. It worked, the ghost display is still present but it doesn't seem to mess anymore with my system. It still works after a reboot.

Thank you for the temporal fix!

**Comment by rottedmood** [comment] 2024-04-10 17:41
> I wonder if this is related to some of the [other display issues](https://github.com/pop-os/linux/issues/304) we saw with the 6.8.0 update. If you boot the previous kernel, does it act normally again? Also, can you describe your hardware?

I started experiencing this with the 6.8.x kernel update. I do think it is related. I attempted to go back to 6.6.10 to test when I first experienced this, but for whatever reason, it wouldn't load. I never got a login screen, just a cursor. I had to get into recovery, chroot and get my kernel reset to the 6.8.x kernel to get the boot to work and be able to log back in.

**Comment by Nuxmin** [comment] 2024-04-11 13:13
Hey!

I decided to do some tweaks, and tried reading the the ArchWiki. It seems like I don't get the ghost screen anymore. However I've noticed some small glitches on the decrypt screen and on login. Although, the system seems to run normally and the ghost screen is gone.

Here are the steps I did.

Open a console and add the following kernel parameter by using:

`sudo kernelstub -a "nvidia_drm.fbdev=1"`

Then reboot. 

You may experience some visual glitches when decrypting and login, but the systems seems to load normally.

Although this is not a fix but more a temporal solution. Maybe Pop devs know better how this works.

Here's the end result on the display settings:

![Screenshot from 2024-04-11 15-09-50](https://github.com/pop-os/pop/assets/55192382/e23e88a7-6d9d-4882-b877-29c54335283a)

**This is using a Nvidia card, I didn't try these in another system. Make sure you make only this change only if you know what you're doing.**

**Try to have a backup in case something goes wrong before applying.**

----

Sources visited to come with this temporal solution:

- https://wiki.archlinux.org/title/NVIDIA

- https://support.system76.com/articles/kernelstub/

**Comment by jcsstelar** [comment] 2024-04-11 15:40
Oh boy, sad didnt find this place before! Wellcome to linux world I guess... I wasted all the weekend trying to figure out how to fix this issue.

Currently pressing spacebar on boot to load old kernel: 
6.2.6-76060206-generic

This kernel was causing me to not be able to mirror my screen (cos of that phantom-unknown screen):
6.8.0.76060800daily20240311.202403110203~1711393930~22.04~331756a amd64

Seems it only happens when I boot with the monitor on attached to the nvidia gpu, if I turn off that monitor and boot with the monitor on that is attached to the amd gpu the unknown screen is gone.

**Comment by zhengliw** [comment] 2024-04-13 11:57
Hey guys, wanted to let you know that `sudo kernelstub -a "nvidia_drm.fbdev=1` fixed it for me, at least for this reboot... How did it turn out for you? And anybody got an idea why this problem is caused?
Also, unrelated note but on Kubuntu 23.10 with 535 drivers, this problem doesn't seem to appear...

**Comment by knackstedt** [comment] 2024-04-13 12:49
This seems really likely to be an upstream kernel/nvidia driver issue. I'm not sure when it happened, but at some point a "PRIME" display started showing up for me. It definitely wasn't there a year ago. 
I'm down to open an issue at the upstream kernel wherever it is, but I frankly have no idea where I would need to create it.

**Comment by Nuxmin** [comment] 2024-04-13 13:17
> Hey guys, wanted to let you know that `sudo kernelstub -a "nvidia_drm.fbdev=1` fixed it for me, at least for this reboot... How did it turn out for you? And anybody got an idea why this problem is caused? Also, unrelated note but on Kubuntu 23.10 with 535 drivers, this problem doesn't seem to appear...

I'm glad my temporal solution worked. Did you also have glitches on the decrypt and login screen?

Relating to your question, I guess it's related somehow to the nvidia drm and the kernel change.

Probably Pop devs have a better explanation.

**Comment by zhengliw** [comment] 2024-04-14 16:33
@Nuxmin hey there, didn't set up encryption so can't say for sure, but login screen seems normal to be
by now, i am back on kubuntu with x11

**Comment by Nuxmin** [comment] 2024-04-15 10:36
I'm not sure... But I believe they've done something in recent updates. The display still appears but no longer seems to be interfering with my system.

**Comment by curiousercreative** [comment] 2024-04-16 15:42
FWIW, here's [my report in the chat](https://chat.pop-os.org/pop-os/pl/7hgjqjx55inkugqgnnp6k3y49r) with some details.

**Comment by KeithDobbelaere** [comment] 2024-04-17 01:02
##Permanently get rid of 'Unknown Display' from Settings application and eliminate mouse cursor from exiting screen:

#1. Find the name of the offending display

Open a terminal and type:
` ~$ xrandr -p `

In my case, the display was listed as "None-2-1".

#2. Create an Xorg Configuration File

If all else fails and the issue persists, you can create a specific Xorg configuration file to explicitly ignore the phantom display. You would do this by creating a file under /etc/X11/xorg.conf.d/ (for example, 20-ignore.conf) with the following content:

```
Section "Monitor"
    Identifier "None-2-1"
    Option "Ignore" "true"
EndSection
```

This file tells Xorg to completely ignore the "None-2-1" display.

#3. Restart computer and the ghost display should be gone!

**Comment by KeithDobbelaere** [comment] 2024-04-17 01:17
# Permanently get rid of 'Unknown Display' from Settings application and eliminate mouse cursor from exiting screen:
## 1. Find the name of the offending display

Open a terminal and type:

` ~$ xrandr -p `

In my case, the display was listed as "None-2-1".

## 2. Create an Xorg Configuration File

Create a file `sudo nano /etc/X11/xorg.conf.d/20-ignore.conf` with the following content:

```
Section "Monitor"
    Identifier "None-2-1"
    Option "Ignore" "true"
EndSection
```
CTRL+S, then CTRL+X to save and exit. 

This file tells Xorg to completely ignore the "None-2-1" display at the next boot.

## 3. Restart computer and the ghost display should be gone!

**Comment by alexclaydon** [comment] 2024-04-17 07:22
Thank you, this was very helpful.  It worked for me, although only if I put the config file in `/usr/share/X11/xorg.conf.d/` instead of `/etc/X11/xorg.conf.d/`.

**Comment by yashaswi-nayak** [comment] 2024-04-17 14:07
I have an XP-Pen Artist 12 display tablet that I use along side my main Monitor. I was having issue recently with my Display Tablet, was unable to mirror the screens. The solution provided by @KeithDobbelaere works. Now my Unkown display (None-1-1) is gone, I am able to work with both my screens now. 😄 

![display_fix](https://github.com/pop-os/pop/assets/6796735/d7799c00-e787-4d01-963e-f5bbf7adb1b8)

**Comment by eXConf** [comment] 2024-04-17 17:23
Thank you, @KeithDobbelaere, that worked for me too. Also logging out and in was sufficient to apply changes.

**Comment by knackstedt** [comment] 2024-04-17 17:31
For me, `sudo kernelstub -a "nvidia_drm.fbdev=1` has been the only thing that appears to have worked.
I'd like to get some kind of confirmation that these issues are going to be addressed in the upstream somewhere, rather than requiring users to patch their systems via the CLI to fix this.

Anyone able to weight in?

**Comment by RikardtheCard** [comment] 2024-04-17 22:19
I tried the xorg.conf trick but it didn't work for me. I put it in etc and in usr x11...neither worked. Drats!

**Comment by KeithDobbelaere** [comment] 2024-04-18 02:07
@RikardtheCard, was the problem display listed when you queried X Resize and Rotate(xrandr)? It might not be "None-2-1" in your case.

**Comment by RikardtheCard** [comment] 2024-04-18 06:25
@KeithDobbelaere  I changed it... mine was "None1-1"

**Comment by knackstedt** [comment] 2024-04-18 11:33
> I tried the xorg.conf trick but it didn't work for me. I put it in etc and in usr x11...neither worked. Drats! (knackstedt, what does sudo kernelstub -a "nvidia_drm.fbdev=1 do?) Well, at least I'm learning stuff. I just learned how to create a conf file, so, that's something.

You can click the 3 horizontal buttons on the comment and "Quote Reply". It won't specifically link the message though IIRC

That setting enables DRM on the kernel, which seems to be a regression in the latest version of the kernel (Frustrating that nobody caught this)

It was originally documented from the Arch linux wiki from what I can tell, but it's relevant for debian as far as the kernel setting goes
https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting

**Comment by rottedmood** [comment] 2024-04-18 16:44
> ```
> Section "Monitor"
>     Identifier "None-2-1"
>     Option "Ignore" "true"
> EndSection
> ```

This resolved it for me, where trying to run `sudo xrandr --output <ghost_display> --off` didn't.

**Comment by RikardtheCard** [comment] 2024-04-18 18:39
> > I tried the xorg.conf trick but it didn't work for me. I put it in etc and in usr x11...neither worked. Drats! (knackstedt, what does sudo kernelstub -a "nvidia_drm.fbdev=1 do?) Well, at least I'm learning stuff. I just learned how to create a conf file, so, that's something.
> 
> You can click the 3 horizontal buttons on the comment and "Quote Reply". It won't specifically link the message though IIRC
> 
> That setting enables DRM on the kernel, which seems to be a regression in the latest version of the kernel (Frustrating that nobody caught this)
> 
> It was originally documented from the Arch linux wiki from what I can tell, but it's relevant for debian as far as the kernel setting goes https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting

I tried "sudo kernelstub -a "nvidia_drm.fbdev=1" it said kernelstub was not found

**Comment by Nuxmin** [comment] 2024-04-19 01:48
Well... I tried my best to help because at the end the first solution I got from a kind person didn't work for me. As I find most people didn't even read my long post trying to help. Not only that, it also led to people saying people who just reposted what I did try to help came with that temporal fix.

A bit appreciation would be welcome. Or at least made me know it didn't work instead of ignoring the post completely.

**Comment by RikardtheCard** [comment] 2024-04-19 05:06
Well, thanx everyone for all your input. I've at least leaned some linux stuff and had my first experience on github.

**Comment by RikardtheCard** [comment] 2024-04-19 05:19
Well I appreciate everyone on github. It's nice to know I wasn't the only one having the problem. I read everything everyone wrote and tried the stuff I could sort of understand. I'm sorry if you feel slighted by me in any way. In the beginning I thanked people because there wasn't many writing on the issue. I didn't try the kernelstub thing a try for awhile because I was a bit scared about what could happen to my system. By the time I got around to it (it didn't work) there were many more entries and I had pretty much given up fixing the problem. In the future I will try to acknowledge all the help I get. Thank-you for your help Nuxmin.

[Rick_Face_small.png]

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by RikardtheCard** [comment] 2024-04-20 18:36
I am finding this comment system confusing. I reply to an email and find it posted here (and there it is...my email...for all to see). There is no reply button; instead after inquiring another member lets me know I have to use the "Quote Reply". As this display issue has not been addressed am I now supposed to close the issue? or just leave it open? Thanx everyone for participating.

**Comment by MelihDarcanxyz** [comment] 2024-04-23 12:37
Having the exact problem all of a sudden. Here's my `xrandr` output:

```
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00*+  59.94    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1440x576      50.00  
   1440x480      59.94  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)
None-2-1 connected (normal left inverted right x axis y axis)
   1920x1080     60.00 +
HDMI-A-1-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-1-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-1-1 disconnected (normal left inverted right x axis y axis)
DisplayPort-1-2 disconnected (normal left inverted right x axis y axis)

```
![image](https://github.com/pop-os/pop/assets/57872471/6c63daea-d4ad-4349-9068-93c5083ae855)

![image](https://github.com/pop-os/pop/assets/57872471/f6be1e23-66d0-416f-92cd-5a0de5efe600)

**Comment by zhengliw** [comment] 2024-04-23 19:34
@RikardtheCard don't worry, github is still kind of a dev platform, and yes please leave this issue open for further discussion :)

**Comment by RikardtheCard** [comment] 2024-04-24 04:56
> @RikardtheCard don't worry, github is still kind of a dev platform, and yes please leave this issue open for further discussion :)

Thanks. It was interesting for me and I learned a few things along the way.

**Comment by MrLekkim** [comment] 2024-04-24 19:19
> In my case, the display was listed as "None-2-1".
> 
> ## 2. Create an Xorg Configuration File
> Create a file `sudo nano /etc/X11/xorg.conf.d/20-ignore.conf` with the following content:
> 
> ```
> Section "Monitor"
>     Identifier "None-2-1"
>     Option "Ignore" "true"
> EndSection
> ```
> 
> CTRL+S, then CTRL+X to save and exit.
> 
> This file tells Xorg to completely ignore the "None-2-1" display at the next login.

Thanks for the help! This solved my issue completely. In my case, the display was listed as "None-1-1".

**Comment by RikardtheCard** [comment] 2024-04-25 05:43
> > In my case, the display was listed as "None-2-1".
> > ## 2. Create an Xorg Configuration File
> > Create a file `sudo nano /etc/X11/xorg.conf.d/20-ignore.conf` with the following content:
> > ```
> > Section "Monitor"
> >     Identifier "None-2-1"
> >     Option "Ignore" "true"
> > EndSection
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > CTRL+S, then CTRL+X to save and exit.
> > This file tells Xorg to completely ignore the "None-2-1" display at the next login.
> 
> Thanks for the help! This solved my issue completely. In my case, the display was listed as "None-1-1".

Well, you know, MrLekkim, I've tried this twice before and for some reason I decided to try again after reading your post. Wonders never cease to surprise! It actually worked this time for me. I have no idea why it didn't work before; the only thing I did different this time was I did it from the command line instead of going in the folder and creating it (it didn't exist when I looked). So, a thank-you to all who listed that as the fix.

**Comment by zhengliw** [comment] 2024-05-05 11:33
Hey guys,

I have a small update: After hopping back to Pop, I randomly noticed today that the fbdev fix made my boot much longer, which now takes about a minute. After putting in the decryption passphrase, the monitor would change mode (goes black for half a sec), and when it reactivates, the screen is still the output of cryptsetup, and only after half a minute, the screen would go to GDM, and after logging in, the screen would again show cryptsetup output for 10 seconds, and then to GNOME. Everything else seems fine...
After removing fbdev from kernel params, the monitor changes mode once, and then GDM appears, and logging in is snappy and quick. But now the ghost display is back :(

What do we do now? Thanks!

**Comment by tomlyo** [comment] 2024-05-17 20:33
I found creating the Xorg configuration file removed my "Unknown Display" on Pop!_os, and that was great until I realized it had other side effects, my streaming application "Sunshine" now just gives me a black screen, and I get other monitor errors when trying to specify the single monitor I have. Removing this configuration file restores functionality, but the "Unknown Display" returns.

**Comment by jarekdudzinski** [comment] 2024-06-01 12:03
If this is still a problem for anyone - this worked for me:
`sudo su
cd /boot/efi/loader/entries/
nano Pop_OS-current.conf`
and on the end of options need to add `initcall_blacklist=simpledrm_platform_driver_init`.
Restart.

**Comment by zhengliw** [comment] 2024-06-01 12:09
I'm on Fedora now, there isn't this ghost monitor bug but has anyone tried adding the nvidia modules to the initramfs? It fixed the broken decryption screen for me on Fedora a while ago, and combined with nvidia_drm.modeset=1 this might be a good workaround

**Comment by illtellyoulater** [comment] 2024-06-02 16:22
are you guys sure than creating `/etc/X11/xorg.conf.d/20-ignore.conf` and adding to it
```
Section "Monitor"
    Identifier "None-2-1"
    Option "Ignore" "true"
EndSection
```
will not cause any issue when actually connecting an additional display?

**Comment by rofrol** [comment] 2024-06-06 21:32
Disabling with xorg.conf.d worked for me. But also disabling with kernel parameter worked for me on Ubunt 24.04:

```
echo 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT initcall_blacklist=simpledrm_platform_driver_init"' | sudo tee /etc/default/grub.d/99_disable_simpledrm.cfg
sudo update-grub
```

To undo the change:

```
sudo rm /etc/default/grub.d/99_disable_simpledrm.cfg
sudo update-grub
```

https://askubuntu.com/questions/1509661/could-not-switch-the-monitor-configuration-on-none-1-1-connected-output/1514074#1514074

**Comment by MrPancakes39** [comment] 2024-06-20 05:41
I have updated my kernel to `6.9.3-76060903-generic` which seems to have fixed this issue

**Comment by Nuxmin** [comment] 2024-06-20 10:47
> I have updated my kernel to `6.9.3-76060903-generic` which seems to have fixed this issue

Same here : )

**Closed** 2024-06-20 13:12 UTC

**Comment by hwertz** [comment] 2024-09-05 20:43
(I just finally rebooted my desktop going from a 6.5.x to 6.8.x kernel on my Ubuntu 22.04 system). Just an FYI, the nvidia-settings program indicates the second screen is for Nvidia Prime.   (I wondered why my remote desktop had become extra-wide 8-) .)  I'm using a Nvidia GTX1650, and the monitor is hooked up to there (nothing hooked up to the onboard video.)  But the BIOS doesn't disable the on board Coffee Lake GPU.  So presumably with the 6.8 kernel something in the driver stack decides I want to run hybrid graphics.
