### ISSUE TITLE
Minimize button does not work on some apps.

### ISSUE THREAD

**Issue by pguragain3** [pop-os/pop#1501] opened 2021-01-21 14:51 UTC
**Distribution (run `cat /etc/os-release`):
  **NAME="Pop!_OS"
  VERSION="20.04 LTS"
  ID=pop
  ID_LIKE="ubuntu debian"
  PRETTY_NAME="Pop!_OS 20.04 LTS"
  VERSION_ID="20.04"
  HOME_URL="https://pop.system76.com"
  SUPPORT_URL="https://support.system76.com"
  BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
  PRIVACY_POLICY_URL="https://system76.com/privacy"
  VERSION_CODENAME=focal
  UBUNTU_CODENAME=focal
  LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** brave-browser

**Issue/Bug Description:** cannot minimize with minimize button. Right click > minimize works. 

**Steps to reproduce (if you know):** updated system with sudo apt update && sudo apt upgrade

**Expected behavior:** Not limited to single application. Other users are facing issues with other different apps than mine.

**Other Notes:** Did a little digging and other users were also having same issues with different apps.

**Comment by leviport** [comment] 2021-01-21 15:20
Duplicate of https://github.com/pop-os/shell/issues/842

**Closed by leviport** 2021-01-21 15:20 UTC
