### ISSUE TITLE
Extreme graphics lag when the laptop lid is closed

### ISSUE THREAD

**Issue by iHnR** [pop-os/pop#2190] opened 2022-01-25 15:58 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

not applicable

**Issue/Bug Description:**

I use a thinkpad p50 with NVIDIA GPU. I can connect a second monitor over HDMI and everything runs fine ... until I close the lid. The second monitor keeps running as it should but becomes unusably slow. 

**Steps to reproduce (if you know):**

* Use a laptop with NVIDIA graphics
* Enable hybrid graphics mode
* Connect second monitor
* Set external monitor as the main monitor
* Close laptop lid

**Expected behavior:**

The external monitor keeps running as usual

**Other Notes:**

I expect there might be some refresh action I could do after closing the lid that would resolve the issue. I don't know what that action should be though.

I know others online are experiencing the same and are able to fix it by using NVIDIA graphics only. I don't want to do this as some apps I use don't fare well with that either.

**Comment by jacobgkau** [comment] 2022-01-25 16:15
Duplicate of https://github.com/pop-os/nvidia-graphics-drivers/issues/61.

**Closed by jacobgkau** 2022-01-25 16:15 UTC

**Comment by Koalitions** [comment] 2023-06-23 15:31
Hello everyone, I am here to share my experience and my solutions following the replacement of my two screens with Samsung Odyssey G5 27" S27AG500PP.
I begin with, my configuration :
• Legion 5 Pro Laptop
• Lenovo Thinkpad USB C dock station

I encountered 2 problems with my screens connected via the dock station. These 2 problems have the same origin: the G-SYNC.
The first issue concerns performance issues when the laptop lid is closed. The screens lag and freeze, even going so far as to cause a PC crash.

I found a few solutions listed in order of relevance,
You have the choice :
1.	Open the laptop lid and turn off the screen.
2.	Change switchable graphics settings from "discrete graphics" to "dynamic graphics" in BIOS or enable hybrid mode in Lenovo Vantage if you have a compatible Lenovo.
3.	Disable Adaptive G-SYNC in the screen settings (on the screen itself).
4.	Go to monitor settings and set DisplayPort to version 1.1 (I think it works because it disables Adaptive G-SYNC).

The second problem concerns a black screen when starting certain games or software such as Lenovo Vantage.

I found a few Solution listed in order of relevance,
You have the choice :
1.	Use a direct USB-C > DisplayPort cable without going through a base.
2.	Disable Adaptive G-SYNC in the screen settings (on the screen itself).
3.	Go to monitor settings and set DisplayPort to version 1.1 (I think it works because it disables Adaptive G-SYNC).
Conclusion: If you encounter the 2 problems simultaneously, prefer to take a dedicated cable for the display of your screen without going through a base. For lack of means, deactivate the Adaptive G-SYNC. If you only have the first problem, open your laptop lid or switch the graphics to dynamic mode.
