### ISSUE TITLE
Not able to run sudo, or perform any root level actions. Pop Shop requesting an Administrator password. 

### ISSUE THREAD

**Issue by Lekua** [pop-os/pop#1805] opened 2021-07-08 20:38 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
None. Base POP OS

**Issue/Bug Description:**
I can no longer run any form of sudo, or install / uninstall any kind of software. When I try to install software, I get asked for an administrator password, that I never set my user password doesn't work and other common passwords don't either. (root, password, username). When I run the `groups` command in terminal, it shows me being in my user group along with dialout. Dialout being there because its required to upload any Arduino code to a board. Sudo works the same as it normally would, running a command with the prefix of sudo, `sudo ls /usr/share/icons` for example. It asks for the user password, but when provided it returns the error. 
`$USER is not in the sudoers file.  This incident will be reported.`
I only have one user on the account, and haven't even tried to set up any others. After googling this error like we all do, I end up landing on a page telling me that I need to run the following commands (pasted below along with the aged forum post). The issue with this is I can't use any sudo command, I'm locked to a base user account without being able to createor having access to  an Administrator account. 
`Step 1. Open a terminal window, CTRL+ALT+T on my system (Debian KDE after setting up as hotkey)

Step 2. Entered root using command su root

Step 3. Input root password

Step 4. Input command apt-get install sudo -y to install sudo

Step 5. Add user to sudoers file by inputting adduser username sudo, put your username in place of username

Step 6. Set the correct permissions for sudoers file by inputting chmod  0440  /etc/sudoers

Step 7. Type exit and hit Enter until you close your terminal window. Shutdown your system completely and reboot.

Step 8. Open another terminal window.

Step 9. Try any sudo command to check if your username is correctly added to sudoers file. I used sudo echo "Hello World!". If your username has been correctly added to the sudoers list then you will get Hello World! as the terminal response!`
[Forum Post](https://unix.stackexchange.com/questions/179954/username-is-not-in-the-sudoers-file-this-incident-will-be-reported)

**Steps to reproduce (if you know):**

**Expected behavior:**
Entering my password will allow me to use sudo, and allow me to perform root level actions. As well as not prompting for an Administrator password. 

**Other Notes:**
I had reinstalled Pop OS last night, trying the LTS version for a theme I was using. That night the last sudo action I used was adding myself to a Dialout group, as told on the Arduino web page for installing on Linux. [Arduino Tutorial Page](https://www.arduino.cc/en/Guide/Linux)

**Comment by jacobgkau** [comment] 2021-07-08 20:52
This is not a support forum, but I would recommend using the [Recovery partition](https://support.system76.com/articles/pop-recovery) (or, if you don't have one, a live disk, but still following that article's instructions) to chroot into your installation. That will allow you to add your regular user to the `sudo` group (you should also add it to the `adm` group, that's the one Pop!_OS and GUI utilities generally check for.)

As far as this bug report is concerned, looking at the command in the article (`sudo usermod -a -G dialout <username>`), the only thing I can see is that if you omit the `-a` option (which stands for `append`), then you would be left with only the new group and the primary group. Can you look back through the `.bash_history` file in your home directory and see if that could be what happened?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by Lekua** [comment] 2021-07-08 20:59
> This is not a support forum, but I would recommend using the [Recovery partition](https://support.system76.com/articles/pop-recovery) (or, if you don't have one, a live disk, but still following that article's instructions) to chroot into your installation. That will allow you to add your regular user to the `sudo` group (you should also add it to the `adm` group, that's the one Pop!_OS and GUI utilities generally check for.)
> 
> As far as this bug report is concerned, looking at the command in the article (`sudo usermod -a -G dialout <username>`), the only thing I can see is that if you omit the `-a` option (which stands for `append`), then you would be left with only the new group and the primary group. Can you look back through the `.bash_history` file in your home directory and see if that could be what happened?
> 
> System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

Was reading through some articles and I did find that the best way to do this is through recovery, and looking back through my bash history, I did omit the -a. By mistake, next time I'll make sure to read documentation and understand the flags before omitting them from a command provided by a tutorial. Sorry about asking for support here, didn't know but thanks for the fast response. Ill reply in the next 5-20 minutes responding if going through recovery does fix the issue.

**Comment by jacobgkau** [comment] 2021-07-08 21:01
No worries, I'm going to close this since it's not a bug in Pop!_OS, but good luck. If you have trouble getting into the chroot, the Mattermost chat room that I linked in my previous message is a great place to go for community support, or if you own System76 hardware, then our support team can answer questions like this.

**Closed by jacobgkau** 2021-07-08 21:01 UTC

**Comment by Lekua** [comment] 2021-07-08 21:10
> Was reading through some articles and I did find that the best way to do this is through recovery, and looking back through my bash history, I did omit the -a. By mistake, next time I'll make sure to read documentation and understand the flags before omitting them from a command provided by a tutorial. Sorry about asking for support here, didn't know but thanks for the fast response. Ill reply in the next 5-20 minutes responding if going through recovery does fix the issue.

Went through recovery mode, and was able to add my user back to root and adm. I'm still faced with the issue of `$USER is not in the sudoers file.  This incident will be reported.` But I should have resources to fix this issue. If I have any more trouble I'll make sure to open a thread on reddit.

Thanks!

**Comment by jacobgkau** [comment] 2021-07-08 21:11
> Went through recovery mode, and was able to add my user back to root and adm.

Do you mean `sudo` and `adm`? `root` is the root user's primary group. `sudo` is what the `sudoers` file checks by default.
