### ISSUE TITLE
LTS and Kernel version

### ISSUE THREAD

**Issue by seanamosw** [pop-os/pop#1937] opened 2021-10-04 13:45 UTC
The LTS version of Pop upgrades the kernel to higher versions than LTS Ubuntu.

eg. As of now, the current kernel in LTS Pop = 5.13.0-7614, LTS Ubuntu = 5.11.x

There are a couple issues with this, but I will highlight the one that affects me right now.

AMDGPU Pro drivers, specifically for OpenCL support, almost always stick to the LTS Ubuntu kernel version.
If you try install AMDGPU Pro drivers today in LTS Pop, you will get this error:

```
./amdgpu-pro-install --opencl=legacy,rocr --headless

...
Setting up amdgpu-dkms (1:5.11.19.98-1290604) ...
Loading new amdgpu-5.11.19.98-1290604 DKMS files...
Building for 5.13.0-7614-generic
Building for architecture amd64
Building initial module for 5.13.0-7614-generic
ERROR (dkms apport): kernel package linux-headers-5.13.0-7614-generic is not supported
Error! Bad return status for module build on kernel: 5.13.0-7614-generic (amd64)
Consult /var/lib/dkms/amdgpu/5.11.19.98-1290604/build/make.log for more information.
dpkg: error processing package amdgpu-dkms (--configure):
 installed amdgpu-dkms package post-installation script subprocess returned error exit status 10
...
```

The install works fine with last kernel version I had installed (5.11.0.35).

This is quite unexpected. One of the main reasons to stick to LTS is to avoid these kinds of issues.
As far as I know, the only workaround at the moment is to manually downgrade the kernel and be very careful when updates come through.

**Comment by jacobgkau** [comment] 2021-10-05 19:34
This is expected. The primary reason this is done is to ensure the current LTS version works on all currenlty-shipping System76 hardware. Ubuntu's LTS kernel is too old to work with some current hardware.

For the AMDGPU-PRO driver, see this issue: https://github.com/pop-os/pop/issues/1135 (There is nothing we can do beyond waiting for AMD to update their proprietary driver to support a newer Linux kernel version.)

> One of the main reasons to stick to LTS is to avoid these kinds of issues.

This is a common misunderstanding. In the context of Pop!_OS, the LTS is not inherently "more stable" or "less issue-prone." Both the latest and LTS releases undergo the same rigorous QA processes for Pop!_OS-specific packages, and both are similarly affected by outside updates to Ubuntu-provided packages.

I'm closing this as a duplicate of https://github.com/pop-os/pop/issues/1135 since the issue here is AMDGPU-PRO not working.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Closed by jacobgkau** 2021-10-05 19:34 UTC
