### ISSUE TITLE
POP SHOP asks for sudo password every minute, HORRIBLE! Also search bar bug

### ISSUE THREAD

**Issue by BarbzYHOOL** [pop-os/pop#3091] opened 2023-07-28 21:44 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

POP SHOP
1) When you do an action, it requires SUDO, but it doesn't stay in memory more than 1 minute, it's awful... My password is super long fyi (which is good practice). It makes me want to uninstall it and only use the terminal instead since SUDO is saved in memory for a while (and in top of that, it can be configured to be longer).
The other day, I installed one app, then another and had to enter twice my password, then uninstalled one and had to enter my password
seriously, this is extremely annoying and could be made more practical

2) when you search for something in the search bar, once you have found it or installed an app, you cannot use the search bar again unless you go back to the Home page of the POP shop, again it is very tedious and counter intuitive

**Expected behavior:**

No need for sudo more than once every 10 minutes, maybe configurable
Search bar working from any window

**Other Notes:**

these issues are not new

**Comment by leviport** [comment] 2023-07-28 21:54
Duplicate of https://github.com/pop-os/shop/issues/354

**Closed by leviport** 2023-07-28 21:54 UTC

**Comment by BarbzYHOOL** [comment] 2023-07-29 01:33
roflmao

https://github.com/pop-os/shop/issues/13 closed as completed in 2017, like my issue

**Comment by BarbzYHOOL** [comment] 2023-08-09 21:42
can someone reopen this since it has never been fixed?
