### ISSUE TITLE
The Pop Shell extension is crappy

### ISSUE THREAD

**Issue by Yuri6037** [pop-os/pop#1513] opened 2021-01-27 12:57 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop Shell built-in extension

**Issue/Bug Description:**
When this extension is enabled a lot of things are disfunctional and buggy as hell:
- Absolutely ALL applications no longer opens with focus, forcing the user to install NoAnnoyance extension
- The activities menu focus switch is all broken: when you click an application you have 50% chances it works and 50% chances it f**** ** and decides to focus a random app that is not the clicked one.
- We have random mouse cursor teleportation to secondary screen on NVIDIA setups

**Steps to reproduce (if you know):**
- Have this extension enabled

**Expected behavior:**
No bugs should be observable. Especially no annoying "Whatever is ready" kind of notification and no focus steal!

**Other Notes:**
This bug did not occur before an update that I applied yesterday.

**Workarround:**
To restore the correct behavior of GNOME, simply disable that extension.

**Comment by leviport** [comment] 2021-01-27 15:11
Focus issues are a duplicate of https://github.com/pop-os/shell/issues/853
Cursor jumping is a duplicate of https://github.com/pop-os/shell/issues/848

We will continue our ceaseless efforts to remove bugs, but I'm sure you're aware that saying something shouldn't have bugs and actually debugging it are on two entirely different levels of difficulty. We do our best to fix bugs quickly, and PRs to address both of those issues have been merged already. Make sure to install updates when you get a chance.

**Closed by leviport** 2021-01-27 15:11 UTC

**Comment by Yuri6037** [comment] 2021-01-27 15:30
It's still not fixed. Despite apt upgrade, the problem is still not fixed and I still can't use Pop Shell extension.

**Comment by leviport** [comment] 2021-01-27 15:32
It takes some time for updates to move through the staging repos and be released. It should be there in the next day or two.
