### ISSUE TITLE
Installing operating system updates breaks graphics

### ISSUE THREAD

**Issue by ingmarsell** [pop-os/pop#3099] opened 2023-08-08 14:49 UTC
**Distribution:**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

Installing Operating System Updates from Pop!_Shop breaks graphics.

I have been running Pop OS on my laptop for around a year, while occasionally installing all updates from the Pop!_Shop. After doing it today and rebooting the system the laptop's built-in display stayed black after the MSI logo. Even Ctrl+Alt+F5 did not bring anything to the screen. After connecting an external display the login screen appeared on that display. I could log in and see the desktop, but the resolution and scaling were really weird. I could also notice a lot of visual UI bugs like elements appearing only after moving the mouse over them etc. I checked the display setting and the built-in display for the laptop was turned off and had a ridiculously large resolution (something like 15000x8000). After changing the resolution back to normal I was able to make the built-in screen work, but only while an external monitor was plugged in. By Cycling different settings and Super+P I was able to make some of the screens work, but never all of them. In all of the configurations, the weird scaling, resolution, and UI bugs persisted. I also wasn't ever able to make the laptop screen work while no external monitors are plugged in. I also tried changing between all of the Nvidia drivers available on Pop!_Shop without any luck. After that, I proceeded to reinstall Pop_OS! From Scratch. With a clean install, everything was working correctly like before, but after running all updates on that instance everything broke the same way again.

**Steps to reproduce:**

- Install Pop! OS on MSI MS-16Q4
- Click Update All in Pop!_Shop
- Reboot

**Expected behavior:**

Graphics stay working after updates

**Other Notes:**

System: MSI MS-16Q4, i7 8750H, RTX 2070 Mobile, 16GB RAM

**Comment by Ingmar05** [comment] 2023-08-16 11:30
I have discovered that reverting to the old kernel fixes the issues.
- Prior to the upgrade, 'uname -r' outputted: 6.2.6-76060206-generic, whereas after the upgrade it was 6.4.6-76060406-generic.
- The initial quick fix for me was repeatedly pressing F9 during boot and selecting 'POP_OS-oldkern.conf' from the screen.
- A more permanent solution involved running: 'kernelstub -v -k /boot/vmlinuz-6.2.6-76060206-generic -i /boot/initrd.img-6.2.6-76060206-generic'.

**Comment by loafylemon** [comment] 2023-08-22 03:41
Encountering a similar problem: no display output on a desktop with kernel version 6.4.6 when using DisplayPort with an AMD GPU (7900 XTX). The issue is resolved by reverting to the previous kernel, but I assume it won't be maintained forever. Any suggestions?

**Comment by loafylemon** [comment] 2023-08-22 17:22
I'm uncertain about what specific details I should be seeking, so here's the complete content of journalctl, spanning from the system's boot until the occurrence of a SIGTERM (forced shutdown).

[logs.txt](https://github.com/pop-os/pop/files/12411179/logs.txt)

**Comment by leviport** [comment] 2023-08-22 20:29
If you hold spacebar while booting, it should summon the systemd-boot menu. From here, if you hit the `e` key with the cursor on a boot entry, it will allow you to edit boot parameters. If you do this on the "current" kernel entry, remove `quiet` and `splash` and then hit `Enter` to boot, is there any additional info printed on the display? 

Also, if you just need to get back to a working state, booting the "oldkern" entry in the boot menu will boot the old kernel, which should work, I believe. If you want to set that as the default for all future boots, hit the `d` key with your cursor on that entry. To remove the override later, the `d` key will also remove the default preference.

**Comment by leviport** [comment] 2023-08-22 21:27
I was able to replicate this on our mira-r2 with a 7900XT installed. I was also able to fix it with a linux-firmware update: https://github.com/pop-os/linux-firmware/pull/39

If you'd also like to test this, you can add that staging branch with this command:
```
apt-manage add popdev:firmware
``` 
and then install updates and reboot. I believe that should allow you to boot 6.4.6 with that graphics card.

Once that PR is merged and the branch is deleted, that apt source will start to 404. You can either remove it with Repoman, or with this command:
```
apt-manage remove popdev-firmware
```
```

**Comment by leviport** [comment] 2023-08-22 23:19
The firmware update passed testing and was released, so you'll probably want to remove that staging source if you've added it, and normal updates will give you the linux-firmware update that will fix the 7900XT(X)

**Comment by loafylemon** [comment] 2023-08-22 23:36
Just fetched the updates and can verify that everything is functioning properly now. Cheers for the quick fix!

**Comment by leviport** [comment] 2023-08-22 23:38
Glad to hear it! I'll leave this open until the OP can let us know whether that fixed it for them. I'm not entirely sure that issue is the same as the 7900XT issue.

**Comment by grantbrown** [comment] 2023-08-23 02:06
I'm wondering if I have a related issue or if I should open a different one. 

I encountered something similar on a desktop with a 7900xtx - this morning after selecting PopOS from the motherboard boot menu it went black when it usually would have shown the LUKS password prompt. I can hit space to get to the old kernel or recovery, but old kernel and new both show a black screen and then the monitor goes to sleep. Recovery boots normally, as does a Windows install and a separate Fedora install. I can unlock and access the root partition from Fedora or LiveUSB without issue. 

I went through the instructions [here](https://support.system76.com/articles/bootloader/) to try to repair the bootloader, but that didn't change the issue (which makes me think something in the kernel is messed up?)

Can I update the kernel through the same chroot method used in the bootloader repair?

**Comment by jurodr** [comment] 2023-08-23 10:41
@grantbrown I had the same issue as you. I have the same GPU (7900xtx).

I managed to fix the problem after finding this thread. After chroot'ing via the recovery or a live usb, I could today run another "apt upgrade" that installed the latest "linux-firmware" package. After that the device is booting normally.

The linux-firmware package that fixed the issue is version "20230815.git0e048b06-0ubuntu1+system76~1692716226~22.04~7d1b0aa"

@leviport Thank you so much for the quick fix!

**Comment by Ingmar05** [comment] 2023-08-23 11:17
When running `apt full-upgrade` I got upgraded to kernel `6.4.6-76060406-generic` and linux-firmware `20230815.git0e048b06-0ubuntu1+system76~1692716226~22.04~7d1b0aa`. After rebooting, the laptop screen stays black and the issue persists :(

I had to revert back to kernel `6.3.13-060313-generic` again.

**Comment by acolombier** [comment] 2023-08-26 09:59
Hi, I'm also experiencing the same issue. After upgrading to `6.4.6-76060406-generic`, the laptop screen stays black. Currently installed `linux-firmware` is `20230815.git0e048b06-0ubuntu1+system76~1692716226~22.04~7d1b0aa`

I had to revert to `old-ker` (`6.2.6-76060206-generic`). This is my `neofetch` in case it may help, let me know if there is any log that could be relevant.

```
             /////////////                
         /////////////////////            -------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: N8xxEP6 
   /////76767//7676767//////////////      Kernel: 6.2.6-76060206-generic 
  /////767676///*76767///////////////     Uptime: 18 mins 
 ///////767676///76767.///7676*///////    Packages: 3874 (dpkg), 36 (flatpak), 3 (snap) 
/////////767676//76767///767676////////   Shell: bash 5.1.16 
//////////76767676767////76767/////////   Resolution: 2560x1440, 1920x1080, 2560x1440 
///////////76767676//////7676//////////   DE: GNOME 42.5 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: terminator 
   //////.7676767676767676767,//////      CPU: Intel i7-8750H (12) @ 2.200GHz 
    /////767676767676767676767/////       GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
      ///////////////////////////         GPU: NVIDIA GeForce GTX 1060 Mobile 
         /////////////////////            Memory: 6958MiB / 15699MiB 
             /////////////

```
Thanks team!

**Comment by lwasyl** [comment] 2023-12-29 00:32
Same here, after updating to `6.6.6-76060606-generic` I am stuck on a black screen with just a mouse cursor visible. What's worse, the suggestions from https://support.system76.com/articles/login-loop-pop/ apparently overwrote the old kernel, and the working 6.5.4 is not available in any of the repositories.

Is there any source where I can still download `vmlinuz-6.5.4-76060504-generic` to use with `kernelstub` or in any other way downgrade to the working `6.5.4-76060504-generic` kernel without losing current installation?

**Comment by ingmarsell** [comment] 2024-01-13 15:39
The issue is no longer present and I can upgrade without the graphics breaking

**Closed** 2024-01-13 15:39 UTC
