### ISSUE TITLE
Borked system after fake upgrade to 20.10

### ISSUE THREAD

**Issue by the-black-wolf** [pop-os/pop#1527] opened 2021-02-05 08:27 UTC
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
  
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
Package files:
 100 /var/lib/dpkg/status
     release a=now
 100 http://us.archive.ubuntu.com/ubuntu groovy-backports/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-backports,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 100 http://us.archive.ubuntu.com/ubuntu groovy-backports/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-backports,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/multiverse i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/multiverse amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/restricted i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/multiverse i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/multiverse amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/restricted i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/main i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/multiverse i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/multiverse amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/restricted i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/main i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://apt.pop-os.org/proprietary groovy/main all Packages
     release v=20.10,o=system76,a=groovy,n=groovy,l=System76,c=main,b=all
     origin apt.pop-os.org
 500 http://apt.pop-os.org/proprietary groovy/main amd64 Packages
     release v=20.10,o=system76,a=groovy,n=groovy,l=System76,c=main,b=amd64
     origin apt.pop-os.org
 500 http://apt.pop-os.org/proprietary focal/main all Packages
     release v=20.04,o=system76,a=focal,n=focal,l=System76,c=main,b=all
     origin apt.pop-os.org
 500 http://apt.pop-os.org/proprietary focal/main amd64 Packages
     release v=20.04,o=system76,a=focal,n=focal,l=System76,c=main,b=amd64
     origin apt.pop-os.org
1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
     release v=20.04,o=LP-PPA-system76-pop,a=focal,n=focal,l=Pop!_OS PPA,c=main,b=i386
     origin ppa.launchpad.net
1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
     release v=20.04,o=LP-PPA-system76-pop,a=focal,n=focal,l=Pop!_OS PPA,c=main,b=amd64
     origin ppa.launchpad.net
 100 http://us.archive.ubuntu.com/ubuntu focal-backports/universe i386 Packages
     release v=20.04,o=Ubuntu,a=focal-backports,n=focal,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 100 http://us.archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages
     release v=20.04,o=Ubuntu,a=focal-backports,n=focal,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-security/main i386 Packages
     release v=20.04,o=Ubuntu,a=focal-security,n=focal,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages
     release v=20.04,o=Ubuntu,a=focal-security,n=focal,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-security/universe i386 Packages
     release v=20.04,o=Ubuntu,a=focal-security,n=focal,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages
     release v=20.04,o=Ubuntu,a=focal-security,n=focal,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-security/multiverse i386 Packages
     release v=20.04,o=Ubuntu,a=focal-security,n=focal,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages
     release v=20.04,o=Ubuntu,a=focal-security,n=focal,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-security/restricted i386 Packages
     release v=20.04,o=Ubuntu,a=focal-security,n=focal,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-security/restricted amd64 Packages
     release v=20.04,o=Ubuntu,a=focal-security,n=focal,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages
     release v=20.04,o=Ubuntu,a=focal-updates,n=focal,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
     release v=20.04,o=Ubuntu,a=focal-updates,n=focal,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages
     release v=20.04,o=Ubuntu,a=focal-updates,n=focal,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages
     release v=20.04,o=Ubuntu,a=focal-updates,n=focal,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-updates/multiverse i386 Packages
     release v=20.04,o=Ubuntu,a=focal-updates,n=focal,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages
     release v=20.04,o=Ubuntu,a=focal-updates,n=focal,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-updates/restricted i386 Packages
     release v=20.04,o=Ubuntu,a=focal-updates,n=focal,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages
     release v=20.04,o=Ubuntu,a=focal-updates,n=focal,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal/main i386 Packages
     release v=20.04,o=Ubuntu,a=focal,n=focal,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
     release v=20.04,o=Ubuntu,a=focal,n=focal,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal/universe i386 Packages
     release v=20.04,o=Ubuntu,a=focal,n=focal,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
     release v=20.04,o=Ubuntu,a=focal,n=focal,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal/multiverse i386 Packages
     release v=20.04,o=Ubuntu,a=focal,n=focal,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages
     release v=20.04,o=Ubuntu,a=focal,n=focal,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal/restricted i386 Packages
     release v=20.04,o=Ubuntu,a=focal,n=focal,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu focal/restricted amd64 Packages
     release v=20.04,o=Ubuntu,a=focal,n=focal,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
```

**Issue/Bug Description:**
pop os upgrade request caught me sleepy at the wheel, I got offered 20.10, but instead got downgraded to 20.04. Not expecting an issue I agreed to "upgrade" request and now I don't even know if this will work if I reboot it. 

**Steps to reproduce (if you know):**
Ran a distro upgrade from GUI, when it failed, updated packages. distro upgrade fails again. Following steps from system76 web sites to repair failed 20.10 upgrades resulted in apt wanting to remove `pop-desktop` on `dist-upgrade`, so I stopped at this.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  fprintd gir1.2-handy-0.0 gstreamer1.0-pipewire libfprint-2-2 libpam-fprintd python3-repolib
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  gdm3 gir1.2-mutter-7 gnome-shell-extension-prefs gnome-startup-applications gnome-tweaks libmutter-7-0 pop-desktop
The following NEW packages will be installed:
  gir1.2-mutter-6 yaru-theme-gnome-shell
The following packages will be DOWNGRADED:
  gir1.2-gdm-1.0 gnome-settings-daemon gnome-settings-daemon-common gnome-shell gnome-shell-common libgdm1 mutter-common
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  pop-desktop gdm3 (due to pop-desktop)
0 upgraded, 2 newly installed, 7 downgraded, 7 to remove and 0 not upgraded.
Need to get 3,048 kB of archives.
After this operation, 8,303 kB disk space will be freed.
You are about to do something potentially harmful.
To continue type in the phrase 'Yes, do as I say!'
```

**Expected behavior:**
Not having a borked system?

**Other Notes:**

This is exactly the issues described in 
https://www.reddit.com/r/pop_os/comments/lccc5w/updating_to_2010_fails_and_breaks_the_system/
https://www.reddit.com/r/pop_os/comments/lcl0zv/pop_os_downgraded_from_2010_to_2004_something_is/

I am now afraid to reboot my system. How can I go back to 20.10 now? I see some changes have been made to `/ubuntu/dists/groovy-backports/` in repository, I dont know if this is related to the issue.

**Comment by bflanagin** [comment] 2021-02-05 13:40
Duplicate of #1526 

Lets move the conversation to that issue.

**Closed by bflanagin** 2021-02-05 13:40 UTC
