### ISSUE TITLE
21.04 Fresh Install - LUKS password prompt is not centered

### ISSUE THREAD

**Issue by tuhlmann** [pop-os/pop#1794] opened 2021-07-07 09:09 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
I have a two monitor setup. The left one has a 3840x2160 resolution, the right one is 1920x1200. I had the same setup with the previous version of Pop_OS (20.10) which I also installed fresh, and the previous version would display the LUKS screen correct on both screens.

Now when the machine boots and the LUKS prompt appears, its out of center on both screens (see picture).

Is there a way to configure this after installation?

![PXL_20210703_121319575](https://user-images.githubusercontent.com/407319/124731928-fce1e480-df12-11eb-9436-253acf4dd65a.jpg)

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by jacobgkau** [comment] 2021-07-07 13:20
Duplicate of https://github.com/pop-os/plymouth-theme/issues/19.

**Closed by jacobgkau** 2021-07-07 13:20 UTC
