### ISSUE TITLE
is there a were to remove the external display tearing/stuttering with hybrid mode

### ISSUE THREAD

**Issue by samuaz** [pop-os/pop#1918] opened 2021-09-20 23:55 UTC
Hi guys

this distro is amazing out of the box, only one detail is about the hybrid mode and external display my setup is an intel + nvidia 2080 with nvidia mode all is smooth, but if i use hybrid mode the animations and windows rendering in the external display attached to the nvidia card have tearing stuttering you can see that is not smooth. if i run glx gears i see that the internal laptop display has a vsync enabled and all is smooth but in the external display there is not vsync using the hybrid mode

any way to solve/improve this?

thanks.

**Comment by jacobgkau** [comment] 2021-09-21 14:26
Duplicate of https://github.com/pop-os/nvidia-graphics-drivers/issues/61.

**Closed by jacobgkau** 2021-09-21 14:26 UTC
