### ISSUE TITLE
pop shell extension cannot loaded

### ISSUE THREAD

**Issue by ydhnwb** [pop-os/pop#1787] opened 2021-07-06 07:31 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
Just doing a minor update that bring system76 power and pop shell new version today (6 July 2021). After installed it, the tiling option in top bar are missing and PopShell Extension cannot be activated (it only shows: pop shell error loading extension). This bug make me cannot enable tiling, search everything using Super + / , and many more.

![Screenshot from 2021-07-06 14-24-45](https://user-images.githubusercontent.com/26734262/124560134-ae770c00-de66-11eb-9e91-55b0dce34515.png)

missing tiling option on top bar

![Screenshot from 2021-07-06 14-24-33](https://user-images.githubusercontent.com/26734262/124560157-b5058380-de66-11eb-99c8-7287c773ab08.png)

error loadinge extension

**Steps to reproduce (if you know):**
I just doing some minor updates. Then it is gone after restart.

**Expected behavior:**
It should show tiling option and pop shell should be active.

**Comment by ids1024** [comment] 2021-07-06 14:58
This is probably a duplicate of https://github.com/pop-os/shell/issues/1066.

We're currently working on releasing a fix for it.

**Closed by ids1024** 2021-07-06 14:58 UTC
