### ISSUE TITLE
Super key not working properly on Pop!_OS 20.04

### ISSUE THREAD

**Issue by antonioqfel** [pop-os/pop#1026] opened 2020-05-14 21:49 UTC
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Languages and Region -> Input Sources

**Issue/Bug Description:**

Super key does work when having more than one keyboard input sources.

<img src="https://preview.redd.it/y1q6ttp4p7y41.png?width=980&format=png&auto=webp&s=dc265cac769335b28b2dfd4c16c436d68afd5ea9">

As shown in the above image, I have three input sources for my keyboard: English (default), Canadian French and Spanish.

Super key works with no problem when English language is selected, but as soon as I change it to any of other two languages, Super key does not work.

**Steps to reproduce (if you know):**

1. Add a second or third language to your keyboard input sources.

2. Select any other language than your default language.

3. Press  Super key.

4. Super key does not work

**Expected behavior:**

<img src="https://pbs.twimg.com/media/EYAmIuzWoAEeh7W?format=png&name=4096x4096">

Super key should work in any keyboard input source as it did on version 19.10

**Other Notes:**

<img src="https://preview.redd.it/3sbzspedq7y41.png?width=980&format=png&auto=webp&s=7de15769136d10cdd46120805ec319a0e485da17">

Whether I move the Spanish or French language to the top, Super key works but not in the other two.

In the above image, I moved the Spanish language to the top, hence, Super key only works when Spanish language is selected.

**Comment by leviport** [comment] 2020-05-15 14:06
Duplicate of https://github.com/pop-os/beta/issues/98

**Closed by leviport** 2020-05-15 14:06 UTC
