### ISSUE TITLE
Lock screen clock - Alignment issue

### ISSUE THREAD

**Issue by dani763f** [pop-os/pop#645] opened 2019-08-28 17:07 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
 

**Issue/Bug Description:**
The clock on the lockscreen jumps around at different intervals. This seems to be related to Pop's default UI font (Fira Sans) having different width digits.
Video of the issue can be found here:
https://www.reddit.com/r/pop_os/comments/cvt6op/lock_screen_clock_feature_or_bug/

**Steps to reproduce (if you know):**
- This behaviour happens out of the box for me on 19.04.

**Expected behavior:**
Clock is aligned to the center of the screen and doesnt move around.

**Other Notes:**
Video of the issue here
https://www.reddit.com/r/pop_os/comments/cvt6op/lock_screen_clock_feature_or_bug/

**Comment by monsieur40a** [comment] 2019-09-16 00:51
"Fix" - Shut off seconds:
* gsettings set org.gnome.desktop.interface clock-show-seconds false

**Comment by marcbone** [comment] 2019-10-03 14:08
same problem on the LTS

**Comment by avdzm** [comment] 2020-04-21 19:22
Hello all,
I don't think the fix should be to disable to seconds.

For me, the seconds are useful, I use it as an indicator if my laptop or the xserver frooze or not responding.

I believe the right course should be to adjust the boundry/border lines, to accommodate the space that the seconds use (if that is the cause).

I also tried enableing the seconds and switching to 24 hour clock to remove the am/pm, to compensate the space. 
The date still jumps.

**Comment by leviport** [comment] 2020-04-21 19:29
This is fixed in 20.04 which is set to release very soon. At this point fixing it in 18.04 and 19.10 is something there simply isn't time for.

**Closed by leviport** 2020-04-21 19:29 UTC

**Comment by avdzm** [comment] 2020-04-21 20:35
Understood,
Really excited for the new release. :)

**Comment by avdzm** [comment] 2020-04-23 07:53
Hello all,
In case some users are sticking to 18.04/19.10 for a little longer.
I found a simple solution.

Edit file /usr/share/gnome-shell/theme/pop.css
Go to bracket .screen-shield-clock-time and add the parameter width:720px; 

so it will look like this
.screen-shield-clock-time {
  font-size: 144pt;
  font-weight: 400;
  width:720px;
  text-shadow: 0 1px 5px rgba(0, 0, 0, 0.6);
}
You may need to increase the number if you get a partial 'time + ...'  e.g. '14:0...'

If you like to the and time to be a little bolder, you can double the font-weight from 200 to 400.

Hope this helps. :)
