### ISSUE TITLE
Second monitor will sometimes not switch workspaces with laptop

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#3] opened 2017-10-31 15:37 UTC
_From @vincenttaglia on October 26, 2017 17:37_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - Pop!_OS 17.10 (Artful Aardvark)"
```

**Issue/Bug Description**
When switching workspaces with a monitor connected via HDMI to my System76 laptop, it will only switch the workspace on my laptop.

**Steps to reproduce (if you know)**
I have not found the steps to reproduce yet

**Expected behaviour**
Should switch workspaces on both monitors

**Other Notes**

_Copied from original issue: pop-os/iso#188_

**Comment by isantop** [comment] 2017-10-31 15:37
_From @brs17 on October 27, 2017 21:57_

We are aware of this odd functionality with GNOME. This is how GNOME currently behaves and are discussing how workspaces should function in Pop!_OS. Thank you for your bug report!

**Comment by WatchMkr** [comment] 2017-12-21 23:28
Closing because this is the expected behavior in GNOME.

**Closed by WatchMkr** 2017-12-21 23:28 UTC
Labels: wishlist
