### ISSUE TITLE
20.04 Full system lockup on enabling Tiling on Wayland (AMD gpu)

### ISSUE THREAD

**Issue by r0ckarong** [pop-os/pop#1013] opened 2020-05-12 09:16 UTC
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
**Issue/Bug Description:**
Due to an unrelated GPU bug in the main distro ([unbearable graphics glitch](https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-amdgpu/+bug/1876384)) I need to use the Wayland session. When I do so I can only use the session when Window tiling is disabled. As soon as I turn on tiling (or start the session with tiling enabled) the entire system freezes. No input is accepted, I can't switch to TTY and must to a hard reset.

**Steps to reproduce (if you know):**

- System with AMD graphics, two screens attached.
- Boot system
- Enable Wayland session in config file
- Reboot
- Start wayland session
- Click on Tiling indicator in Gnome Shell
- Click on "Tile Windows"
- Freeze
(optionally)
- Do hard reboot
- Start wayland session with Tiling now "enabled"
- Freeze
(to fix)
- Do hard reboot
- Start X11 session
- Disable Tiling from Gnome Shell
- Log out
- Start Wayland Session
- Works

**Expected behavior:**
Enabling tiling would NOT lock the entire system to an unrecoverable/unresponsive state.

**Other Notes:**

I'd be happy to just use X11 if that problem went away but right now the only reasonable way to use this machine is Wayland.

**Comment by leviport** [comment] 2020-05-12 14:12
Duplicate of https://github.com/pop-os/shell/issues/166

**Closed by leviport** 2020-05-12 14:12 UTC
