### ISSUE TITLE
Wi-fi HotSpot feature not working 

### ISSUE THREAD

**Issue by pranavsambyal** [pop-os/pop#2321] opened 2022-04-28 19:48 UTC
Turning on wifi hotspot in 2.5 Ghz mode turn on the hosted network but clients are unable to connect to the said network,
hotspot not turning on in 5Ghz mode at all. 

Everything was working fine till 21.04

**Comment by jacobgkau** [comment] 2022-04-28 19:56
Duplicate of https://github.com/pop-os/gnome-control-center/issues/225. (If you're having the same issue with clients other than Linux and Android, please feel free to comment that detail in that issue.)

**Closed by jacobgkau** 2022-04-28 19:56 UTC

**Comment by pranavsambyal** [comment] 2022-04-28 20:58
Naa issue is the same will hop on to that thread for more updates and findings
