### ISSUE TITLE
Feature request: search installed apps

### ISSUE THREAD

**Issue by paupin2** [pop-os/pop#2177] opened 2022-01-19 14:53 UTC
**Distribution:** 21.10

**Issue/Bug Description:**
On Pop!_Shop, the search box is disabled on the **Installed** tab. 

**Steps to reproduce (if you know):**
Open Pop!_Shop, switch to the **Installed** tab, click on "Search Apps".

**Expected behavior:**
It should be possible to search in installed apps.
It's especially useful when dozens of apps are installed.

**Comment by leviport** [comment] 2022-01-19 15:57
Duplicate of https://github.com/pop-os/shop/issues/321

**Closed by leviport** 2022-01-19 15:57 UTC
