### ISSUE TITLE
Oryx Pro Hybrid mode does not seem smooth at all

### ISSUE THREAD

**Issue by Geigerkind** [pop-os/pop#1843] opened 2021-07-30 06:09 UTC
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
``` 

**Issue/Bug Description:**
When using hybrid mode, videos start stuttering.

**Steps to reproduce (if you know):**
Go into hybrid mode, watch some video.

**Expected behavior:**
It should be butter smooth.

**Comment by leviport** [comment] 2021-07-30 13:51
This looks like a duplicate of https://github.com/pop-os/nvidia-graphics-drivers/issues/61

Right now it looks to be a shortcoming of the Nvidia driver. As a workaround, switching to Nvidia mode will make external displays perform much better.

**Closed by leviport** 2021-07-30 13:51 UTC
