### ISSUE TITLE
Graphical glitches when resuming from suspend

### ISSUE THREAD

**Issue by raf-r** [pop-os/pop#2258] opened 2022-03-21 23:28 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Gnome Shell

**Issue/Bug Description:**

Sometimes when resuming from suspend there are graphical issues on gnome.

**Steps to reproduce (if you know):**

Resume from suspend

**Expected behavior:**

Resume normally without graphical glitches

**Other Notes:**

When the glitch occurs I have to restart gnome by pressing alt + F2 and type r which does solve the issue.
The problem started around the time I updated to nvidia driver 510.
Hardware GPU GTX 1650.

**Comment by leviport** [comment] 2022-03-21 23:32
I believe this is a duplicate of https://github.com/pop-os/nvidia-graphics-drivers/issues/133

**Closed by leviport** 2022-03-21 23:32 UTC
