### ISSUE TITLE
Bug instalation PopOs 18.04 Nvdia iso with /home separated

### ISSUE THREAD

**Issue by kennyterra** [pop-os/pop#318] opened 2018-07-11 15:17 UTC
As I try to perform the installation of POP OS 18.04 Nvidia version, it error in customizing partitions, allowing only clean installation. I tested it in virtual machine and the problem persists. Has anyone got the solution? help-me. thank you.

**Comment by mmstick** [comment] 2018-07-11 15:25
1. In the installer, when you get the option to do so, select Demo Mode
2. Open a terminal and enter `sudo apt update && sudo apt upgrade -y`, then press y when asked to install updates
3. Restart the installer and try again.

The version of the installer in ISO 24 currently cannot do a custom install due to a bug.

**Comment by mmstick** [comment] 2018-07-11 15:40
Duplicate of https://github.com/pop-os/pop/issues/309

**Closed by mmstick** 2018-07-11 15:40 UTC

**Comment by kennyterra** [comment] 2018-07-11 18:09
Thanks mmstick, for the agility in the response, congratulations!!! works for me.
