### ISSUE TITLE
Extensions failing to load from launcher

### ISSUE THREAD

**Issue by MikeJohnPage** [pop-os/pop#1896] opened 2021-09-05 07:48 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-shell:
  Installed: 3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1623339707~21.04~2a1865d
  Candidate: 3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1623339707~21.04~2a1865d
  Version table:
 *** 3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1623339707~21.04~2a1865d 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
     3.38.4-1ubuntu3~21.04.1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/main amd64 Packages
     3.38.4-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages

**Issue/Bug Description:**
'Extensions' fails to open from the launcher, nothing happens.

**Steps to reproduce (if you know):**
Search for 'Extensions' from the launcher and hit enter to launch.

**Expected behavior:**
'Extensions' should load.

**Other Notes:**
'Extensions' can be opened from the application menu without an issue. All other apps appear to launch fine.

**Comment by leviport** [comment] 2021-09-07 15:15
Duplicate of https://github.com/pop-os/shell/issues/1159

**Closed by leviport** 2021-09-07 15:15 UTC
