### ISSUE TITLE
Feature request: Independent workspaces per monitor

### ISSUE THREAD

**Issue by mojason-81** [pop-os/pop#2206] opened 2022-02-07 04:03 UTC
I do my 9-5 on a Mac.  I'm not a Mac fan-boy, but one thing I really do like and I find helps me be more productive is having the "workspaces" independent on my displays.  I generally have my browser open on one display and on the other I have my terminal, editor, db client, etc open in "workspaces" on the other where I can quickly and easily switch between them (I set up ctrl + arrow keys to move between them).  Would love to have a feature like this in Pop.  Right now it looks like my only options on Pop are to have workspaces active across all displays or only my primary display.

**Comment by jacobgkau** [comment] 2022-02-07 17:47
Thank you for opening an issue. I'm closing this as a duplicate of https://github.com/pop-os/shell/issues/823.

**Closed by jacobgkau** 2022-02-07 17:47 UTC
