### ISSUE TITLE
Pop os does not update

### ISSUE THREAD

**Issue by ChristianKos** [pop-os/pop#2432] opened 2022-05-20 09:55 UTC
I am trying to install the updates that pop os has told me that I have through the pop shop 
but it crashes every time I press "update" button.
I tried to run the updates throught the terminal but every time it says "too many errors"
Is it an os fault?
or do I have to format and install again the distro?
I have pop os 22.04.

**Comment by leviport** [comment] 2022-05-20 15:07
The output from `sudo apt update && sudo apt upgrade` in a terminal would likely reveal what the problem is. I would also recommend taking a look at this article: https://support.system76.com/articles/package-manager-pop

**Comment by ChristianKos** [comment] 2022-05-20 15:52
@leviport Thank you for your answer.

Pop os prompt me to do a recovery partition update.
I did that and then I typed what you wrote "sudo apt update && sudo apt upgrade"
and the result was this.

"Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease                      
Get:2 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]    
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease 
Get:4 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease [99,8 kB]
Hit:5 http://apt.pop-os.org/proprietary jammy InRelease          
Hit:6 http://apt.pop-os.org/release jammy InRelease                            
Fetched 210 kB in 6s (34,0 kB/s)                                               
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded."

Then I went to do a search with pop shop for upadates and no updates where requiered.

I will wait for the next update notification pop shop tells me 
and I will check if I still have the same problem.

**Comment by leviport** [comment] 2022-05-20 15:57
Cool, looks like everything is up to date. I'll close this issue for now, but it can be reopened if the problem comes back.

**Closed by leviport** 2022-05-20 15:57 UTC
