### ISSUE TITLE
EMPTY Applications Screen 

### ISSUE THREAD

**Issue by harshkc** [pop-os/pop#1909] opened 2021-09-17 10:53 UTC
**Distribution :** 21.04
 
 
 
**Related Application and/or Package Version :** No package involved.

**Issue/Bug Description:** Application page is empty i.e. no icons are visible on page 1, page 2 icons are visible. Also, typing anything in the search box brings all the icons back.

**Steps to reproduce (if you know):** Open applications page either through the dock or top bar.

**Expected behaviour:** Applications page should show all the installed apps icons on page 1 as well as page 2.

**Other Notes:**  
WM Theme: Nordic 
Theme: gnome-professional-40.1 [GTK2/3] 
Icons: la-capitaine-icon-theme [GTK2/3] 
Note: changing theme or icons doesn't work, I have been facing this issue for the last 1 month.

**Comment by jacobgkau** [comment] 2021-09-17 14:24
Thank you for the report. I'm closing this as a duplicate of https://github.com/pop-os/pop/issues/1894.

**Closed by jacobgkau** 2021-09-17 14:24 UTC
