### ISSUE TITLE
Jetbrains IDE's (IntelliJ, PHPStorm and WebStorm) windows can't be focused when auto tiling is enabled

### ISSUE THREAD

**Issue by rodzappa** [pop-os/pop#2158] opened 2022-01-11 17:11 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
 

**Issue/Bug Description:**
When auto tiling is enabled, JetBrains Developer IDE's installed through Jetbrains Toolbox can not be focused either by mouse click or keyboard shortcut. When auto tiling is disabled, those windows can be focused without any problems.

**Steps to reproduce (if you know):**
- Install Jetbrains Toolbox
- Install any tool (Webstorm, ex)
- Activate auto tiling (super + y)
- Open a Jetbrains Tool
- Open another app (ex, Firefox)
- Try to put focus on a Jetbrains Tool Windows (focus quickly returns to previous window focused)

**Expected behavior:**
Until last nigh update (10/01/2021) everithing was working correctly. 
Windows focus wasn't a issue.

**Other Notes:**
My setup includes a nvidia GTX 1050 TI, with dual screens (one 4k and another FullHD)

**Comment by jacobgkau** [comment] 2022-01-12 22:20
Duplicate of https://github.com/pop-os/shell/issues/1312.

**Closed by jacobgkau** 2022-01-12 22:20 UTC
