### ISSUE TITLE
Installing nvidia-prime also tries to break the system.

### ISSUE THREAD

**Issue by DucksDont** [pop-os/pop#2020] opened 2021-11-28 13:26 UTC
**Distribution**: Pop!_OS 21.04
 
 
**Related Application and/or Package Version**:

```
nvidia-prime:
  Installed: (none)
  Candidate: 0.8.16.1
  Version table:
     0.8.16.1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main i386 Packages

```

**Issue/Bug Description:**
When I try to install **nvidia-prime**, apt tries to remove essential components.  
```
ducks@pop-os:~$ sudo apt install nvidia-prime
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  fd-find gnome-shell-extension-appindicator gnome-shell-extension-cosmic-dock gnome-shell-extension-desktop-icons-ng gtk2-engines-murrine libqalculate21 libqalculate21-data pop-cosmic pop-gnome-shell-theme pop-gtk-theme pop-icon-theme pop-launcher
  pop-shell pop-shell-shortcuts pop-sound-theme pop-theme qalc xwayland
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  gnome-shell-extension-system76-power pop-default-settings pop-desktop pop-session pop-shell-plugin-system76-power system76-power
The following NEW packages will be installed:
  nvidia-prime
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  pop-desktop pop-session (due to pop-desktop) pop-default-settings (due to pop-desktop)
0 upgraded, 1 newly installed, 6 to remove and 0 not upgraded.
Need to get 9,136 B of archives.
After this operation, 2,774 kB disk space will be freed.
This operation is not permitted because it will break the system.
Abort.
```

**Comment by jacobgkau** [comment] 2021-11-29 16:17
Duplicate of https://github.com/pop-os/session/issues/48.

**Closed by jacobgkau** 2021-11-29 16:17 UTC
