### ISSUE TITLE
Hang On Shutdown After Update to Kernel Version 5.11

### ISSUE THREAD

**Issue by Banjalucan** [pop-os/pop#1613] opened 2021-04-02 17:20 UTC
**Distribution (run `cat /etc/os-release`):**
boris@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 

**Issue/Bug Description:**
After the recent update from kernel v. 5.8 to 5.11, my computer freezes on shutdown. I have to turn it of manually. It worked fine before. 

**Steps to reproduce (if you know):**
Shutdown or reboot

**Other Notes:**
Neofetch dump: 
OS: Pop!_OS 20.10 x86_64 
Host: Blade Stealth 13 (Late 2020) -  
Kernel: 5.11.0-7612-generic 
Uptime: 19 mins 
Packages: 2109 (dpkg), 26 (flatpak) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: GNOME 3.38.3 
WM: Mutter 
WM Theme: Pop 
Theme: Pop [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i7-1165G7 (8) @ 4 
GPU: Intel UHD Graphics 
GPU: NVIDIA GeForce GTX 1650 Ti Mobil 
Memory: 2402MiB / 15768MiB

**Comment by jacobgkau** [comment] 2021-04-02 17:32
Seems like this might be a duplicate of https://github.com/pop-os/linux/issues/41, albeit on different hardware.

**Comment by Banjalucan** [comment] 2021-04-02 22:33
> Seems like this might be a duplicate of [pop-os/linux#41](https://github.com/pop-os/linux/issues/41), albeit on different hardware.

Thank you for the fast reply. 

You are right, it seems like the same problem. The only difference is that my screen stays on (it's black, but the backlight is still on) and the shutdown does not work occasionally in my case, it always fails. 

If you want, you can close this issue and I can follow [pop-os/linux#41](https://github.com/pop-os/linux/issues/41). If i have anything additional to report I can do it there.

**Closed** 2021-04-03 20:11 UTC
