### ISSUE TITLE
PopOS 20.10 Pulseaudio won't recognize audio line-out until pulseaudio restarted 

### ISSUE THREAD

**Issue by Raythonic** [pop-os/pop#1515] opened 2021-01-29 00:34 UTC
Ubuntu 20.10 (PopOS on a custom Skylake generation server, not System76)

Problem started occurring after upgrade from Ubuntu 20.04 (non-PopOS) to Ubuntu 20.10 (PopOS). System never experienced this problem before that upgrade and it's a 5 year old server.

Pulseaudio does not recognize speakers attached to green line-out port of built-in analog card. This is temporarily corrected by restarting pulseaudio service. However, upon next reboot the problem reoccurs. Thus, requiring a pulseaudio restart after every reboot.

To reproduce problem:
1. Speakers plugged in (through green line-out port of built-in card) and speakers are powered on
2. Restart Linux (either after hard power off, or reset, or soft reboot, doesn't matter. BIOS changes do nothing.)
3. System comes up, and pulseaudio dashboard shows no built-in analog stereo under "Output Devices"
4. Restart pulseaudio: systemctl --user restart pulseaudio.service
5. Pulseaudio dashboard now shows built-in analog stereo under "Output Devices"

CONFIGURATION INFORMATION:

cat /etc/issue
Pop!_OS 20.10

uname -a
Linux walkubu 5.8.0-7630-generic #32~1609193707~20.10~781bb80-Ubuntu SMP Tue Jan 5 21:29:56 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
    Playback/recording through the PulseAudio sound server
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
hw:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1150 Analog
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=2
    HDA Intel PCH, ALC1150 Alt Analog
    Direct hardware device without any conversions
plughw:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1150 Analog
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=2
    HDA Intel PCH, ALC1150 Alt Analog
    Hardware device with all software conversions
sysdefault:CARD=PCH
    HDA Intel PCH, ALC1150 Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1150 Analog
    Front output / input
dsnoop:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1150 Analog
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=2
    HDA Intel PCH, ALC1150 Alt Analog
    Direct sample snooping device
usbstream:CARD=PCH
    HDA Intel PCH
    USB Stream Output
hw:CARD=C525,DEV=0
    HD Webcam C525, USB Audio
    Direct hardware device without any conversions
plughw:CARD=C525,DEV=0
    HD Webcam C525, USB Audio
    Hardware device with all software conversions
sysdefault:CARD=C525
    HD Webcam C525, USB Audio
    Default Audio Device
front:CARD=C525,DEV=0
    HD Webcam C525, USB Audio
    Front output / input
dsnoop:CARD=C525,DEV=0
    HD Webcam C525, USB Audio
    Direct sample snooping device
usbstream:CARD=C525
    HD Webcam C525
    USB Stream Output
usbstream:CARD=NVidia
    HDA NVidia
    USB Stream Output

**Comment by leviport** [comment] 2021-01-29 14:59
Duplicate of https://github.com/pop-os/pop/issues/1409

It seems pulseaudio had this regression some time ago, so I'm hoping a fix is inbound. There have definitely been quite a few reports.

**Closed by leviport** 2021-01-29 14:59 UTC

**Comment by Raythonic** [comment] 2021-04-01 22:44
Haven't seen a fix for this yet.  Any update?

**Comment by WereDev** [comment] 2021-05-06 20:42
@Raythonic Ubuntu (and thus PopOS) hasn't updated beyond version 13.99.2 for 20.10 and I'm guessing that they won't be updating that at all since it's not an LTS release.  The plus side is that Ubuntu (and thus PopOS) 21.04 will be running PulseAudio 14.2 which is the latest version from January.  Hopefully this fixes it. :crossed_fingers:

**Comment by JohnReedV** [comment] 2023-12-08 20:18
I am still doing this on every restart on V22.04 :( Any updates?
