### ISSUE TITLE
Pop Shop & Settings menu crash with page up keypress

### ISSUE THREAD

**Issue by joey04** [pop-os/pop#89] opened 2017-12-11 01:20 UTC
**Reporter info**

```
 * Distribution - 17.10 downloaded today
```

**Issue/Bug Description**

Installed today's iso in a VM on Windows to try it out. I already have a Gnome 3 hotkey scheme I like, so one of the first things I'm doing is reassigning some hotkeys. Works fine, but it revealed an odd crash with a specific key sequence.

**Steps to reproduce**
1) go to Settings->Device->Keyboard
2) click on any entry then press Escape -- this is to get focus for navigating the list with up/down arrows and page up/down
3) press Page Up until reach the top; when it reaches the top entry the Settings window crashes every time

**Expected behavior**
No crash, of course :)  It's an odd quirk because up arrow at the very top doesn't crash; neither does page down at the very bottom.
And this same STR didn't cause problems in several other Settings submenus.

**Comment by joey04** [comment] 2017-12-12 07:03
I also have an Ubuntu 17.10 install and it too has this same problem. I'd set it up about a week ago and experienced crashes then, but didn't realize the specific pattern until yesterday in Pop.

(Thankfully Pop hasn't been as buggy as Ubuntu in other areas. I've finished my Pop setup and will be keeping it. You made a lot of nice touches to differentiate it from Ubuntu, and I prefer Pop overall.)

**Comment by joey04** [comment] 2017-12-13 00:50
Just found out that this specific bug also affects Pop Shop. I suppose that would mean it's a Gnome/GTK problem.

**Comment by joey04** [comment] 2017-12-13 00:53
STR in Pop Shop: go to Install list then hit tab to focus the list for scrolling. Then press Page Up at the top of the list and it crashes.

**Comment by brs17** [comment] 2017-12-13 03:20
@joey04 Thanks for submitting this issue!

First looking at the crash happening in gnome-control-center, I can confirm gnome-control-center crashes each time. I also see the journald logs that are output each time it crashes.

`Dec 12 20:15:04 pc gnome-control-center.desktop[4218]: **

Dec 12 20:15:04 pc gnome-control-center.desktop[4218]: Gtk:ERROR:/build/gtk+3.0-wTY3BU/gtk+3.0-3.22.25/./gtk/gtklistbox.c:3094:gtk_list_box_move_cursor: assertion failed: (count > 0)`

Looks like there's some sort of off-by-one error!

**Comment by brs17** [comment] 2017-12-13 03:28
And with the issue in the Pop!_Shop:

`Dec 12 20:22:13 pc io.elementary.appcenter[1471]: **

Dec 12 20:22:13 pc io.elementary.appcenter[1471]: Gtk:ERROR:/build/gtk+3.0-wTY3BU/gtk+3.0-3.22.25/./gtk/gtklistbox.c:3094:gtk_list_box_move_cursor: assertion failed: (count > 0)
`
Looks like the same bug! And you're right it seems to be a bug with gtk.

**Comment by brs17** [comment] 2017-12-13 05:42
@joey04 I have reported the bug upstream to GNOME. I believe the solution is not far away!

https://bugzilla.gnome.org/show_bug.cgi?id=791549

**Comment by brs17** [comment] 2018-01-02 15:58
@joey04 It seems as though the bug in the Pop!_Shop has been fixed, but it is still an issue in the keyboard settings. Will continue to investigate as time allows.

**Comment by brs17** [comment] 2018-03-08 21:43
@joey04  Looks like the keyboard settings page bug is fixed in early versions of 18.04. I'm closing this issue, feel free to reopen if when 18.04 upgrade happens this issue is not resolved.

**Closed by brs17** 2018-03-08 21:43 UTC
Labels: bug, upstream
