### ISSUE TITLE
Date shifting on lock screen

### ISSUE THREAD

**Issue by avdzm** [pop-os/pop#917] opened 2020-04-21 06:46 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
I am not sure, but I believe its GDM3
gdm3:
  Installed: 3.28.3-0ubuntu18.04.5pop1~1551986836~18.04~d21ecd7
  Candidate: 3.28.3-0ubuntu18.04.5pop1~1551986836~18.04~d21ecd7
  Version table:
 *** 3.28.3-0ubuntu18.04.5pop1~1551986836~18.04~d21ecd7 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     3.28.3-0ubuntu18.04.4 500
        500 http://us.archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
     3.28.0-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

**Issue/Bug Description:**
When you enable seconds to show on the top bar, it also shows on the lock screen (which for me that is fine),
But then, on the lock screen the date is jumping from right to center and back to right and so on.

**Steps to reproduce (if you know):**
1) Enable seconds to show on time on the top bar.
2) Lock screen (super+L) and wake up screen (Before login in).

**Expected behavior:**
To stay on the center position.

[lockscreen.dateshifting.with.seconds.zip](https://github.com/pop-os/pop/files/4508156/lockscreen.dateshifting.with.seconds.zip)

**Other Notes:**
I've attached a zip file containing a short video.

**Comment by leviport** [comment] 2020-04-21 16:42
Thank you for the report, however it is a duplicate of https://github.com/pop-os/pop/issues/645 so I'm going to close it for now. It's worth noting that this is fixed in 20.04, which is due for release very soon.

**Closed by leviport** 2020-04-21 16:42 UTC

**Comment by avdzm** [comment] 2020-04-21 19:25
Cool, 
weird that I didnt find the post in the search.
Anyway.

Thank you for the response.
Can't wait for the new release. :)
