### ISSUE TITLE
Screenshot freezes requires hard reset

### ISSUE THREAD

**Issue by anonaddict** [pop-os/pop#2431] opened 2022-05-20 01:53 UTC
**Distribution (run `cat /etc/os-release`):**
 22.04 lts
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Built in screenshot

**Issue/Bug Description:**
Trying to take a screenshot while holding down the left mouse button freezes the pc requiring you to press the power button to reset it

**Steps to reproduce (if you know):**
Hold down left mouse button
Press prtsc
Try resizing the selection or press escape

**Expected behavior:**
Esc should terminate screenshot process

**Other Notes:**

**Comment by leviport** [comment] 2022-05-20 15:04
Duplicate of https://github.com/pop-os/gnome-shell/issues/106

**Closed by leviport** 2022-05-20 15:04 UTC
