### ISSUE TITLE
Login password exposed in plain text!

### ISSUE THREAD

**Issue by bittercold** [pop-os/pop#346] opened 2018-08-26 00:28 UTC
Sorry for duplicate post, I already commented on this issue here:
https://github.com/pop-os/pop/issues/340

but I think this deserves a separate look as it's not about switching TTY consoles.

NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

I just got a new System76 laptop today, and when pressing Alt+left/right to go back and forth in the browser, it was instead switching TTYs. 

But what is really disturbing is that as I was cycling through TTYs, at some point the screen went blank with one blinking cursor in the upper left, and then for a second **my password appeared in plain text on the screen**. Then it logged me back into the GUI.

This somewhat freaked me out, as the password is not supposed to be kept either in memory or on disk. And it must have been, since there wouldn't be any other way to print it.

This the following upstream ticket one user brought up same experience. 
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1508146

**Comment by mmstick** [comment] 2018-08-26 00:41
Closing as duplicate of #292 

There's a fix being tested at the moment, and it it may be released on Monday.

**Closed by mmstick** 2018-08-26 00:41 UTC
