### ISSUE TITLE
Pop OS! 21.04 Cosmic LiveUSB crashing after loading/show installer ( booth .iso versions)

### ISSUE THREAD

**Issue by SwiatLinuksa** [pop-os/pop#1763] opened 2021-07-01 13:19 UTC
Pop OS! 21.04 - cant submit os-release - system not launching
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Hi. I just tried to install popos 21.04 on 3 different computers, 1x laptop hp 840p nvidia nvs3100, desktop i5 6600 750ti 16gb ram and ryzen 1600x with radeon rx570 - all UEFI. All have the same issue - after loading GUI popos and opened installer gnome just crashing to console ( terminal ) and thats it. cant login to root becouse no password was given, tried dd, balena ether and 2 different usb sticks - nothing helps, but in virtualbox it just works... tried amd and nvidia iso, checksums are ok. 
![USER_SCOPED_TEMP_DATA_photo1625143479041_6816345794719583178](https://user-images.githubusercontent.com/59401253/124130585-37fd9700-da7f-11eb-9074-ca242c0be4fa.jpeg)
Nowhere noone knows whats going on. Hardware is 100% ok. 20.04 works well, beta cosmic 21.04 works well too

**Steps to reproduce (if you know):**

Write usb stick, start :)

**Expected behavior:**

No crashing

**Other Notes:**
picture shows ending screen.

**Comment by leviport** [comment] 2021-07-01 15:45
This looks like a duplicate of https://github.com/pop-os/beta/issues/153

Can you try disconnecting ethernet before installing? If that works, then it's the same problem and a fix is in the works.

**Comment by SwiatLinuksa** [comment] 2021-07-01 16:23
Yeah, thats the point! Disconecting ethernet help - run, install without any problems :) Thank you very much for help! Strange that on VirtualBox 6.1.22 on Manjaro its fully works.. Thx again, sry for my english and god bless you for that fantastic OS :)

**Comment by leviport** [comment] 2021-07-01 16:46
Thanks for testing! It's definitely a strange bug. I'm thinking it has something to do with timing since the issue doesn't seem to happen when using really fast USB-C storage for a live disk. Either way, we have a few leads we're investigating, and the next iso should have it resolved. 

I'll close this since it's the same as pop-os/beta#153.

**Closed by leviport** 2021-07-01 16:46 UTC
