### ISSUE TITLE
Changing the hostname in Settings>About doesn't update /etc/hosts and causes a bunch of lag

### ISSUE THREAD

**Issue by d9a** [pop-os/pop#1217] opened 2020-09-05 17:28 UTC
This is on Pop!_OS 20.04.

**Issue/Bug Description:**
/etc/hosts doesn't get updated if you change the hostname in the Settings application. This causes  sudo, web browsers, etc. all to start extremely slowly because the DNS requests are wrong.

**Steps to reproduce (if you know):**
Change the hostname in Settings>About. Try to use sudo, open Firefox, etc.
You can verify this by "cat /etc/hosts"

**Expected behavior:**
/etc/hosts should have all instances of "pop-os" change to the hostname in the settings app.

**Comment by mmstick** [comment] 2020-09-06 05:15
Upstream GNOME issue, but we could potentially patch it

**Comment by mmstick** [comment] 2020-09-06 05:16
Duplicate of https://github.com/pop-os/gnome-control-center/issues/114

**Closed by mmstick** 2020-09-06 05:16 UTC
