### ISSUE TITLE
'Record screencast interactively' only works once

### ISSUE THREAD

**Issue by amokfa** [pop-os/pop#3114] opened 2023-08-20 12:33 UTC
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
gnome-shell:
  Installed: 42.5-0ubuntu1pop1~1675984688~22.04~f574f54
  Candidate: 42.5-0ubuntu1pop1~1675984688~22.04~f574f54
  Version table:
     42.9-0ubuntu2 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
 *** 42.5-0ubuntu1pop1~1675984688~22.04~f574f54 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     42.0-2ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
```

**Issue/Bug Description:**

There is a `Record screencast interactively` entry in the keyboard shortcuts. I can set it and when I press it, the screencast interface is displayed. But the recording is only started the first time I use this feature. Afterwards I get an error saying "Aug 20 17:59:53 pop-os gnome-shell[2567]: Error starting screencast` in journalctl. It starts working after reboot and stops again after using it once.

**Other Notes:**

I can work on this issue. Can someone point me to the location of the source code of this feature?

**Comment by amokfa** [comment] 2023-08-20 12:37
I was able to trace it to this file but there is no `screenshot.js` file on my hard drive.

https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/screenshot.js#L1350

**Comment by fireshaper** [comment] 2023-08-25 22:58
The same thing happens when you press the PrtScr button and record a screencast or use Shift+Ctrl+Alt+R to go straight to the screen recording. It seems like something is not completing correctly because you should get a notification that the screen recording is complete with a button to open the Screencasts folder but there isn't one.

**Comment by anon-legion** [comment] 2023-11-05 00:09
Having the same issue, just got a brand new S76 Pangolin on Pop!_OS 22.04 LTS and the screen record feature is busted.
Im having the worst time trying to make a new github issue for fzf.fish to report a bug because Im trying to screen record my terminal and 70% of the time it doesnt record anything and the other 30% of the time it only records 5s worth of video even if I recorded more than that

**Comment by bryangruneberg** [comment] 2023-11-10 15:36
Same problem as above

**Comment by jacobgkau** [comment] 2023-12-01 00:00
I'm closing this as a duplicate of https://github.com/pop-os/gnome-shell/issues/134, since that issue is in the correct repository (gnome-shell) and was reported 10 days earlier than this one.

**Closed by jacobgkau** 2023-12-01 00:00 UTC

**Comment by plugato** [comment] 2023-12-15 21:52
I am experiencing the same problem.

**Comment by jacobgkau** [comment] 2023-12-15 22:05
@plugato If you have any additional information to provide besides what's already in the issue, you can leave it on the open issue at https://github.com/pop-os/gnome-shell/issues/134.

**Comment by crromatic** [comment] 2024-10-19 17:24
i have the same problom... i just want to send stardew recordings to my friends

**Comment by jacobgkau** [comment] 2025-05-07 19:08
Once again, this issue is at https://github.com/pop-os/gnome-shell/issues/134. I'm locking this page, please go to the other one to make additional comments. ("I'm having this issue too" comments are not useful unless they add more information than previous comments.)
