### ISSUE TITLE
Can't rightclick in file manager list view

### ISSUE THREAD

**Issue by Szwagi** [pop-os/pop#2106] opened 2021-12-22 19:08 UTC
**Distribution:** 21.10

**Related Application:** Files

**Issue/Bug Description:** When using the list view and files fill the entire window, there is no empty spot to right click and get the folder-related context menu with "New Folder", "Open in Terminal" etc.

**Steps to reproduce:**
1. Switch Files to use the list view.
2. Open a folder with enough files to fill the whole window.
3. Try to open the folder-related context menu.

**Expected behavior:** It should only bring up the file-related context menu when right clicked near the file name or icon. Any other empty spot should bring up the folder-related context menu.

**Other Notes:** It works as expected in grid view.

**Comment by jacobgkau** [comment] 2021-12-22 19:37
Upstream issue for this: https://gitlab.gnome.org/GNOME/nautilus/-/issues/1929 

Some upstream duplicates, which provide some info on the UX behind the current design:
https://gitlab.gnome.org/GNOME/nautilus/-/issues/2026 
https://gitlab.gnome.org/GNOME/nautilus/-/issues/1691 
https://gitlab.gnome.org/GNOME/nautilus/-/issues/894 
https://gitlab.gnome.org/GNOME/nautilus/-/issues/41 

Note that right-clicking on the breadcrumb entry for your current folder seems to display the same options as right-clicking on an empty space within the folder, and is available in list view or icon view.

**Comment by jacobgkau** [comment] 2021-12-22 19:38
I'm closing this as a duplicate of https://github.com/pop-os/pop/issues/62 and will post the same info there.

**Closed by jacobgkau** 2021-12-22 19:38 UTC
Labels: upstream
