### ISSUE TITLE
[20.04] Display rotation from gnome display setting is not working

### ISSUE THREAD

**Issue by Dtatoo** [pop-os/pop#933] opened 2020-04-24 21:15 UTC
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
Upgrade
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

If you rotate a secondary display from gnome display configuration left or right it does not rotate.

**Steps to reproduce (if you know):**

Gnome display configuration -> rotate your secondary display

**Expected behavior:**

Rotated display

**Other Notes:**
If you rotate display from NVIDIA X Server setting utility it will rotate correctly. 

Issues are being tracked here:
https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/974
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1874217

**Comment by sirikon** [comment] 2020-05-01 10:29
Happening to me, too. ARandR does the job fine.

You were well aware of this bug during the Beta and it's present on 20.04 release. It's quite infuriating to get releases rushed.

**Comment by zentrobi** [comment] 2020-05-01 12:41
got the same, it also dosn't save my setting, so when ever i shut the system down and then boot it up again, my 2nd screen "view"(for lack of better word) is overlapping my main screen.

**Comment by isamu1024** [comment] 2020-05-01 15:11
Got the same, but it is a constant bug that was present in 19.10 as well for my case.
Need to use ARandR.
Another bug is now, gdm is on my secondary monitor on the first boot, but not when i disconnect my session and relog again. Weird.

**Comment by sirikon** [comment] 2020-05-01 15:17
@isamu1024 The bug wasn't present for me in 19.10, only happened when upgraded to 20.04

**Comment by kasbruh** [comment] 2020-05-01 23:18
> @isamu1024 The bug wasn't present for me in 19.10, only happened when upgraded to 20.04

Same for me. No issues in 19.10

**Comment by kasbruh** [comment] 2020-05-01 23:45
Using ARandR and adding this script to startup applications fixed it for me.
DP-0 is my secondary monitor in portrait mode. I had to add the last two lines to get the monitors to work with their native refresh rate
`#!/bin/sh
xrandr --output DVI-D-0 --off --output HDMI-0 --off --output HDMI-1 --off --output DP-0 --mode 2560x1440 --pos 0x0 --rotate left --output DP-1 --off --output DP-2 --primary --mode 1920x1080 --pos 1440x668 --rotate normal --output DP-3 --off
xrandr --output DP-0 --mode 2560x1440 --rate 144
xrandr --output DP-2 --mode 1920x1080 --rate 240`

**Comment by ilgityildirim** [comment] 2020-05-02 06:39
Same here, no issues for me in 19.10, started happening in 20.04.
For those who needs help;
Install arandr with `sudo apt -y install arandr` then launch it with `arandr`

Use your mouse to adjust; right click for resolution and orientation options. Once you get your layouts right, you can "export" your settings to a shell script (something similar to kasbruh's comment above).

**Comment by Dtatoo** [comment] 2020-05-03 16:55
Issues are being tracked here:
https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/974
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1874217

According to GNOME issue the issue is from Nvidia driver.

> Soo, #980 suggests that Nvidia drivers fail to apply settings correctly sometimes. That smells like exactly what is happening here. In which case, it is all NOTGNOME.

**Comment by ppazos** [comment] 2020-05-29 21:25
I just installed popos on an old computer and the first display is not rotating, also my second screen is not even detected.

**Comment by ChaosBlades** [comment] 2020-06-11 01:22
I just did the whole 'screw windows I'm going to Linux' thing... Well here I am on this issue that is 47 days old.... going back to windows. The workarounds are too much of a pain and it doesn't look like it is getting fixed anytime soon. Both my left and right monitors can't be set to portrait, the monitors actually get disconnected when I try, and the main monitor becomes undetected when the screens time out and turn off. To solve both problems I have to reboot.

**Comment by ppazos** [comment] 2020-06-11 17:29
@ChaosBlades I formated the disk I put PopOS on, and just installed Linux Mint XFCE, works like charm and it's the most similar experience of windows I had on Linux, I'm keeping Linux Mint. PopOS is not reliable yet.

**Comment by anton-matosov** [comment] 2020-06-13 21:37
I have updated from 18.04 to 20.04 and hit this frustrating issue. I have 2 monitors in Portrait mode and it works without any issues before. 
I have found this workaround that worked for me https://askubuntu.com/questions/1230570/cant-rotate-monitor-on-20-04/1247763#1247763
You need to correct `~/.config/monitors.xml` with all your settings , if you have backup from previous install, it should work well, if you don't have it (my case) there is fairly easy way to re-create it.

Easy way to re-create `~/.config/monitors.xml` is using xrandr GUI called `arandr` (can be installed using `sudo apt install arandr`)
Steps:
1. Run `arandr` in terminal or Activites
1. Update your monitor layout in arandr GUI the way you want it
1. Apply changes
1. (optional) Save layout as shell script for future reference using `Layout`=>`Save As` menu
1. Open display tab Settings app
1. Monitors layout should match the one you set in `arandr`
1. Change scale to 200%, apply, keep changes
1. Change scale back to 100%, apply, keep changes. 

This will update your `~/.config/monitors.xml`, after that execute commands:
```
sudo cp ~/.config/monitors.xml /var/lib/gdm3/.config/
sudo chown gdm:gdm /var/lib/gdm3/.config/monitors.xml
```

**Comment by wlad** [comment] 2020-07-07 19:32
just ran into it w/ 20.04 ... no portrait, wrong refresh rates :disappointed: 

arandr helped w/ portrait issue, now going to try script above to fix refresh rate

**Comment by wlad** [comment] 2020-07-07 20:02
just ran into it w/ 20.04 ... no portrait, wrong refresh rates :disappointed: 

arandr helped w/ portrait issue, now going to try script above to fix refresh rate

info from this [comment](https://github.com/pop-os/pop/issues/933#issuecomment-622613131) helped to solve refresh rate issue. seems even to work after reboot.

**Comment by Lwfrancisco** [comment] 2020-07-21 21:02
Also have this issue on 20.04 and simply fixed it using the arandr GUI as described in the comments above (install arandr, rotate the desired display, apply). I don't use portrait mode that often so a 30s manual fix is fine (for now) but I'd like a more official fix if possible.

**Comment by jacobgkau** [comment] 2020-07-22 22:18
It looks like a fix is coming down the pipeline now.

The issue does occur in Ubuntu 20.04 with Mutter 3.36.3 and NVIDIA 440.100. (Interestingly, the issue is not currently occurring on Debian 11 (Testing), even though it also includes Mutter 3.36.3 and NVIDIA 440.100.)

After installing the following updates from [Ubuntu proposed](https://wiki.ubuntu.com/Testing/EnableProposed), the issue is fixed (on both Pop!_OS 20.04 and Ubuntu 20.04):
gir1.2-mutter-6 (3.36.4-0ubuntu0.20.04.1)
libmutter-6-0 (3.36.4-0ubuntu0.20.04.1)
mutter-common (3.36.4-0ubuntu0.20.04.1)

These three components are being upgraded from 3.36.3 to [3.36.4](https://gitlab.gnome.org/GNOME/mutter/-/compare/3.36.3...3.36.4). Once we're able to release 3.36.4 in Pop, this issue should be resolved.

**Comment by eddiefiggie** [comment] 2020-07-27 17:21
I found a workaround that worked out for me after battling this issue.

In your display settings, first orient the monitors (drag-drop) the monitors on top of one another versus left-right. Then make the monitor on top go Portait-Right. Should work, then drag that monitor now to its appropriate place to the left or right of your other monitor.

Worked me more than once.

**Comment by CodeMonkeyX** [comment] 2020-07-28 20:34
For me I am having this issue on a Chromebook I converted to Linux. It has a tablet mode and a flappable screen. It would boot correctly, the login would display correctly, then something would load that inverted the screen. Also, the screen would switch to portrait at the the slightest bump. So I removed "iio-sensor-proxy" (suggest on Reddit) and that seems to have fixed it for me. Not sure if it's directly related to this issue for others or not.

**Comment by jacobgkau** [comment] 2020-07-29 19:06
> For me I am having this issue on a Chromebook I converted to Linux. It has a tablet mode and a flappable screen. It would boot correctly, the login would display correctly, then something would load that inverted the screen. Also, the screen would switch to portrait at the the slightest bump. So I removed "iio-sensor-proxy" (suggest on Reddit) and that seems to have fixed it for me. Not sure if it's directly related to this issue for others or not.

That does not sound related to this issue. This issue is regarding the inability to set displays to portrait mode using the Settings -> Displays interface.

This issue is resolved by https://github.com/pop-os/mutter/pull/5, which updates mutter to 3.36.4.

**Comment by Shemeikka** [comment] 2020-08-03 14:40
With the latest updates installed, this problem is now fixed for me when using two monitors.

```
# apt list --installed |grep mutter

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gir1.2-mutter-6/focal,now 3.36.4-0ubuntu0.20.04.1pop3~1596137403~20.04~a912c7f amd64 [installed,automatic]
libmutter-6-0/focal,now 3.36.4-0ubuntu0.20.04.1pop3~1596137403~20.04~a912c7f amd64 [installed,automatic]
mutter-common/focal,focal,now 3.36.4-0ubuntu0.20.04.1pop3~1596137403~20.04~a912c7f all [installed,automatic]
mutter/focal,now 3.36.4-0ubuntu0.20.04.1pop3~1596137403~20.04~a912c7f amd64 [installed,automatic]
```

**Closed** 2020-08-07 10:20 UTC

**Comment by codecreate-dev** [comment] 2020-09-05 00:49
I needed this tonight and realised there was no rotation button, 20.04. 
I am using RealVNC on my ipad with the VNC server on Ubuntu, a HP x 360 .
The solution is to run:

`sudo xrandr -o left`

then ...

`sudo xrandr -o normal`

to reset it. My HP rotates when I physically rotate it in tablet mode. 
It would be nice to have this in the settings or back where it was previously, however I can live with this fix. I will add it in my .bash_aliases file

**Comment by mblaughton** [comment] 2020-09-09 03:37
I don't think my problem was the exact issue described here, but after spending many hours chasing it down (and being directed here by Google several times) I'd like to mention my solution for those in the same situation:

**My Setup**
Ubuntu 20.04 (fresh install)
NVIDIA GeForce GTX 1050 Ti / driver: 440.100
Left monitor (primary): 5120x2880 - landscape
Right monitor: 2048x2560 - portrait

**My Problem**
I easily configured the displays to my desired configuration for each user through Gnome Settings > Displays (including rotation, offset, and fractional scaling) but the gdm login screen still displayed the user list on the right monitor rotated 90 degrees. I tried copying the ~/.config/monitors.xml to /var/lib/gdm3/.config/monitors.xml but it didn't have any effect.

**My Solution**
What finally worked was to create a version of monitors.xml that didn't have fractional scaling enabled. After copying that over it worked immediately, and I can still use fractional scaling for the regular users.

Hope this helps someone.
