### ISSUE TITLE
keyboard shortcuts for split view not woeking after modification

### ISSUE THREAD

**Issue by pollaloca** [pop-os/pop#796] opened 2019-12-24 15:50 UTC
**Distribution (run `cat /etc/os-release`):**
 DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Pop!_OS 19.10"
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
I've just changed the default keyboard shortcut for splitting views from Ctrl + Supr + arrow key to Supr + arrow keys.

Toggle maximization state (Supr + up):  works fine
Restore window (Supr + down): works fine
View split on left (Supr + left): not working (the window doesn't move at all)
View split on right (Supr + right): not working the window doesn't move at all)

**Steps to reproduce (if you know):**

**Expected behavior:**
View split on left (Supr + left): should move the window to the left and take half of the space
View split on right (Supr + right): nshould move the window to the right and take half of the space

**Other Notes:**

**Comment by crawfxrd** [comment] 2019-12-24 16:58
Duplicate of #409

**Closed by crawfxrd** 2019-12-24 16:58 UTC
