### ISSUE TITLE
gnome-shell JS Error when super key is hit to enter activities panel, showing only desktop

### ISSUE THREAD

**Issue by marthinwurer** [pop-os/pop#1855] opened 2021-08-05 03:18 UTC
**Distribution (run `cat /etc/os-release`):**
 ```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
$ apt policy gnome-shell
gnome-shell:
  Installed: 3.36.7-0ubuntu0.20.04.1pop1~1614014876~20.04~4e7877a
  Candidate: 3.36.7-0ubuntu0.20.04.1pop1~1614014876~20.04~4e7877a
  Version table:
     3.36.9-0ubuntu0.20.04.2 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
 *** 3.36.7-0ubuntu0.20.04.1pop1~1614014876~20.04~4e7877a 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     3.36.4-1ubuntu1~20.04.2 500
        500 http://us.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages
     3.36.1-5ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**Issue/Bug Description:**
When trying to play a game via Steam Proton, I hit the super key to switch to another window. When I do so, all windows disappear and I'm stuck looking at my desktop. I cannot open any new windows or interact with anything besides the top bar. In syslog, I see the following error from gnome-shell:
```
Aug  2 21:02:39 pop-os gnome-shell[2500]: JS ERROR: TypeError: app is null#012_getCaption@resource:///org/gnome/shell/ui/workspace.js:644:9#012WindowOverlay@resource:///org/gnome/shell/ui/workspace.js:498:48#012_addWindowClone@resource:///org/gnome/shell/ui/workspace.js:1857:23#012_init@resource:///org/gnome/shell/ui/workspace.js:1174:22#012_updateWorkspaces@resource:///org/gnome/shell/ui/workspacesView.js:232:29#012_init@resource:///org/gnome/shell/ui/workspacesView.js:91:14#012_updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:682:24#012show@resource:///org/gnome/shell/ui/workspacesView.js:612:14#012show@resource:///org/gnome/shell/ui/viewSelector.js:276:33#012_animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27#012show@resource:///org/gnome/shell/ui/overview.js:566:14#012toggle@resource:///org/gnome/shell/ui/overview.js:689:18#012_initializeUI/<@resource:///org/gnome/shell/ui/main.js:223:22

```

**Steps to reproduce (if you know):**
Start Squad from Steam using the Proton compatibility layer. When it is running, hit the super key.

**Expected behavior:**
The menu appears like normal, and I am able to click out of it and continue using my computer

**Other Notes:**
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4516
Posted to the gnome-shell issue tracker, they told me to come here because the version was too out of date for them.

I have removed the keycap of the super key so I don't accidentally hit it again while playing.

**Comment by DMGPage** [comment] 2021-08-05 06:40
Noticed same issue today after updating my pop os 20.04. Before update all worked just fine.

**Comment by mmstick** [comment] 2021-08-05 10:45
Duplicate of https://github.com/pop-os/shell/issues/1123

**Closed by mmstick** 2021-08-05 10:45 UTC
