### ISSUE TITLE
Unable to disable startup OS upgrade notification

### ISSUE THREAD

**Issue by 4a454646** [pop-os/pop#2103] opened 2021-12-22 15:01 UTC
**cat /etc/os-release**
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**apt policy gnome-control-center**
```
gnome-control-center:
  Installed: 1:3.38.3-1pop1~1625268318~21.04~2880306
  Candidate: 1:3.38.3-1pop1~1625268318~21.04~2880306
  Version table:
     1:3.38.5-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
 *** 1:3.38.3-1pop1~1625268318~21.04~2880306 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
```

I am unable to disable the startup notification that pops up with the message "New version available (21.10)". I have no desire to upgrade at the moment and have done my best to disable it, but no luck.

Things I have tried:
- Going to Settings>Applications>PopShop and disabling notifications
- Going to the Pop Shop itself and turning off updates
- Going to Settings>OS Upgrade and Recovery, but there is no button to turn off notifications, only one to download the new version.
- Disabling the upgrade notifier in Startup Applications
- Removing the upgrade notifier entirely from Startup Applications

However after all of my efforts this notification still just has to pop up every time I start up. It's only there for a second so this is no means a huge priority bug fix, but I still find it quite annoying especially given the lengths I've gone to do disable it.

**Comment by leviport** [comment] 2021-12-22 16:21
Duplicate of https://github.com/pop-os/upgrade/issues/235

It's worth noting that support for 21.10 will end in January, so the notification probably shouldn't be ignored for too much longer.

**Closed by leviport** 2021-12-22 16:21 UTC

**Comment by 4a454646** [comment] 2021-12-22 16:54
The issue I have is that if I ugprade to 21.10, it will run kernel 5.15xxx which does not have support for my Wifi card, so I am waiting to upgrade.
However I have run the command on the duplicate issue and now the notification is gone.

**Comment by jacobgkau** [comment] 2021-12-22 16:57
> The issue I have is that if I ugprade to 21.10, it will run kernel 5.15xxx which does not have support for my Wifi card, so I am waiting to upgrade.

The same kernel is currently being used across 21.10, 21.04, and 20.04 LTS, so that should not be a factor in your decision of whether or not to upgrade, just to let you know. (You can see from the [kernel repo](https://github.com/pop-os/linux/) that only 18.04 and 19.10 have separate kernel branches.)

A tool such as [mainline](https://github.com/bkw777/mainline) might allow you to install an older kernel manually on 21.10.

**Comment by 4a454646** [comment] 2021-12-22 17:14
I ran apt-hold mark on my kernel so it wouldn't upgrade to 5.15, I'm currently on `5.13.0-7620-generic`. I will look into mainline in the future though.
