### ISSUE TITLE
Progressive Web Apps overwrite Chrome in the Alt Tab list

### ISSUE THREAD

**Issue by dwarburt** [pop-os/pop#1977] opened 2021-11-01 19:15 UTC
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```google-chrome-stable:
  Installed: 94.0.4606.54-1
  Candidate: 94.0.4606.54-1
  Version table:
 *** 94.0.4606.54-1 500
        500 http://apt.pop-os.org/proprietary hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

After installing browser apps ([PWA](https://support.google.com/chrome/answer/9658361)) with Chrome, such as YouTube or Outlook, then these replace Chrome in the alt tab list. Activate the YouTube Music PWA, and then the icon for YouTube Music appears instead of the Chrome icon. The other chrome windows do not get grouped under that icon as application windows, but if you find Chrome and switch back to it, it will be restored in the alt tab list and the PWA is gone. Which ever one was activated last wins, it seems.

**Steps to reproduce (if you know):**

Install Chrome, Install a PWA, try to alt-tab between chrome and your PWA at the same time. The one you're trying to switch to does not appear in the alt tab list.

**Expected behavior:**

Both icons will be in the alt-tab list

**Other Notes:**

I've seen this with YouTube Music and Outlook but I haven't tested any others.

**Comment by jacobgkau** [comment] 2021-11-01 19:19
Thank you for the report. This has already been reported here: https://github.com/pop-os/shell/issues/1067 

I've re-opened that issue and am closing this one as a duplicate. It sounds like it's an issue being caused by Pop Shell, but if not, that issue can be transferred to the appropriate repository.

**Closed by jacobgkau** 2021-11-01 19:19 UTC
