### ISSUE TITLE
Apps in Pop Shop not updated for a while

### ISSUE THREAD

**Issue by github2099** [pop-os/pop#2856] opened 2023-04-05 20:57 UTC
Running latest Pop OS 22.04

The apps that I intended to use are outdated in Pop Shop.

ex. Virtual Box, Pinta, pdfarranger, gnucash. etc.

**Comment by jacobgkau** [comment] 2023-04-05 21:07
> ex. Virtual Box, Pinta, pdfarranger, gnucash. etc.

Pop!_OS does not package Pinta, pdfarranger, or gnucash. You can see this by running `apt policy pinta pdfarranger gnucash`; you will see that all of the URLs are `apt.pop-os.org/ubuntu` (our Ubuntu mirror) and not `apt.pop-os.org/release` (the Pop!_OS repository.) For those packages, you would need to go upstream to Ubuntu to get them updated, although Ubuntu intentionally does not release feature updates mid-release, so it's unlikely that they will be.

That said, all three of these packages have Flatpak options available from Flathub, and Pop!_OS includes Flathub by default. For PDF Arranger, you can uninstall the app with `Ubuntu (deb)` selected in the drop-down, then install it again with `flathub (flatpak)` selected. The other two apps have separate listings for the .deb and Flatpak versions-- simply uninstall the one that's currently installed, and then install the other one (the Flatpak will include the words `Up to...` in the size listing below the install button.)

VirtualBox is actually packaged by Pop!_OS: https://github.com/pop-os/virtualbox We have a [pull request](https://github.com/pop-os/virtualbox/pull/7) open for version 7.0.6, but it currently contains a packaging regression and does not work on Pop!_OS 20.04, so it requires engineering attention before it can move forward for 22.04.

I'm going to close this issue since it's not actionable from here, but you can follow the VirtualBox repository for updates and open an issue in that repository (including the version you're wanting and what features in that version you need) for that specific application if you'd like.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Closed by jacobgkau** 2023-04-05 21:07 UTC
