### ISSUE TITLE
Keyboard-Shortcut "Super+right" for window-split and stick to the right side doesn't work

### ISSUE THREAD

**Issue by papa-sierra** [pop-os/pop#683] opened 2019-10-06 20:20 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
LOGO=distributor-logo-pop-os 
 
**Related Application and/or Package Version (run `apt policy $ PACKAGE NAME`):**
Settings-App:
gnome-control-center:
  Installed: 1:3.32.2-1ubuntu2pop1~1565997433~19.04~e390710
  Candidate: 1:3.32.2-1ubuntu2pop1~1565997433~19.04~e390710
  Version table:
 *** 1:3.32.2-1ubuntu2pop1~1565997433~19.04~e390710 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status
     1:3.32.2-0ubuntu1.1 500
        500 http://us.archive.ubuntu.com/ubuntu disco-updates/main amd64 Packages
     1:3.32.1-1ubuntu4 500
        500 http://us.archive.ubuntu.com/ubuntu disco/main amd64 Packages

**Issue/Bug Description:**
When setting the Keyboard-Shortcut in the section "Window" for the function "View split on right" to the combination "Super+right", it just won't work. With any other combination (like Super+Shift+Right) it works fine, but not with "super+right"... 
As I didn't find anything about this in any docs, I thought I'll report it.

**Steps to reproduce (if you know):**
Open gnome-control-panel > Devices > Keyboard > Set shortcut as mentioned before.

**Expected behavior:**
Window should get sticked to the right side of the screen, customarily using 50% of the available space.

**Other Notes:**
n/a

Thanks guys for everything! Best Distro I've ever used - and I'm a poweruser.

**Comment by gncgnc** [comment] 2019-11-05 14:29
I'm having the same issue in 18.04 . When I change the shortcut to be Super + Right, it does not work with the regular arrow key. However, it seems to work with the numpad arrow key. I change it back to the default shortcut, Ctrl + Super + Right, and it works. 

But after a reboot, that shortcut also doesn't work. I change it back to Super + Right, and now that one works! This also happens for the left shortcut sometimes.

**Comment by crawfxrd** [comment] 2019-12-24 17:00
Duplicate of #409

**Closed by crawfxrd** 2019-12-24 17:00 UTC
