### ISSUE TITLE
Pop!_OS 20.04 stuck in Overview/Workspace perspective 

### ISSUE THREAD

**Issue by rbdavid** [pop-os/pop#1816] opened 2021-07-15 13:54 UTC
I am noticing this issue after installing the recent OS updates that were pushed to the Pop!_Shop yesterday. 

**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
etc 

CPU info:
Intel Core i7-7700 

GPU info:
Intel HD Graphics 630
GeForce GTX Titan X
GeForce GTX 1080

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
Hitting the super key takes me to the workspaces/overview perspective, as desired. Once in that view, I cannot escape out of it. While in this view, I can click on applications to start them but I cannot view or interact with the respective GUI. No active workspaces are present. Keyboard shortcuts work (ex, Ctrl+Alt+Del, etc); no shortcuts that open up an application window will escape me from the overview perspective.  

**Steps to reproduce (if you know):**
I restarted my computer after an OS update that was pushed out yesterday through Pop!_Shop. After the restart, this bug occurs immediately. If I do not hit the super key, thereby moving me into the overview perspective, then my computer works fine. If the first thing I do once logged in is press the super key, I become locked in the perspective. 

I have turned off all gnome extensions that I had installed and running, hoping that the error was originating from one of them. 

**Expected behavior:**
I should be able to escape out of the overview/workspaces perspective.

**Comment by jacobgkau** [comment] 2021-07-15 14:04
Thank you for reporting. This is a duplicate of https://github.com/pop-os/shell/issues/1072. If any further discussion is necessary, please use that issue.

A fix has been merged and is in the process of being released now.

**Closed by jacobgkau** 2021-07-15 14:04 UTC
