### ISSUE TITLE
Kdenlive is missing dependencies and fails to run.

### ISSUE THREAD

**Issue by sramkrishna** [pop-os/pop#119] opened 2018-01-15 22:41 UTC
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)

NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

kdenlive:
  Installed: 4:17.08.2-0ubuntu1
  Candidate: 4:17.08.2-0ubuntu1
  Version table:
 *** 4:17.08.2-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description**

When installing  kdenlive, it seems that some pre-requisites are missing.  After installing the package, I get a window that says breeze-icons and vlc/xine is missing.

It seems that neither are installed as part of installing the package.  The breeze-icons are not available in Pop!_Shop or GNOME Software but can be installed from command line.  That's likely the issue.

**Steps to reproduce (if you know)**

go to Pop! Shop, install kdenlive

**Expected behavior**

Application installs and runs properly.

**Other Notes**

The original bug was reported at - https://itsfoss.com/pop-os-linux-review/ in the comments below as part of the criticism the poster had of Pop!_OS.

**Comment by jacobgkau** [comment] 2020-07-14 18:04
This seems to have been caused by messy packaging. Kdenlive did (and still does) require `breeze-icon-theme` to display its interface correctly, but in 17.10, `kdenlive` did not depend on `breeze-icon-theme`, leading to this message:

![kdenlive-1710](https://user-images.githubusercontent.com/7199422/87449365-58a4b680-c5ba-11ea-8df9-0afeb0a4e9c6.png)

Upgrading from 17.10 to 18.04 LTS using do-release-upgrade pulls in `breeze-icon-theme` as a dependency of the newer `kdenlive` package:

![kdenlive-1804](https://user-images.githubusercontent.com/7199422/87452242-34e36f80-c5be-11ea-996a-8e8b3d589afd.png)

18.04 still shows a warning about vlc or xine missing, even though neither of those packages are recommended by the 18.04 `kdenlive` package (4:17.12.3-0ubuntu1) and they are truly optional, as opposed to the icons.

In 20.04, I can install Kdenlive from the Pop!_Shop and launch it immediately with no warnings. The dependency check in Kdenlive's configuration wizard has been removed in favor of displaying a message when the user actually attempts to use the DVD preview functionality, which makes more sense given how it's buried fairly deep within the program and isn't critical to normal editing usage. To get this message, you need to first generate a DVD image using the DVD wizard (File -> DVD Wizard), then click the "Preview" button:

![kdenlive-2004](https://user-images.githubusercontent.com/7199422/87456041-9b1ec100-c5c3-11ea-802c-ece59ca9a70b.png)

It does seem like Kdenlive's package should recommend (or at least suggest) xine or vlc. This is the case in [Arch](https://www.archlinux.org/packages/extra/x86_64/kdenlive/), but is not the case in [openSUSE](https://build.opensuse.org/package/view_file/openSUSE:Factory/kdenlive/kdenlive.spec?expand=1) right now. There was a [Launchpad bug](https://bugs.launchpad.net/ubuntu/+source/kdenlive/+bug/1001646) in 2012 to make the Kdenlive package depend on Xine (before VLC support was added), and Ubuntu referred upstream to Debian for adding Xine to recommends. I do not see any archived bugs on the Debian package about this.

VLC can at least be installed through the Pop Shop, although only the deb version works with Kdenlive, not the Flatpak version.

**Comment by jacobgkau** [comment] 2020-07-14 20:26
Opened a Debian bug report to make kdenlive suggest vlc or xine-ui: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=965042 

Closing this issue since Kdenlive is not missing any dependencies and does not fail to run.

**Closed by jacobgkau** 2020-07-14 20:26 UTC
Labels: confirmed
