### ISSUE TITLE
Spotify can't be updated

### ISSUE THREAD

**Issue by dodalovic** [pop-os/pop#1277] opened 2020-10-08 11:34 UTC
Latest POP OS

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://repository.spotify.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D1742AD60D811D58
E: http://repository.spotify.com stable InRelease is not (yet) available (The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D1742AD60D811D58)
```

Please, let me know if additional info is needed. 
Thanks for the great product!

**Comment by leviport** [comment] 2020-10-08 14:23
Duplicate of https://github.com/pop-os/pop/issues/1278

**Closed by leviport** 2020-10-08 14:23 UTC
