### ISSUE TITLE
19.10: System takes ~40 seconds to move off of cryptsetup plymouth page 

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#671] opened 2019-09-30 13:17 UTC
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10 iso2 (having run updates)

**Issue/Bug Description:**
After providing the disk decryption password, the Plymouth screen shows `Cryptsetup cyyptsetup:cryptdata set up successfully` for around 40 seconds before the GDM lock screen appears.

**Comment by mmstick** [comment] 2019-09-30 21:59
Is there any useful info from `systemd-analyze blame`? An long disk decryption screen is caused by a service that's waiting to start.

**Comment by jackpot51** [comment] 2019-10-17 16:25
This should be fixed in https://github.com/pop-os/systemd/commit/28c8cd35cf52fceb360d83725184e7b1d6811773

**Comment by jackpot51** [comment] 2019-10-17 21:01
This was fixed in new initramfs-tools package

**Closed by jackpot51** 2019-10-17 21:01 UTC
Labels: 19.10
