### ISSUE TITLE
Custom partitioner does not detect unlocked LVM on LUKS

### ISSUE THREAD

**Issue by bbaserdem** [pop-os/pop#685] opened 2019-10-08 00:07 UTC
**Distribution (run `cat /etc/os-release`):**
Pop OS live usb. (most recent)
 
**Issue/Bug Description:**
I already have my drive partitioned with LUKS, which has LVM under it. Here is my partitioning map, as seen by Arch Linux.
```
NAME               MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
nvme0n1            259:0    0   1.9T  0 disk
└─nvme0n1p1        259:1    0   1.5T  0 part
  └─crypthome      254:4    0   1.5T  0 crypt
    └─Data-Home    254:5    0   1.5T  0 lvm   /home
nvme1n1            259:2    0   477G  0 disk
├─nvme1n1p1        259:3    0   550M  0 part  /esp
└─nvme1n1p2        259:4    0 476.4G  0 part
  └─cryptroot      254:0    0 476.4G  0 crypt
    ├─Linux-Arch   254:1    0   100G  0 lvm   /.snapshots
    ├─Linux-Swap   254:2    0    50G  0 lvm   [SWAP]
    └─Linux-PopOS  254:3    0    50G  0 lvm
```
In Pop OS live environment, I issue `sudo cryptsetup luksOpen /dev/nvme1n1p2 cryptroot` in the terminal without issues and I am able to browse the file system after mounting. (Along with home) However, the installer custom partitioner does not see the unlocked LUKS volumes, and shows me the unlocked partitions as the install target.

I have approached the installer both by manually unlocking the partitions and by leaving them alone. In both cases, the installer tells me that my LUKS partitions do not have LVM underneath.

**Steps to reproduce (if you know):**
Have my partitioning layout and try to install pop-os

**Expected behavior:**
Expect to see /dev/mapper/Linux-PopOS as an installation target.

**Other Notes:**
It would be great if I could mount everything to /mnt myself and let the installer install everything to mount, and then fix things myself.

**Comment by mmstick** [comment] 2019-10-08 01:52
duplicate of https://github.com/pop-os/distinst/issues/193

**Closed by mmstick** 2019-10-08 01:52 UTC
