### ISSUE TITLE
Super + / not available in EU keyboards

### ISSUE THREAD

**Issue by defecador** [pop-os/pop#967] opened 2020-05-03 18:21 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Tile Windows

**Issue/Bug Description:**
in European keyboards also not super + / Probably because / = shift + 7 but Super + shift + 7 is also not working. would be perfect to have the possibility to change this shortcut

**Steps to reproduce (if you know):**

Set up the keyboard to German and try to do Super + / (in German keyboards the / is in shift + 7)

**Expected behavior:**

HAve this shortcut available in Keyboard shortcuts. Tried to add it but also doesnt work

**Other Notes:**

**Comment by mmstick** [comment] 2020-05-04 15:19
Duplicate of https://github.com/pop-os/shell/issues/196

**Closed by mmstick** 2020-05-04 15:19 UTC
