### ISSUE TITLE
Icon Overlap in Activities Menu

### ISSUE THREAD

**Issue by Appalbarry** [pop-os/pop#252] opened 2018-05-02 00:49 UTC
(Note: sometime this week I'll install 18.10 and see if this remains)
 **Distribution - (run ```cat /etc/os-release```)**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Issue/Bug Description**
As applications are opened, their icons are added to the Activities Menu.
The bottom application icon overlaps the "Show Applications" icon at the bottom.  
Eventually you are not able to open the bottom most application because its icon is behind the "Show Applications" icon

**Steps to reproduce (if you know)**
Launch applications, the Activities menu fills up.

**Expected behavior**
Icons will respect each other's space.

**Other Notes**
See attached screen grab.
/home/barryrueger/Desktop/Screenshot from 2018-05-01 17-35-32.png
![image](https://user-images.githubusercontent.com/1308152/39500232-e10271a2-4d67-11e8-836e-682da6fd1c5c.png)

**Comment by brs17** [comment] 2018-05-02 01:05
@Appalbarry Thank you for filing this issue. This is a duplicate of https://github.com/pop-os/gnome-shell-theme/issues/23 I am going to close this issue, feel free to follow it and add more detail as requested there.

**Closed by brs17** 2018-05-02 01:05 UTC
