### ISSUE TITLE
app icon enlarges by itself

### ISSUE THREAD

**Issue by ariasyqolani** [pop-os/pop#1882] opened 2021-08-27 07:44 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-cosmic-applications.desktop

**Issue/Bug Description:**
after updating the system via pop shop and rebooting the computer the application icon in the menu becomes very large

**Steps to reproduce (if you know):**

**Expected behavior:**
normal icon size

**Other Notes:**
after changing screen resolution icon size to normal

**Comment by ahmed-kaif** [comment] 2021-09-04 11:44
I also faced the problem when I set the dock icon size to custom. But when I select small the issue gets solved..

**Comment by jacobgkau** [comment] 2021-09-07 15:54
Closing as a duplicate of https://github.com/pop-os/pop/issues/1786.

**Closed by jacobgkau** 2021-09-07 15:54 UTC
Labels: needs more info
