### ISSUE TITLE
Only showing dummy output as audio device

### ISSUE THREAD

**Issue by jontok** [pop-os/pop#2674] opened 2022-11-03 16:46 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Maybe:
```text
pipewire:
Installed: 0.3.59-0pop1~1664857105~22.04~83dda19
Candidate: 0.3.59-0pop1~1664857105~22.04~83dda19
Version table:
 *** 0.3.59-0pop1~1664857105~22.04~83dda19 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu2 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
```

**Issue/Bug Description:**
After Updating my `ThinkPad P15s Gen 2i` would not show any audio devices except `Dummy Output/Input`. After an BIOS Update it showed my external USB Webcam (Logitech C270) as the only Input.

**Steps to reproduce (if you know):**

**Expected behavior:**
Show All Audio out and input devices.
- Speaker
- Audio Jack
- Microphone array
- Headset if connected

**Other Notes:**
`uname -r`
 
Output: `6.0.3-76060003-generic

**Comment by leviport** [comment] 2022-11-03 16:50
This looks like a duplicate of https://github.com/pop-os/pop/issues/2487, but I can reopen if I'm mistaken.

**Closed by leviport** 2022-11-03 16:50 UTC
