### ISSUE TITLE
Device Name in settings app is incomplete

### ISSUE THREAD

**Issue by 400Ferrets** [pop-os/pop#2701] opened 2022-11-21 15:25 UTC
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
 
**Issue/Bug Description:**
When changing Device Name in the about section of the settings app, /etc/hostname is properly filled but /etc/hosts is not.

**Steps to reproduce (if you know):**
1. On a fresh install of Pop!_OS open the settings app
2. Click the Device Name field and change it to anything but pop-os
3. Observe that /etc/hostname and /etc/hosts now conflict

**Expected behavior:**
/etc/hosts would be filled with the new hostname

**Other Notes:**
The conflicting hostname can cause many commands to stall for 10+ seconds.

**Comment by jacobgkau** [comment] 2022-11-21 16:08
Duplicate of https://github.com/pop-os/systemd/issues/5.

**Closed by jacobgkau** 2022-11-21 16:08 UTC
