### ISSUE TITLE
Luters 's wine instance ,Virtual boxes window remain open and unresponsive in the dock even after terminating them from the main program.

### ISSUE THREAD

**Issue by esrocker1** [pop-os/pop#992] opened 2020-05-06 05:38 UTC
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment] 2020-05-06 16:34
Duplicate of https://github.com/pop-os/shell/issues/220

Thanks for the report, but this should already have been fixed. Install updates and reboot, then if the issue persists, please add a comment on https://github.com/pop-os/shell/issues/220 so we know to reopen the issue.

**Closed by leviport** 2020-05-06 16:34 UTC
