### ISSUE TITLE
Unable to insatll ttf-mscorefonts-installer

### ISSUE THREAD

**Issue by gingermybuddy** [pop-os/pop#1902] opened 2021-09-09 18:35 UTC
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
 
 
ttf-mscorefonts-installer:
  Installed: (none)
  Candidate: 3.8ubuntu2
  Version table:
     3.8ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/multiverse amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu hirsute/multiverse i386 Packages

Trying to install ttf-mscorefonts-installer gives the error "The following packages have unmet dependencies:
 update-notifier-common : Depends: update-manager-core (>= 1:17.04.2) but 1.0.0~1630504302~21.04~c43efce is to be installed"

sudo apt install ttf-mscorefonts-installer

install ttf-mscorefonts-installer

Tried to install/reinstall update-notifier-common, update-notifier, update-manager-core nothing seemed to help.

**Comment by mmstick** [comment] 2021-09-09 18:51
Duplicate of #1901

**Closed by mmstick** 2021-09-09 18:51 UTC
