### ISSUE TITLE
Window tiling malfunctions when another tab of Terminal is added

### ISSUE THREAD

**Issue by teverus** [pop-os/pop#1207] opened 2020-08-28 12:20 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-os@pop-os:~$ apt policy $PACKAGE NAME
N: Unable to locate package NAME

**Issue/Bug Description:**
Window tiling malfunctions when another tab of Terminal is added
![Screenshot from 2020-08-28 12-19-11](https://user-images.githubusercontent.com/62369371/91560083-bf8eec80-e928-11ea-887c-eb92810dd397.png)

**Steps to reproduce (if you know):**
1 - Enable window tiling
2 - Open Firefox
3 - Open Terminal
4 - Add another tab in Terminal

**Expected behavior:**
Windows height stays the same

**Actual behavior:**
Terminal window height becomes somewhat shorter

**Other Notes:**
Terminal window height doesn't return to "normal" even after the second tab is closed :( So, if I want to use window tiling properly, I should be using just one tab of Terminal

**Comment by mmstick** [comment] 2020-09-06 05:34
Feature of GNOME Terminal. All dimensions must be increments of a certain amount of pixels. Not negotiable at this time, since any attempt to ignore WM_HINTs causes some rendering glitches and instability.

Duplicate of https://github.com/pop-os/shell/issues/85

**Closed by mmstick** 2020-09-06 05:34 UTC
