### ISSUE TITLE
Laptop not powering off after shutdown

### ISSUE THREAD

**Issue by groomit** [pop-os/pop#1653] opened 2021-04-18 09:52 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 

**Issue/Bug Description:**
Laptop is not powering off after shutdown using the shutdown system menu. Screen blanks but power LED and fans stay on. Only a hard-off (keeping powerbutton pressed for a few seconds) works then. When running `shtudown now` in terminal it is properly shutting down.
It used to work until recently. When booting into "old-kernel-config" with kernel 5.8 everything is working as intended. Also booting into the recovery console and running as live-system the shutdown is working as it should. So maybe it is kernel 5.11 related?

I'm on:
Clevo NV41ME
i7-1165G7
nvidia GTX 1650 TI
32 GB RAM - Samsung 3200
evo 980pro 1TB

**Steps to reproduce (if you know):**
Happens to me each and every time since recently. Try to shutdown using the system menu.

**Expected behavior:**
After the shutdown procedure the hardware should properly turn off.

**Other Notes:**
There is an old issue #530 . The suggested solution to uncomment cryptswap in some files did not solve the problem. I also posted there but I think this is a new issue. There are also some quite new comments from users with system76 hardware. So I decided to bring this topic to the top again.

**Comment by raymondgggg** [comment] 2021-04-18 22:26
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Issue/bug**
Laptop will not fully shutdown when going to the right and clicking on shutdown, on a Lemur pro, happens everytime I try to shut down.

**Comment by leviport** [comment] 2021-04-19 14:21
Duplicate of https://github.com/pop-os/linux/issues/41

**Closed by leviport** 2021-04-19 14:21 UTC
