### ISSUE TITLE
Thinkpad P15 Gen2 - Internal sound stopped working after kernel update to version 6.0.3

### ISSUE THREAD

**Issue by deemkeen** [pop-os/pop#2677] opened 2022-11-04 08:12 UTC
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

After the regular Pop!_OS kernel update to 6.0.3 the internal laptop (Thinkpad P15 Gen2)
sound stopped working. External sound devices still work.

**output from `dmesg | grep snd`**

[   13.256007] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[   13.257883] snd_hda_intel 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   13.258989] snd_hda_intel 0000:01:00.1: enabling device (0000 -> 0002)
[   13.259737] snd_hda_intel 0000:01:00.1: Disabling MSI
[   13.259744] snd_hda_intel 0000:01:00.1: Handle vga_switcheroo audio client
[   13.842632] snd_hda_codec_hdmi ehdaudio0D2: failed to create hda codec -12
[   13.842700] snd_hda_codec_hdmi ehdaudio0D2: ASoC: error at snd_soc_component_probe on ehdaudio0D2: -12
[   21.672304] usbcore: registered new interface driver snd-usb-audio

this imho directly related to the following kernel issue:

https://bugzilla.kernel.org/show_bug.cgi?id=216613

I guess the fix has to be backported to the current kernal

**Comment by leviport** [comment] 2022-11-04 15:11
Duplicate of https://github.com/pop-os/pop/issues/2487

6.0.6 is in testing. There are instructions in that issue for adding the pre-released kernel.

**Closed** 2022-11-04 15:12 UTC
