### ISSUE TITLE
Pop-os requires power cycle after lid close/suspend

### ISSUE THREAD

**Issue by JackDalba** [pop-os/pop#3202] opened 2024-01-06 01:09 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

I've got a System 76 Darter Pro that runs Pop-OS. I recently updated the firmware (Jan 2024) and now the machine requires me to manually hold the power button on the right side of the computer any time I want to wake it up. If I close the lid -- even for a moment -- it requires me to cycle power by pressing the button to get a response from the device. I've tried several fixes, inducing [this](https://github.com/pop-os/pop/issues/349) one and [this](https://github.com/pop-os/pop/issues/449) one, and doing a complete re-install of pop-OS, wiping the drive. I've also tried re-installing the nvidia drivers. The issue still persists despite all these tweaks. Does anyone know how to solve this problem? At this point I'm getting desperate, and have backed up all my files, so all options are on the table. 

**Steps to reproduce:**

Close lid or hit suspend in upper right corner menu. 
Wait for a sad, unresponsive darkness . . . 

**Expected behavior:**

Computer will require user to manually power cycle to get response. Hitting suspend in top corner sometimes causes lock screen to flicker, then goes to black, requiring manual power cycle. 

**Other Notes:**

I have a suspicion this is due to me interrupting the PC during a firmware update, though I can't be certain: I've had this happen once before, but was able to fix it by doing a refresh install of PopOS. That hasn't worked this time.

**Comment by leviport** [comment] 2024-01-08 14:19
I believe this is a duplicate of https://github.com/system76/firmware-open/issues/469

We are currently investigating the bug and will push a fix as soon as it's ready. In the meantime, there are also instructions for how to downgrade to the previous version in that thread.

**Closed by leviport** 2024-01-08 14:19 UTC

**Comment by JackDalba** [comment] 2024-01-08 20:24
That worked like a charm. Thanks!
