### ISSUE TITLE
"Dummy Output" as the audio output.

### ISSUE THREAD

**Issue by gray380** [pop-os/pop#2679] opened 2022-11-04 10:34 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 

**Issue/Bug Description:**
After recent system updates I've "lost" built-in audio.
"Dummy Output" as the audio output.

```
inxi -A
Audio:
  Device-1: Intel Tiger Lake-LP Smart Sound Audio
    driver: sof-audio-pci-intel-tgl
  Sound Server-1: ALSA v: k6.0.3-76060003-generic running: yes
  Sound Server-2: PipeWire v: 0.3.59 running: yes

lspci -nnk | grep -A2 Audio
00:1f.3 Multimedia audio controller [0401]: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller [8086:a0c8] (rev 20)
	Subsystem: Dell Tiger Lake-LP Smart Sound Technology Audio Controller [1028:0a7c]
	Kernel driver in use: sof-audio-pci-intel-tgl
	Kernel modules: snd_hda_intel, snd_sof_pci_intel_tgl

uname -r
6.0.3-76060003-generic
```

```
systemctl --user status pipewire
Started PipeWire Multimedia Service.
  mod.rt: RTKit error: org.freedesktop.DBus.Error.InvalidArgs
  mod.rt: could not set nice-level to -11: input-output error
```

**Expected behavior:**

Buit-in audio works

**Other Notes:**

USB headphones have no issues by the way.
Solution from the https://support.system76.com/articles/audio/ does not help.

**Comment by leviport** [comment] 2022-11-04 14:57
I think this is a duplicate of https://github.com/pop-os/pop/issues/2487. Can reopen if I'm mistaken.

**Closed by leviport** 2022-11-04 14:57 UTC
