### ISSUE TITLE
21.04 : broken installer

### ISSUE THREAD

**Issue by Gogny** [pop-os/pop#1752] opened 2021-06-30 00:49 UTC
**Distribution (run `cat /etc/os-release`):**
 the 21.04 release iso available on system76 website
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
I would love to know !
EDIT : mdadm deamon or something related to my 2 hard disks in RAID 1. Once unplugged, it works.

**Issue/Bug Description:**
When booting the live usb, gnome desktop appears, it's functionnal. After a few seconds it is replace by the lines from the booting of the live usb and some commands are running.

I would like the login credentials of the installer to access tty shell and restart gnome !

**Steps to reproduce (if you know):**

**Expected behavior:**
The Gnome desktop continues to be usable to install Pop!_OS 

**Other Notes:**

**Comment by davenavas** [comment] 2021-06-30 12:23
I have the same problem, I'm using the Nvidia graphics image version 5. I tried removing the ssd and see if it boots that way, and no luck.
My usb live image boots and loads normally. After a few seconds the interface disappears and i get this
![IMG_20210630_071825](https://user-images.githubusercontent.com/9887973/123959466-d00e5a00-d973-11eb-96b3-739db9eefdc6.jpg)
I'm trying to fresh install in my PC.
When i upgraded from 20.04 i ended up with a nasty problem that doesn't allow me to install with apt

**Comment by Gogny** [comment] 2021-06-30 12:49
You may try to unplug your graphic card, install with onboard graphics and then plug back your graphic card.
You will be able to go in the pop!_shop and download your drivers, at least that was working with my GT730.
Then, to switch to your graphic card, if I remember correctly there is a UI.

**Comment by davenavas** [comment] 2021-06-30 13:11
Well I tried removing the graphics card and installing with the other iso, for not Nvidia graphics and it happens again. Bummer

**Comment by davenavas** [comment] 2021-06-30 13:13
Well I tried removing the graphics card and installing with the other iso, for not Nvidia graphics and it happens again. Bummer
![IMG_20210630_081020](https://user-images.githubusercontent.com/9887973/123966415-07ccd000-d97b-11eb-91ec-a5b12e8cead0.jpg)

**Comment by Gogny** [comment] 2021-06-30 13:18
Well, at this point unplug everything... I also unplugged ethernet the time it worked...
Along with my 2nd monitor

**Comment by jacobgkau** [comment] 2021-06-30 13:21
Since it worked after you unplugged Ethernet, I believe this is a duplicate of https://github.com/pop-os/beta/issues/153. I'm closing this as a duplicate so we can keep better track of the issue in a single location.

**Closed by jacobgkau** 2021-06-30 13:21 UTC

**Comment by Gogny** [comment] 2021-06-30 13:23
eeeeeehhhhh... I unplugged several things at the same time, It didn't have time to investigate it was 2:00AM in France...
It may not be the ethernet cable.

**Comment by davenavas** [comment] 2021-06-30 13:23
Really?

> Since it worked after you unplugged Ethernet, I believe this is a duplicate of [pop-os/beta#153](https://github.com/pop-os/beta/issues/153). I'm closing this as a duplicate so we can keep better track of the issue in a single location.

What a dick

**Comment by jacobgkau** [comment] 2021-06-30 13:25
There is a known issue with Ethernet causing this problem, there is no reason to believe it was anything else at this point. If you investigate further and find a different root cause, the issue can be re-opened.

> What a dick

@davenavas There is no need for that kind of language here, please be civilized.

**Comment by Gogny** [comment] 2021-06-30 13:28
@jacobgkau I think you're right. Thank you !
@davenavas I hope it wasn't towards me, the translation in French is quite insulting...
Have a good day
