### ISSUE TITLE
Failed to install nvidia-driver-440

### ISSUE THREAD

**Issue by Yuri6037** [pop-os/pop#1165] opened 2020-07-28 09:35 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Not applicable.

**Issue/Bug Description:**
This morning when running my workstation I got an update popup for NVIDIA driver version 440. However for some reasons the driver cannot be updated:

```
The following packages have unmet dependencies:
  nvidia-driver-440: Depends: xserver-xorg-video-nvidia-440 (= 440.100-1pop1~1593619752~20.04~c73bf6e) but it is not going to be installed
```

**Steps to reproduce (if you know):**
Not applicable just a standard update popup/notification from the Pop Shop.

**Expected behavior:**
The package should update properly.

**Other Notes:**
I'm not running System 76 hardware. The hardware specs for my workstation are as follows:
- Asus Motherboard P9X79 (with non default BIOS, updated from official Asus BIOS in order to allow computer to reboot without instant shut down).
- Intel Core i7 3.7 Ghz 4 cores 8 threads (4th generation, LGA2011).
- NVIDIA GTX 650 Ti DirectCU 2 2Gb VRAM (from Asus).
- 24Gb RAM (DDR3 DIMM, some are 1600MT/S some are slower and some are faster. In other words I just put all kinds of DDR3 RAM sticks we had in various other dead computers).

**Comment by jacobgkau** [comment] 2020-07-28 13:55
First and foremost, this is not a support forum. System76 customers can [contact support](https://support.system76.com/) for technical assistance. Otherwise, you should ask on [Mattermost](https://chat.pop-os.org/) or [Reddit](https://www.reddit.com/r/pop_os/) if you have an issue that is specific to your own machine (i.e. not a reproducible issue.)

We have not released any updates to the NVIDIA driver for [27 days](https://github.com/pop-os/nvidia-graphics-drivers/commit/c73bf6e5a3f3d4165bdb80846d4d333781cc892d). It looks like you have a package management issue on your machine. I would recommend running the following six commands from our [support article](https://support.system76.com/articles/package-manager-pop/) about package manager issues:

```
sudo apt clean
sudo apt update
sudo dpkg --configure -a
sudo apt install -f
sudo apt full-upgrade
sudo apt autoremove --purge
```

I would also recommend checking what version of `xserver-xorg-video-nvidia-440` is available, and why the correct version is not able to be installed:

```
apt policy xserver-xorg-video-nvidia-440
sudo apt install xserver-xorg-video-nvidia-440=440.100-1pop1~1593619752~20.04~c73bf6e
```

**Comment by Yuri6037** [comment] 2020-07-28 14:32
Thank you. I throught I could just post this bug here as there was a bug template. Maybe you could put some kind of information when writing bugs that we should first contact by email or something else.

I ran your 6 commands and the first 5 did not produce any output. The last one (autoremove removed one package libnvidia-common-440*).

For some reasons the xserver-xorg-video-nvidia-440 was not installed at all. After running apt install the Pop Shop update tool succeeded to update the NVIDIA driver.

However there's still something strange: libnvidia-common-440-server libnvidia-extra-440-server are marked as not needed by apt autoremove, is that normal considering I have a NVIDIA GPU?
If that's abnormal then I think know what caused this problem in the first place: the fact that I run an autoremove after uninstalling certain apps that I no longer need or that I'm making tests with. Could it be that for some reasons apt found that NVIDIA was no longer needed?

**Comment by leviport** [comment] 2020-07-28 15:15
Bug reports and technical assistance requests are two distinctly different things, but they can look similar at times. The distinguishing factor is usually giving steps for a tester to reproduce the issue. Some preliminary investigation into the bug is also helpful, as it gives testers and engineers more of a lead on the actual behavior. We do very much appreciate bug reports, so please feel free to post them. If it's just something that broke or stopped working, however, it's probably best to start by seeking assistance, then reporting a bug once you've confirmed it's a bug and not just a random breakage.

In this case, I believe what you ran into was a bug that was fixed on Friday: https://github.com/pop-os/shop/pull/206

Using `apt autoremove` at this time is very unlikely to delete anything that your system needs to keep working properly, so I would just go ahead and run it.

**Closed by leviport** 2020-07-28 15:15 UTC

**Comment by Yuri6037** [comment] 2020-07-28 16:23
Thank you, I see.

**Comment by Yuri6037** [comment] 2020-08-08 10:51
Same bug appeared again today 08/08/2020:

```
The following packages have unmet dependencies:
  nvidia-driver-440: Depends: xserver-xorg-video-nvidia-440 (= 440.100-1pop1~1593619752~20.04~c73bf6e) but it is not going to be installed
```
