### ISSUE TITLE
Wireless mouse usb device not detecting 

### ISSUE THREAD

**Issue by bhanuprasad1999** [pop-os/pop#3417] opened 2024-12-12 01:18 UTC
I'm also facing similar issue. I was trying to connect wireless mouse dongle on usb, it is not detecting. some times it worked on the same system when inserted pendrive and removed inserted wireless mouse dongle. Again once I restart the system, it wireless dongle on usb haven't detected.

what are the things I tried:
* Inserting on usb 3.0, 2.0 usb slots
* inserting with some other usb drives and tried again inserting the wireless dongle sometimes worked.
I'm using pop os   22.04 LTS
GNOME version : 42.9
OS Type : 64

_Originally posted by @bhanuprasad1999 in https://github.com/pop-os/pop/issues/1475#issuecomment-2537532935_

**Comment by leviport** [comment] 2024-12-12 14:52
Duplicate of https://github.com/pop-os/pop/issues/1475. Please don't open duplicate issues.

This is more of a hardware-specific tech support question anyway, and that kind of thing fits better in Pop chat: https://chat.pop-os.org/pop-os

**Closed by leviport** 2024-12-12 14:52 UTC
