### ISSUE TITLE
Alt Tab not showing Chrome window in application mode

### ISSUE THREAD

**Issue by hanhpv** [pop-os/pop#1988] opened 2021-11-09 02:54 UTC
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**Issue/Bug Description:**
Chrome website running in application mode (in a separate window) not showing in Alt Tab.

**Steps to reproduce (if you know):**
* Create shortcut for https://to-do.live.com/ in Chrome (in Settings > More tools > Create shortcut... > Open as window)
* Open Todos app by desktop shortcut, it should be running in a separate Chrome window.
* Open Chrome browser normally
* Press Alt Tab to switch between windows. Only one Chrome window is showing, depends on which window was last active.

**Expected behavior:**
Both Chrome browser and Chrome application showing in Alt Tab.

**Screenshots:**
Both Chrome and To Do app (created via Chrome shortcut) are running:

![Screenshot from 2021-11-09 09-40-04](https://user-images.githubusercontent.com/5069672/140851906-226b4494-383c-4f17-a6f8-958df96b1013.png)

Alt Tab showing only Chrome:
![Screenshot from 2021-11-09 09-53-30](https://user-images.githubusercontent.com/5069672/140853353-33f1d23a-3c3f-4544-872b-a86af6697b68.png)

**Comment by jacobgkau** [comment] 2021-11-09 15:32
Thank you for the report. I'm closing this as a duplicate of https://github.com/pop-os/shell/issues/1067.

**Closed by jacobgkau** 2021-11-09 15:32 UTC
