### ISSUE TITLE
Favorites Bar doesn't scale with icons

### ISSUE THREAD

**Issue by McPaulchen** [pop-os/pop#257] opened 2018-05-03 17:03 UTC
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
GNOME Desktop Activities Overview

**Issue/Bug Description**
The icons on the favorite bar don't scale, the 13th item is placed behind the 'all applications' button.

**Steps to reproduce (if you know)**
Press Super or your preferred way to access the Activities Overview and add more than 13 items to the favorite bar.

**Expected behavior**
Scaling of the icons.

**Other Notes**

**Comment by brs17** [comment] 2018-05-06 21:54
@McPaulchen thank you for filing this issue. This seems to be a duplicate of https://github.com/pop-os/gnome-shell-theme/issues/23. Feel free to follow and contribute as necessary to that issue.

**Closed by brs17** 2018-05-06 21:54 UTC
