### ISSUE TITLE
Is there a netboot image for PopOS?

### ISSUE THREAD

**Issue by Jieiku** [pop-os/pop#2047] opened 2021-12-09 07:34 UTC
I am a long time Ubuntu user, I have been thinking of trying something else for a couple years now.

Pop-OS looks really really good. I am wondering if there is a netboot image for it anywhere?

similar to this: http://cdimage.ubuntu.com/netboot/bionic/

With Ubuntu I would install via the netboot image and then I would install only the packages I want or need:

```
sudo apt update
sudo apt install software-properties-common -y
sudo apt update && sudo apt full-upgrade
sudo apt install xorg plasma-desktop plasma-nm plasma-workspace sddm dolphin konsole yakuake firefox
sudo reboot
```

**Comment by jacobgkau** [comment] 2021-12-09 22:04
No, there is not a netboot or minimal image at this time, only the main images for Intel/AMD and NVIDIA graphics.

We do try to keep the list of hard dependencies minimal in https://github.com/pop-os/desktop, so some default components can be removed if you don't use them (although components necessary to have the GNOME/Pop!_OS desktop installed and functional are currently required, even if you primarily use another DE.)

This may change in the future once https://github.com/pop-os/pop/issues/1916 is addressed.

**Comment by Jieiku** [comment] 2021-12-10 04:47
Thanks for the info, I appreciate it. the main reason I use netboot with ubuntu is because ubuntu-desktop or whatever the package is, comes bundled with a set of applications. Many of those applications I do not use.... which is why I use the netboot image.
I try not to have things installed that I do not use. I first ran into this years ago when I wanted to uninstall some package or another that comes with ubuntu. so I did for example sudo apt remove kate

and then a big wall of text appeared, this will remove ubuntu-desktop and ALLLL these other packages.... and im like no no no, dont do that. from that point forward I just use the netboot to avoid that situation.

if something is really a dependency of gnome then its fine.... but if its just part of the desktop package.... well I do not really care for that. It is very promosing that things may change. I am going to subscribe to the other #1916 so i can keep an eye on the status of that.

**Comment by jacobgkau** [comment] 2021-12-10 05:34
The minimal installation you're describing is not necessarily synonymous with "netboot." It would be perfectly possible to have a netboot image (minimal packages _on the installation image_) that simply downloads all the same gigabytes worth of packages as a normal installation when you install. So it sounds like what you're asking for is a minimal installation option more than a netboot (which is covered by the issue I linked.)

**Comment by Jieiku** [comment] 2021-12-10 05:45
very good point! yes I am asking for a bare bones minimal installation, enough to boot to a terminal! I am super excited about trying this once PopOS has some sort of minimal install. Thanks again!

**Comment by jacobgkau** [comment] 2021-12-10 05:52
I'll close this issue since it's a duplicate of https://github.com/pop-os/pop/issues/1916.

**Closed by jacobgkau** 2021-12-10 05:52 UTC
