### ISSUE TITLE
Fullscreen doesn't work in tiling mode (20.04)

### ISSUE THREAD

**Issue by muhlinux** [pop-os/pop#971] opened 2020-05-04 10:02 UTC
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop shell?

**Issue/Bug Description:**
Going fullscreen with firefox, youtube or with a video player is buggy with "tiling windows" enabled

**Steps to reproduce (if you know):**
Enable "Tiling Windows" and watch a video fullscreen

**Expected behavior:**
Border to border video/application

**Other Notes:**

**Comment by aral** [comment] 2020-05-04 11:25
Duplicate of: #957

**Closed** 2020-05-04 13:10 UTC
