### ISSUE TITLE
Pop!_Shop shows a badge that 1 update is available but no updates can be found

### ISSUE THREAD

**Issue by jasongerard** [pop-os/pop#1109] opened 2020-06-26 14:44 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Pop!_Shop shows a badge that 1 update is available but no updates can be found. 

apt shows nothing to be updated. 
```
apt list --upgradeable
Listing... Done
```

**Steps to reproduce (if you know):**

**Expected behavior:**
The dock badge should not be displayed. The "Installed" tab should not had a badge indicating 1 update available when there are no updates to install.

**Other Notes:**
Computer is a System76 Lemur Pro that arrived the day 20.04 was released. Upgrade was done the next day through the UI popup.

**Comment by leviport** [comment] 2020-06-26 14:48
Duplicate of https://github.com/pop-os/shop/issues/198

**Closed by leviport** 2020-06-26 14:48 UTC
