### ISSUE TITLE
Desktop Right Click Context Menu became Transparent on installing Gnome Tweak tool

### ISSUE THREAD

**Issue by ssen8** [pop-os/pop#434] opened 2019-02-11 05:48 UTC
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 18.04 LTS
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
$ apt policy gnome-tweak-tool 
 
 gnome-tweak-tool:
  Installed: (none)
  Candidate: 3.28.1-1
  Version table:
     3.28.1-1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu bionic/universe i386 Packages

**Issue/Bug Description:**
  Desktop Right Click Context Menu became Transparent on installing Gnome Tweak tool

**Steps to reproduce (if you know):**
  install all updates of the OS - ( apt update && apt upgrade && apt dist-upgrade )
  install gnome tweak tool
  Under appearance > theme, set "applications" to Pop / Pop-dark / Pop-light OR any other Pop theme
  The moment its set or changed from one to another, the right click context menu of desktop becomes 
  transparent.

**Expected behavior:**
   The color of right click context menu should remain the same color as that of one selected under 
   "Applications"

**Other Notes:**
   Screenshot here - https://i.paste.pics/4QJ3O.png

**Comment by brs17** [comment] 2019-02-11 15:03
This is a duplicate of https://github.com/pop-os/gtk-theme/issues/272. Feel free to add additional information there.

**Closed by brs17** 2019-02-11 15:03 UTC

**Comment by deejay2** [comment] 2019-02-15 14:24
Same issue here... :(

**Comment by cata0309** [comment] 2019-02-19 13:01
It has nothing to do with Gnome Tweaks tool. It's all about the Pop Os theme
