### ISSUE TITLE
Bug: Clock and battery percentage freezes in full screen - Pop!_OS 20.10

### ISSUE THREAD

**Issue by itsmordecai** [pop-os/pop#1384] opened 2020-11-11 10:04 UTC
**Distribution (run cat /etc/os-release):**
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

```
**Issue/Bug Description:**
As mentioned by @r-murmu in #1375, when full screen is opened on any application that facilitates this, the clock in the top bar freezes but this is not only restricted to the clock but also the battery percentage. To view the correct battery percentage, one has to click on the system status area in order to view the correct percentage in the dropdown. I believe this may also happen with anything that has changing values in the top bar area.

**Steps to reproduce :** 
Open YouTube 
Play a video of choice in full screen 
or locally open a video player such as VLC and play any local video 

The time will be behind by the length of the video, or simply it will be frozen to when you started the video
The battery percentage will also be inaccurate depending on power consumption and length of your video

**Expected behaviour:** 
The time and battery percentage should be accurate after exiting fullscreen 

**Other Notes:** 
This bug resolves itself after a few minutes. 
The issue started after updating to 20.10 from 20.04, not sure if it's related but seems like

**Comment by leviport** [comment] 2020-11-11 15:06
Is this not a duplicate of https://github.com/pop-os/pop/issues/1375 as you mentioned? I can reopen this if I'm mistaken, but having two open issues for the same bug is not preferable.

**Closed by leviport** 2020-11-11 15:06 UTC

**Comment by r-murmu** [comment] 2020-11-11 15:39
yes this is a duplicate of #1375

**Comment by lowban** [comment] 2020-11-20 09:29
Both seems closed but this is still an issue on my machine.
