### ISSUE TITLE
Firefox window randomly blurring

### ISSUE THREAD

**Issue by marksumm** [pop-os/pop#1210] opened 2020-09-01 07:24 UTC
**Distribution (run `cat /etc/os-release`):**
 
```
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
firefox:
  Installed: 80.0+build2-0ubuntu0.20.04.1
  Candidate: 80.0+build2-0ubuntu0.20.04.1
  Version table:
 *** 80.0+build2-0ubuntu0.20.04.1 500
        500 http://us.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     75.0+build3-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**Issue/Bug Description:**

Entire browser window randomly blurs and then returns to normal.

**Steps to reproduce (if you know):**

Happens randomly when switching tabs.  It seems to recover when the window is dragged.

**Expected behavior:**

Browser window displays normally.

**Other Notes:**

This has nothing to do with fractional scaling, which is disabled.  It was also happening with the previous Firefox version.

**Comment by marksumm** [comment] 2020-09-05 19:45
https://www.reddit.com/r/pop_os/comments/gd6qy9/on_2004_temporary_blurry_text_in_windows/

**Comment by mmstick** [comment] 2020-09-06 05:18
Disabling animations fixes it.

Duplicate of https://github.com/pop-os/shell/issues/457

**Closed by mmstick** 2020-09-06 05:18 UTC

**Comment by marksumm** [comment] 2020-09-13 08:59
No, it really doesn't.  Also, I don't have window tiling enabled either.

**Comment by marksumm** [comment] 2020-09-27 16:20
Seems much happier without "Snap to Grid (Floating Mode)" enabled in Pop shell extension settings.
