### ISSUE TITLE
pop-upgrade und FirmwareManager.Notify using 16% CPU with multiple processes

### ISSUE THREAD

**Issue by qwertele** [pop-os/pop#1792] opened 2021-07-06 17:54 UTC
**Distribution (run `cat /etc/os-release`):**

 $ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

$ apt policy pop-upgrade
pop-upgrade:
  Installed: 1.0.0~1625268913~20.10~b7524b6
  Candidate: 1.0.0~1625268913~20.10~b7524b6
  Version table:
 *** 1.0.0~1625268913~20.10~b7524b6 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status

$ apt policy firmware-manager-notify
firmware-manager-notify:
  Installed: 0.1.2~1622314143~20.10~61fb022
  Candidate: 0.1.2~1622314143~20.10~61fb022
  Version table:
 *** 0.1.2~1622314143~20.10~61fb022 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

"/usr/bin/pop-upgrade release check" is running with 3 processes, each using 16% CPU.
"/usr/bin/com.system76.FirmwareManager.Notify" is running with 2 processes, each using 16% CPU.

They are not stopping or doing anything actively that i can see, just in the background, hogging cpu.

**Steps to reproduce (if you know):**
updated:
Found out how to reproduce:
It has to do with logging out & in. On first start of the laptop, everything is fine. If i logout and login again, the processes start with high cpu consumption (up to 28%), and then drop and stay at 16%. That persists through multiple logouts.
I have the impression that repeated logouts/-ins have a chance to add more processes, but im not sure. It looks like after the first logout/-in there are always 2 "pop-upgrade release check" and 1 firmware notify. Repeated logins can increase that number up to 3 & 2, although on one occasion all processes stopped using 16% cpu, and it was fine again.

**Expected behavior:**

Run after boot or login, let me know if there are updates (which there are in both instances, as it told me so), quit process after i dismissed the notifications.

**Other Notes:**

**Comment by qwertele** [comment] 2021-07-07 06:58
Right now the processes are not taking up any CPU... Weird.
It has happened multiple times in the past though, so it definitly wasnt a one time thing.

I will try and see if i can pinpoint it a bit more. Not too optimistic though, didnt notice anything yet in the past days.

**Comment by qwertele** [comment] 2021-07-07 08:53
Found out how to reproduce:
It has to do with logging out & in. On first start of the laptop, everything is fine. If i logout and login again, the processes start with high cpu consumption (up to 28%), and then drop and stay at 16%. That persists through multiple logouts.
I have the impression that repeated logouts/-ins have a chance to add more processes, but im not sure. It looks like after the first logout/-in there are always 2 "pop-upgrade release check" and 1 firmware notify. Repeated logins can increase that number up to 3 & 2, although on one occasion all processes stopped using 16% cpu, and it was fine again.

**Comment by ids1024** [comment] 2021-07-07 20:14
I'm able to reproduce the issue with more `pop-upgrade` processes spawning on logout/login, and taking too much CPU on 20.10.

**Comment by ids1024** [comment] 2021-07-08 16:59
Seems to happen on logout, without requiring a login. It looks like `pop-upgrade` is intercepting signal handlers, but the event loop isn't being run while it's waiting for the notification to be opened. So I guess that needs to be changed in one way or another so it will terminate on logout.

**Comment by ids1024** [comment] 2021-07-08 20:59
The CPU usage is apparently due to a zbus issue that was fixed in https://gitlab.freedesktop.org/dbus/zbus/-/merge_requests/254.

**Comment by jacobgkau** [comment] 2021-07-09 17:31
Fixed by https://github.com/pop-os/upgrade/pull/190 and https://github.com/pop-os/firmware-manager/pull/106.

**Closed by jacobgkau** 2021-07-09 17:31 UTC
Labels: bug, confirmed
