### ISSUE TITLE
Power off/restart buttons on login screen not working

### ISSUE THREAD

**Issue by pollaloca** [pop-os/pop#797] opened 2019-12-24 15:54 UTC
**Distribution (run `cat /etc/os-release`):**
 DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Pop!_OS 19.10"
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Power off/restart buttons on login screen not working

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by brs17** [comment] 2019-12-24 15:56
This is a duplicate of https://github.com/pop-os/pop/issues/708.

Also this issue has been resolved, so make sure to run updates and these buttons should then start working properly.

**Closed by brs17** 2019-12-24 15:56 UTC
