### ISSUE TITLE
On Enterprise Network.. every network printer is added automatically

### ISSUE THREAD

**Issue by AtomicCons** [pop-os/pop#125] opened 2018-01-26 15:22 UTC
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

```

**Issue/Bug Description**
When creating a machine or entering  my enterprise network, all local area network printers are added without permissions. When you have more than 200 printers, this is slightly a bad thing.

**Steps to reproduce (if you know)**
Connect to a network with shared printers. Printers will automatically be added.

**Expected behavior**
Expect no printers to be added automatically.

**Other Notes**
I am not sure if the protocol picks up all IP printers, or the printers being shared from a windows print server. 

Sorry about the empty post the first go round.

**Comment by brs17** [comment] 2018-04-06 01:55
Going to close this as it is a duplicate of #8 

There is a work around suggested in that issue although we have not decided if we will do anything with Pop!_OS specifically.

**Closed by brs17** 2018-04-06 01:55 UTC
Labels: upstream
