### ISSUE TITLE
Dock and Workspace indicator conflict

### ISSUE THREAD

**Issue by ProbablyNotLime** [pop-os/pop#1765] opened 2021-07-01 17:25 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
If the dock is aligned the left side the dock is on the top of the workspace indicator
![Screenshot from 2021-07-01 19-13-24](https://user-images.githubusercontent.com/78648178/124165425-0813bb00-daa2-11eb-8de8-8932845f4c65.png)

**Steps to reproduce (if you know):**
In settings switch to align the dock to the left side after open workspaces

Edit: Interesting. Sometimes it conflict sometimes not.

**Comment by jacobgkau** [comment] 2021-07-13 20:55
Duplicate of https://github.com/pop-os/cosmic/issues/63.

**Closed by jacobgkau** 2021-07-13 20:55 UTC
