### ISSUE TITLE
Sound not detected after updating

### ISSUE THREAD

**Issue by StormTrooper720** [pop-os/pop#2694] opened 2022-11-13 16:37 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
While installing pop os, on the live usb I checked to make sure that the internal sound works because I have had issues in the past on my desktop. The sound worked fine until after pop os installed and updated, now it shows "dummy output". I have tried all steps on the `support.system76.com/articles/audio/` to no avail. On the live usb the sound shows up as "Tiger Lake-LP Smart Sound Technology Audio Controller". `pavucontrol` shows the device, but only for the audio/mic port.

**Steps to reproduce (if you know):**

**Expected behavior:**
Sound card to show up

**Other Notes:**
I don't have much experience with linux commands and how to figure out the reason why. But I think it might be because the kernel updated from version 5. something to 6.0.6

**Comment by leviport** [comment] 2022-11-14 15:13
I believe this is a duplicate of https://github.com/pop-os/pop/issues/2487. This can be reopened if I'm mistaken.

**Closed by leviport** 2022-11-14 15:13 UTC
