### ISSUE TITLE
When pop-os21.04 is installed to configure the system, the installation program will automatically exit and the installation fails

### ISSUE THREAD

**Issue by Yakumo-Yukari** [pop-os/pop#1839] opened 2021-07-30 02:19 UTC

**Comment by jacobgkau** [comment] 2021-07-30 14:11
Please provide more information about the issue.

- What language are you installing in? If you're changing the language or keyboard layout settings, then this could be a duplicate of https://github.com/pop-os/installer/issues/190 or https://github.com/pop-os/installer/issues/192.
- What partitioning scheme are you using?
- What hardware are you using?
- Do you have any output in `/tmp/installer.log`?
- What output do you get if you run the installer from a terminal with `pkexec io.elementary.installer` and then recreate the issue?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by Yakumo-Yukari** [comment] 2021-07-30 23:49
> Please provide more information about the issue.
> 
> * What language are you installing in? If you're changing the language or keyboard layout settings, then this could be a duplicate of [Installer quits without warning if installing czech language installer#190](https://github.com/pop-os/installer/issues/190) or [Installer crashes when "generating locales" installer#192](https://github.com/pop-os/installer/issues/192).
> * What partitioning scheme are you using?
> * What hardware are you using?
> * Do you have any output in ?`/tmp/installer.log`
> * What output do you get if you run the installer from a terminal with  and then recreate the issue?`pkexec io.elementary.installer`
> 
> System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

Mounting method：Erase and Install
Language: Chinese
The installer exits without warning when configuring the system

**Closed** 2021-08-01 02:54 UTC
Labels: needs more info
