### ISSUE TITLE
Firefix not opening properly

### ISSUE THREAD

**Issue by BBBalls** [pop-os/pop#2231] opened 2022-02-24 04:17 UTC
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10" 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

firefox:
  Installed: 97.0+build2-0ubuntu0.21.10.1
  Candidate: 97.0+build2-0ubuntu0.21.10.1
  Version table:
 *** 97.0+build2-0ubuntu0.21.10.1 500
        500 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu impish-updates/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

When opening Firefox it does not always render properly. Only a kind of frame that duplicates the desktop background appears. It is not possible to interact with the frame, but it disappears when Firefox is closed via the dock. Firefox will open normally after several attempts.

**Steps to reproduce (if you know):**

Open Firefox.

**Expected behavior:**

Firefox open normally.

**Other Notes:**

This is happening with Librewolf as well

librewolf:
  Installed: 97.0.1-1
  Candidate: 97.0.1-1
  Version table:
 *** 97.0.1-1 500
        500 http://deb.librewolf.net impish/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by leviport** [comment] 2022-02-24 16:21
duplicate of https://github.com/pop-os/pop/issues/2182

**Closed by leviport** 2022-02-24 16:21 UTC
