### ISSUE TITLE
Suspend not working. Black screen output instead.

### ISSUE THREAD

**Issue by youngfinn** [pop-os/pop#3084] opened 2023-07-24 05:47 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
libreoffice7.5:
  Installed: 7.5.2.2-2
  Candidate: 7.5.2.2-2
  Version table:
 *** 7.5.2.2-2 100
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Laptop does not go to suspend. Only shows console with output (please check attached jpg). Only option is to turn it off via power button.

**Steps to reproduce (if you know):**
I think you have to run an application that uses the GPU. The following steps definitely reproduce the problem on my side:

1. Start LibreOffice Impress 7.5
2.  Go to suspend (via button or closing the lid, does not matter)
3.  --> Screen goes black and starts showing console output.

This also happens when Bluetooth and Wifi are deactivated. My guess is that it's GPU related. 

**Expected behavior:**
Go to suspend.

**Other Notes:**
Hardware: HP Spectre x360 15-inch with dedicated GPU NVidia Geforce 940mx (2017). 
NVidia driver 525

PopOS power settings are set to Nvidia Graphics.

Already did a full reinstall of the drivers which didn't help.

![suspend_output](https://github.com/pop-os/pop/assets/70367591/b0cc14b8-d91c-4e78-98ed-6952955b9af4)

**Comment by realKarthikNair** [comment] 2023-08-04 13:50
I don't have a dGPU and I still face the issue https://github.com/pop-os/pop/issues/3078

**Comment by bgrgv** [comment] 2023-10-02 21:18
Try https://github.com/pop-os/pop/issues/1368#issuecomment-1743780588 @realKarthikNair

**Comment by youngfinn** [comment] 2023-10-03 07:06
@bgrgv . The s2idle state was already set to deep. By the way, I can't reproduce the problem today. There probably have been a couple of updates since I opened up this issue, so I don't know if there maybe was a fix for my machine. 

I just opened up a lot of applications, including the above mentioned libreOffice and the laptop goes to sleep fine and can be woken up successfully aswell.

**Comment by youngfinn** [comment] 2023-10-03 07:22
OK sorry, I was wrong :D 

Just started another application (this time ParaView 5.7.0) and the problem is back. However, with ParaView 5.11.2, the problem is gone. The former is started via a binary from a folder and the latter is a flatpak.

Furthermore, I failed to mention that I changed my LibreOffice to the flatpak version as well! 

So maybe the non-flatpak stuff has something to do with it.

**Comment by bgrgv** [comment] 2023-10-03 08:46
> OK sorry, I was wrong :D
> 
> Just started another application (this time ParaView 5.7.0) and the problem is back. However, with ParaView 5.11.2, the problem is gone. The former is started via a binary from a folder and the latter is a flatpak.
> 
> Furthermore, I failed to mention that I changed my LibreOffice to the flatpak version as well!
> 
> So maybe the non-flatpak stuff has something to do with it. Maybe it's also just the newer versions of the software, as I use other non-flatpak software that doesn't keep my laptop from going to sleep.

Did you try running both update and upgrade as well?

**Comment by youngfinn** [comment] 2023-10-05 05:41
> > OK sorry, I was wrong :D
> > Just started another application (this time ParaView 5.7.0) and the problem is back. However, with ParaView 5.11.2, the problem is gone. The former is started via a binary from a folder and the latter is a flatpak.
> > Furthermore, I failed to mention that I changed my LibreOffice to the flatpak version as well!
> > So maybe the non-flatpak stuff has something to do with it. Maybe it's also just the newer versions of the software, as I use other non-flatpak software that doesn't keep my laptop from going to sleep.
> 
> Did you try running both update and upgrade as well?

Yes, I did. I'm gonna try the non-flatpak version of ParaView 5.11. as well now.

**Comment by realKarthikNair** [comment] 2023-10-06 10:53
@bgrgv still doesn't fix it... also worth mentioning that i no longer am using the same laptop yet the issue still persists

**Comment by realKarthikNair** [comment] 2023-10-06 11:09
Pop!_OS installation was fresh on my new machine but the only common ground between both of these machines are that they use AMD processors instead of Intel.... The former machine (Asus) from which I reported #3078  for the first time was using AMD Ryzen 5 4500U with no dedicated GPU and my current one (OMEN) is using Ryzen 7 7840HS with RTX 4060... 

Now I have 2 laptops with the exact same issue with Pop!_OS.... The only apparent working solution currently being disabling S3 sleep from BIOS and falling back to the inefficient Modern Standby mode (S0)

@mmstick in https://github.com/pop-os/pop/issues/3078#issuecomment-1634837591 stated that it is a hardware based issue but now I am using a laptop from a different OEM and nothing except having an AMD processor is common between these devices. I understand how open source works and neither am I capable of fixing the issue myself... But atleast acknowledge that this IS AN ISSUE WITH POP_OS instead of just narrowing it down to "specific niche hardware based issue thus cant fix" thingy since both WIndows and Fedora does wake from S3 mode I tested myself. 

I really am disappointed

Previous laptop motherboard/UEFI info 

```
karthik@cosmic:~$ sudo inxi -M
Machine:
  Type: Laptop System: ASUSTeK product: VivoBook_ASUSLaptop X421IAY_M413IA
    v: 1.0 
  Mobo: ASUSTeK model: X421IAY v: 1.0 
  UEFI: American Megatrends v: X421IAY.314 date: 05/24/2022
```

neofetch
```
karthik@cosmic:~$ neofetch
             /////////////                 karthik@cosmic
         /////////////////////             --------------
      ///////*767////////////////          OS: Pop!_OS 22.04 x86_64
    //////7676767676*//////////////        Host: VivoBook_ASUSLaptop X421IAY_M413IA 1.0
   /////76767//7676767//////////////       Kernel: 6.2.6-76060206-generic
  /////767676///*76767///////////////      Uptime: 4 mins
 ///////767676///76767.///7676*///////     Packages: 3308 (dpkg), 1 (flatpak)
/////////767676//76767///767676////////    Shell: bash 5.1.16
//////////76767676767////76767/////////    Resolution: 1920x1080 @ 60Hz
///////////76767676//////7676//////////    DE: GNOME 42.5
////////////,7676,///////767///////////    WM: Mutter (Wayland)
/////////////*7676///////76////////////    WM Theme: Pop-dark
///////////////7676////////////////////    Theme: Pop-dark [GTK2/3/4]
 ///////////////7676///767////////////     Icons: Numix-Circle [GTK2/3/4]
  //////////////////////'////////////      Font: Bahnschrift (11pt) [GTK2/3/4]
   //////.7676767676767676767,//////       Cursor: breeze (24px)
    /////767676767676767676767/////        Terminal: gnome-terminal-server
      ///////////////////////////          Terminal Font: JetBrains Mono (14pt)
         /////////////////////             CPU: AMD Ryzen 5 4500U (6) @ 4.011 GHz
             /////////////                 GPU: AMD Renoir
                                           Memory: 1.78 GiB / 7.18 GiB (24%)
                                           Disk (/): 88.36 GiB / 146 GiB (60%)
                                           Battery: 77% [Discharging]
                                           Locale: en_GB.UTF-8

                                           ████████████████████████
                                           ████████████████████████
```

New laptop motherboard/UEFI info:

```
karthik@cosmic:~$ sudo inxi -M
Machine:
  Type: Laptop System: HP product: OMEN by HP Gaming Laptop 16-xf0xxx
    v: Type1ProductConfigId 
  Mobo: HP model: 8BCA v: 77.39 UEFI: Insyde v: F.10
    date: 08/10/2023
```

New laptop neofetch:
```
karthik@cosmic:~$ neofetch
             /////////////                karthik@cosmic 
         /////////////////////            -------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: OMEN by HP Gaming Laptop 16-xf0xxx 
   /////76767//7676767//////////////      Kernel: 6.5.5-x64v3-xanmod1 
  /////767676///*76767///////////////     Uptime: 20 mins 
 ///////767676///76767.///7676*///////    Packages: 2280 (dpkg) 
/////////767676//76767///767676////////   Shell: bash 5.1.16 
//////////76767676767////76767/////////   Resolution: 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 42.5 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16) @ 5. 
    /////767676767676767676767/////       GPU: NVIDIA 01:00.0 NVIDIA Corporation Device 28a0 
      ///////////////////////////         GPU: AMD ATI 05:00.0 Device 15bf 
         /////////////////////            Memory: 2549MiB / 15172MiB 
             /////////////
                                                                  
```

**Comment by leviport** [comment] 2023-10-06 14:09
I believe this is a duplicate of https://github.com/pop-os/pop/issues/3078

**Closed** 2023-10-06 14:10 UTC
