### ISSUE TITLE
org.gnome.Shell.Screencast does not work

### ISSUE THREAD

**Issue by ianhundere** [pop-os/pop#2179] opened 2022-01-20 01:36 UTC
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
`gnome-shell-extension-easyscreencast` (i think?)

the issue is specific to `/usr/share/gnome-shell/org.gnome.Shell.Screencast`

**Issue/Bug Description:**
when running the shortcut to record video (super + shift + 5 for me) the orange/yellow record icon appears in the upper-right corner, but when you press the shortcut again to stop recording the recording never stops forcing you to kill the process. 
![image](https://user-images.githubusercontent.com/138915/150245784-e4cbd95e-8ef6-4005-887f-7678c90812a6.png)

the file is created under `/home/<user>/Videos` if you still have that specified in `.config/user-durs.dirs`, but nothing is ever written to the file, `0 Jan 19 20:22 'Screencast from 01-19-2022 08:22:23 PM.webm'`.

**Steps to reproduce (if you know):**
mentioned above.

**Expected behavior:**
press screencast shortcut and:
- play around and record you video
- press the shortcut once more
- the file / video is written
- the process for recording your screen is killed after 

**Other Notes:**
there's this issue, but i've tried removing `gnome-sushi` and it hasn't helped.

https://github.com/pop-os/pop/issues/1332

**Comment by faraonc** [comment] 2022-01-21 22:17
I have the same issue on my system. I was trying to figure out how to kill the process
```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```

**Comment by ianhundere** [comment] 2022-01-21 22:19
yah, that's how i kill it.

**Comment by keithfancher** [comment] 2024-02-24 22:33
Still an issue on PopOS 22.04, except for me the screen recording works *once* and then needs to be forced killed as above. I have the same yellow dot sitting in my top bar.

```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Comment by Christian3756** [comment] 2024-02-27 17:26
Same issue. 
Screencast will record once, then fail all subsequent times. Logging out, restart, or manually kill the  "/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shell.Screencast" allows it work for one more recording session. 

Screenshots works as expected.
Screencasts only affected.

journalctl:
 Feb 27 11:12:52 pop-os gnome-shell[11444]: Error starting screencast

PS aux:
 SNLsl 11:18   0:00 /usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shell.Screencast

!
![Screenshot from 2024-02-27 11-24-46](https://github.com/pop-os/pop/assets/10119173/3e46561b-1c9b-4770-bdf0-20c83ee19b19)

**Comment by jacobgkau** [comment] 2024-02-28 21:37
Thank you for the reports. This is a duplicate of https://github.com/pop-os/gnome-shell/issues/134. Since that one's in the correct repository, I'm closing this one. Feel free to add any pertinent discussion there (the issue is already known, so "same issue" doesn't move the issue forward unless you're providing more information about the cause or a potential fix).

**Closed by jacobgkau** 2024-02-28 21:37 UTC
