### ISSUE TITLE
Gedit Pop Dark and Pop Light themes oversized font with some HTML tags

### ISSUE THREAD

**Issue by gabrc52** [pop-os/pop#1500] opened 2021-01-20 22:01 UTC
**Distribution (run `cat /etc/os-release`):**
 
 Pop!_OS 20.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
pop-default-settings:
  Installed: 4.0.6~1607983973~20.10~225ebf2
  Candidate: 4.0.6~1607983973~20.10~225ebf2
  Version table:
 *** 4.0.6~1607983973~20.10~225ebf2 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

`<title>`, `<h1>`, `<h2>`, and related HTML tags make the font size massive (incredibly big to work with). It seems to be a bug with the stylesheet, and it doesn't seem intended since `<b>`, `<strong>`, `<i>` and `<em>` tags have no effect, and Markdown headers `# Title` don't make the text bigger, all of these things which would be a nice addition if implemented correctly.

![image](https://user-images.githubusercontent.com/24363938/105245525-9bca7e00-5b37-11eb-9220-a187a266aa5e.png)

**Steps to reproduce (if you know):**

1. Open Gedit
2. In "Preferences" > "Font and colors", make sure the theme is Pop Dark or Pop Light
3. Type `<title>blah<title>` in Gedit

**Expected behavior:**

Either:

1. `<title>`, `<h1>`, `<h2>` appear with the same font size as everything else, like with the other Gedit (`gtksourceview`) themes (the more straightforward and probably best solution, as it respects the way upstream GNOME intended).
2. `<title>`, `<h1>`, `<h2>` etc appear with a subtle bigger size (according to someone knowledgeable in design), but with almost the same size as everything else. Markdown headers appear in a style equivalent to that of HTML headers, and bolded and italicised in different markup languages appear bolded or italicised. (It would be a nice addition but I'd rather that's discussed and implemented in upstream GNOME if it were to be implemented).

**Other Notes:**

More info here: https://www.reddit.com/r/gnome/comments/ek96er/is_there_a_way_to_force_gedit_html_syntax/

**Comment by jacobgkau** [comment] 2021-01-26 23:47
This is a duplicate of https://github.com/pop-os/pop/issues/778.

**Closed by jacobgkau** 2021-01-26 23:47 UTC
