### ISSUE TITLE
WiFi driver patch

### ISSUE THREAD

**Issue by spirulin** [pop-os/pop#2000] opened 2021-11-13 15:24 UTC
**Distribution (run `cat /etc/os-release`):**
It's on all operating systems before they get 5.16 kernel.
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
rtw89

**Issue/Bug Description:**
So I got this brand new laptop with great specs but the WiFI card is still not supported and will be with kernel 5.16. Most likely pop 21.10 will ship with an older version.

**Steps to reproduce (if you know):**
Get laptop using Realtek 8852AE

**Expected behavior:**
WiFi to work out of the box.

**Other Notes:**
Here is a temporary fix until 5.16 kernel: https://github.com/lwfinger/rtw89

If you somehow manage to add a patch in your OS till the kernel hits your distro will be great.

**Comment by jacobgkau** [comment] 2021-11-15 16:19
Duplicate of https://github.com/pop-os/pop/issues/1834.

**Closed by jacobgkau** 2021-11-15 16:19 UTC
