### ISSUE TITLE
Condense multiple Pop-Shop entries for the same package into one entry

### ISSUE THREAD

**Issue by christianitus03** [pop-os/pop#1421] opened 2020-11-26 19:49 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-shop:
  Installed: 3.3.0pop0~1600965555~20.10~f37e26a
  Candidate: 3.3.0pop0~1600965555~20.10~f37e26a
  Version table:
 *** 3.3.0pop0~1600965555~20.10~f37e26a 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Multiple Pop-Shop entries for the same application, but different package formats. For example, seperate entries for .deb packages, flatpaks, etc for the same app.

**Steps to reproduce (if you know):**
Search for certain packages (for example, Claws mail); and see for yourself.

**Expected behavior:**
A single shop entry for each application, which has the option to install as a .deb or flatpak.

**Other Notes:**
I would be happy to compile and send a list of affected applications if it means this inconvenience can be resolved.

**Comment by jacobgkau** [comment] 2020-11-30 15:13
Duplicate of https://github.com/pop-os/shop/issues/203 and https://github.com/pop-os/shop/issues/157.

**Closed by jacobgkau** 2020-11-30 15:13 UTC
