### ISSUE TITLE
Can't boot unless plugged in

### ISSUE THREAD

**Issue by MEJacoby529** [pop-os/pop#1145] opened 2020-07-15 00:47 UTC
**Distribution (run `cat /etc/os-release`):**
20.04
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Dell 7530 which hangs endlessly on the Dell logo when unplugged and just on battery.

**Steps to reproduce (if you know):**
Turn off device, unplug device, try to restart.

**Expected behavior:**
Dell logo screen, hanging.

**Other Notes:**
I have the Quadro P2000 card; seems like the nVidia cards cause various issues. I first noticed this issue when I tried to switch to hybrid graphics. Perhaps the nVidia card issue -- if that's the issue -- is also making the laptop come away from sleep mode impossible, when not plugged in.

**Comment by leviport** [comment] 2020-07-15 14:10
Duplicate of https://github.com/pop-os/pop/issues/855

**Closed by leviport** 2020-07-15 14:10 UTC
