### ISSUE TITLE
Pop!_Shop always shows one item to install when all packages are updated.

### ISSUE THREAD

**Issue by jordonedavidson** [pop-os/pop#1494] opened 2021-01-20 01:39 UTC
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop!_Shop

**Issue/Bug Description:**
Pop!_Shop icon in the dock consistently shows one more item to install than exists. _i.e._ When there are 5 it shows 6, when all updates are installed it shows 1. 

This indicator is also incorrect in the app on the __Installed__ tab

**Steps to reproduce (if you know):**
Open Pop!_Shop and go to the installed tab. Wait for search to complete. The indicator will be one more than the number of items to update in the listing. After `Update All` the indicator will show 1.

Run `sudo apt update` in the terminal and it will report `All packages are up to date`.

**Expected behavior:**
Counter indicator will disappear from __Installed__ tab in the app and from the icon in the dock.

**Other Notes:**
This has also been the case off and on for 3 months on my 20.10 VM on my work Mac (VmWare on MacOSX Catalina).

It has just showed up in the last day or so on my new Galago Pro (galp5).
![OneExtraUpdate](https://user-images.githubusercontent.com/5767866/105115173-bdc3f200-5a9e-11eb-8e12-b622ae49b236.png)

**Comment by leviport** [comment] 2021-01-20 14:46
I believe this is a duplicate of https://github.com/pop-os/shop/issues/198

Let me know if I'm mistaken and I can reopen this issue.

**Closed by leviport** 2021-01-20 14:46 UTC

**Comment by jordonedavidson** [comment] 2021-01-21 00:26
@leviport Confirmed. `flatpak update` showed one package. Updating that removed the indicator.

Closing as duplicate of pop-os/shop#198
