### ISSUE TITLE
OS installer crashes when choosing the Czech language 

### ISSUE THREAD

**Issue by sch3fr** [pop-os/pop#1707] opened 2021-05-19 16:04 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
don't know, sorry.

**Issue/Bug Description:**
The Pop os installer stops at "Configuring the system (75%)" when the language chosen during the first step of set up is Czech. It happens both in Oracle VM VirtualBox and on my ThinkPad T440s. I tried making the USB drive with Etcher and Rufus, but it doesn't seem change anything.

**Steps to reproduce (if you know):**
1. boot from live USB
2. on Select a language screen select čeština -> Česko (Czech)
3. on Rozložení klávesnice (Keyboard layout) select Czech -> výchozí (default) 

//I don't think this actually affects anything, since instalation in English with Czech keyboard layout finishes without any problems.

4. on Drive encryption chose Don't Encrypt
5. on Install screen select Clean install, choose your drive and press Vymazat a nainstalovat (Erase and install)

Now the instalation should go fine until it reaches the Konfiguruji systém (Configuring the system) phase. Then the isntaller closes itself.

**Expected behavior:**
The installation should complete.

**Other Notes:**
I hope this report is okay. This is my first time doing this and English is not my first language.

**Comment by leviport** [comment] 2021-05-19 16:08
Duplicate of https://github.com/pop-os/installer/issues/190

**Closed by leviport** 2021-05-19 16:08 UTC
