### ISSUE TITLE
Firmware Manager: Specified firmware is older than installed

### ISSUE THREAD

**Issue by wmutschl** [pop-os/pop#640] opened 2019-08-18 07:54 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Firmware Manager in Gnome Settings

**Issue/Bug Description:**
The firmware manager shows an update, but actually there is nothing (see running `sudo apt fwupdmgr get-updates`) I attach three screenshots with the bug.

![firmware](https://user-images.githubusercontent.com/36013296/63221760-02f33e80-c19e-11e9-9662-4088b3871b29.png)
![firmware1](https://user-images.githubusercontent.com/36013296/63221761-038bd500-c19e-11e9-99c8-4e866b3b5152.png)
![firmware3](https://user-images.githubusercontent.com/36013296/63221762-038bd500-c19e-11e9-9ec3-9949a6e180ed.png)

**Comment by wmutschl** [comment] 2019-08-18 07:55
Also running the application "Dell Command Update" on Windows on the same machine (dual boot) does not show any updates.

**Comment by mmstick** [comment] 2019-08-18 18:11
This is a duplicate of https://github.com/pop-os/firmware-manager/issues/45, which has been fixed.

**Closed by mmstick** 2019-08-18 18:11 UTC
