### ISSUE TITLE
kernel 5.15 causes zfs-dkms to fail to build

### ISSUE THREAD

**Issue by joeammond** [pop-os/pop#2029] opened 2021-12-02 19:46 UTC
**Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os 
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
linux-image-5.15.5-76051505-generic:
  Installed: 5.15.5-76051505.202111250933~1638201579~21.04~09f1aa7
  Candidate: 5.15.5-76051505.202111250933~1638201579~21.04~09f1aa7
  Version table:
 *** 5.15.5-76051505.202111250933~1638201579~21.04~09f1aa7 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status

zfs-dkms:
  Installed: 2.0.2-1ubuntu5.3
  Candidate: 2.0.2-1ubuntu5.3
  Version table:
 *** 2.0.2-1ubuntu5.3 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/universe i386 Packages
        100 /var/lib/dpkg/status
     2.0.2-1ubuntu5 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu hirsute/universe i386 Packages
```

**Issue/Bug Description:**

Installing kernel 5.15 causes zfs-dkms stop building:

```
Building initial module for 5.15.5-76051505-generic
configure: error: 
	*** None of the expected "iops->get_acl()" interfaces were detected.
	*** This may be because your kernel version is newer than what is
	*** supported, or you are using a patched custom kernel with
	*** incompatible modifications.
	***
	*** ZFS Version: zfs-2.0.2-1ubuntu5.3
	*** Compatible Kernels: 3.10 - 5.14
	
ERROR (dkms apport): kernel package linux-headers-5.15.5-76051505-generic is not supported
Error! Bad return status for module build on kernel: 5.15.5-76051505-generic (x86_64)
Consult /var/lib/dkms/zfs/2.0.2/build/make.log for more information.
dpkg: error processing package zfs-dkms (--configure):
 installed zfs-dkms package post-installation script subprocess returned error exit status 10
Processing triggers for initramfs-tools (0.139ubuntu3) ...
update-initramfs: Generating /boot/initrd.img-5.15.5-76051505-generic
cryptsetup: WARNING: Resume target cryptswap uses a key file
kernelstub.Config    : INFO     Looking for configuration...
kernelstub           : INFO     System information: 

    OS:..................Pop!_OS 21.04
    Root partition:....../dev/nvme0n1p3
    Root FS UUID:........ae222dd7-5779-4207-bb7b-868714ab2c57
    ESP Path:............/boot/efi
    ESP Partition:......./dev/nvme0n1p1
    ESP Partition #:.....1
    NVRAM entry #:.......-1
    Boot Variable #:.....0000
    Kernel Boot Options:.quiet loglevel=0 systemd.show_status=false splash
    Kernel Image Path:.../boot/vmlinuz-5.15.5-76051505-generic
    Initrd Image Path:.../boot/initrd.img-5.15.5-76051505-generic
    Force-overwrite:.....False

kernelstub.Installer : INFO     Copying Kernel into ESP
kernelstub.Installer : INFO     Copying initrd.img into ESP
kernelstub.Installer : INFO     Setting up loader.conf configuration
kernelstub.Installer : INFO     Making entry file for Pop!_OS
kernelstub.Installer : INFO     Backing up old kernel
kernelstub.Installer : INFO     Making entry file for Pop!_OS
Errors were encountered while processing:
 zfs-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Steps to reproduce (if you know):**

Install kernel 5.15. Attempt to install zfs-dkms

**Expected behavior:**

zfs-dkms builds OpenZFS kernel modules successfully.

**Other Notes:**

**Comment by jacobgkau** [comment] 2021-12-02 20:23
Thank you for the report. I'm closing this as a duplicate of https://github.com/pop-os/beta/issues/285, and moving that issue from the beta repo into the kernel repo.

**Closed by jacobgkau** 2021-12-02 20:23 UTC
