### ISSUE TITLE
nautilus export dialog bug

### ISSUE THREAD

**Issue by MustaphaAlioglou** [pop-os/pop#1581] opened 2021-03-13 13:19 UTC
**Issue/Bug Description:**
when i try to export some compressed files the dialog window doesnt show all the home folders and if i try to extract i can see that it did but it didnt somehow. because after the exportation i cant see the folder (its not a dot folder). but if i try to export again the folder its there.

**Steps to reproduce (if you know):**
download godot . not the c# version. try to extract to desktop

**Expected behavior:**
it doesnt show all home directories

**Comment by bflanagin** [comment] 2021-03-15 12:23
@MustaphaAlioglou: I'm not seeing the issue on my end. Picture for reference: 

![Screenshot from 2021-03-15 07-19-33](https://user-images.githubusercontent.com/10382037/111152608-e6c4a880-855e-11eb-80e2-bb24ceb80518.png)

Can you get some screenshots of the issue?

**Comment by MustaphaAlioglou** [comment] 2021-03-15 12:25
let me install popos in a vm because i installed 20.10 cause it has a newer
file manager version.

**Comment by bflanagin** [comment] 2021-03-15 12:47
Ah, so what version of Pop!_OS where you using you saw the issue? Also, there isn't any reason for you to do the extra leg work if the issue is fixed in whatever version you're using. We can check the issue's validity on our end and fix it if we can replicate the problem.

**Comment by MustaphaAlioglou** [comment] 2021-03-15 13:15
i was using the 20.04 lts fully upgraded  and i tried to replicate 2 times
on vm and i succeeded but not i can't. it works fine. if it happens again i
will record a video.
Also do you know for how long the weather will be like this? personally i
removed it all together because its not that important but it looks bad.

**Comment by bflanagin** [comment] 2021-03-15 13:23
Here's hoping you don't have to make that video. As fars as Gnome Weather is concerned, the package pulled from Ubuntu so when they get an update we'll get an update. Beyond that we don't have much more information.

**Comment by MustaphaAlioglou** [comment] 2021-03-15 13:25
ok. i am stupid. i am pretty sure i was pressing recent instead of home. i
am going to kill my self, thank you

**Comment by MustaphaAlioglou** [comment] 2021-03-16 09:50
here is the bug.
[2021-03-16 11-4.zip](https://github.com/pop-os/pop/files/6147797/2021-03-16.11-4.zip)

**Closed** 2021-03-16 09:58 UTC

**Comment by MustaphaAlioglou** [comment] 2021-03-16 10:00
i recorded the bug btw. but  i just realised its probably because i use google chrome with firejail
