### ISSUE TITLE
21.04 - Problem with background or icons overlap in Application list

### ISSUE THREAD

**Issue by wellington1993** [pop-os/pop#1781] opened 2021-07-05 15:28 UTC
**Distribution (run `cat /etc/os-release`):**
```ini
DISTRIB_ID=Pop
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Pop!_OS 21.04"
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"

```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
- Gnome extensions... or Pop Shell/Cosmic or Themes. I don't know

**Issue/Bug Description:**
I probably did some mistake, now I when I go to list Applications, I see some overlap effect in applications icons when I scroll.

**Steps to reproduce (if you know):**
I don't know. When try to scroll in the Applications list.

**Expected behavior:**
No overlap effects in applications list. 

**Other Notes:**

https://user-images.githubusercontent.com/6920053/124489945-ebb89c80-dd87-11eb-9579-d7c3f1498591.mp4

**Comment by leviport** [comment] 2021-07-06 15:43
Duplicate of https://github.com/pop-os/cosmic/issues/96

This _should_ have been fixed with https://github.com/pop-os/cosmic/pull/112, so make sure you have the latest updates installed.

**Closed by leviport** 2021-07-06 15:43 UTC
