### ISSUE TITLE
Logging in after Lock sometimes breaks GNOME Shell

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#52] opened 2017-10-31 16:13 UTC
_From @RicardoEPRodrigues on July 21, 2017 1:2_

**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
    Distributor ID:	Ubuntu
    Description:	Ubuntu 17.04
    Release:	17.04
    Codename:	zesty

 * Related Application and/or Package Version - apt policy $PACKAGE NAME
    gnome-screensaver:
      Installed: (none)
      Candidate: 3.6.1-7ubuntu5
      Version table:
         3.6.1-7ubuntu5 500
            500 http://pt.archive.ubuntu.com/ubuntu zesty/main amd64 Packages
   gnome-shell:
     Installed: 3.24.2-0ubuntu0.1
     Candidate: 3.24.2-0ubuntu0.1
     Version table:
    *** 3.24.2-0ubuntu0.1 500
           500 http://pt.archive.ubuntu.com/ubuntu zesty-updates/universe amd64 Packages
           100 /var/lib/dpkg/status
        3.24.0-0ubuntu2 500
           500 http://pt.archive.ubuntu.com/ubuntu zesty/universe amd64 Packages
```

**Issue/Bug Description**

After not using my pc for a bit and it showing the lock screen, when I try logging in to my account it sometimes breaks the Shell.

In this case breaking means that the extensions are not loaded or I'm placed back at the login screen and logout of my account. 

**Steps to reproduce (if you know)**

1. Let the computer lock
2. Login
3. Sometimes it shows up with no extensions loaded.

**Expected behaviour**

At step 3 it should always load correctly. (I know this not very helpful)

**Other Notes**

I think there is a bug report on this for Ubuntu GNOME 17.04.

List of active extensions:

* Alternatetab
* Appfolders management extension
* Better Volume indicator
* Dash to dock
* Freon
* Native window placement
* Places status indicator
* Removable drive menu
* Screenshot tool
* Shelltile
* Sound input & output device chooser
* Suspend button
* Topicons plus
* User Themes
* Cpufreq

_Copied from original issue: pop-os/iso#54_

**Comment by isantop** [comment] 2017-10-31 16:13
_From @kylerchin on July 21, 2017 3:39_

hmmm.... thats sad.....

**Comment by isantop** [comment] 2017-10-31 16:13
_From @RicardoEPRodrigues on July 21, 2017 10:32_

When it happens again I'll try `journalctl` to see if I can catch anything.

**Comment by isantop** [comment] 2017-10-31 16:13
_From @jackpot51 on July 21, 2017 13:4_

I have noticed crashes when using topicons plus. Try disabling it.

**Comment by isantop** [comment] 2017-10-31 16:13
_From @RicardoEPRodrigues on July 21, 2017 13:26_

OK, I'll give it a try, I'll try to keep you posted.

**Comment by isantop** [comment] 2017-10-31 16:13
_From @ryanleesipes on July 25, 2017 17:30_

@RicardoEPRodrigues did this fix the issue?

**Comment by isantop** [comment] 2017-10-31 16:13
_From @RicardoEPRodrigues on July 25, 2017 18:40_

I noticed it unlocks faster, but it seems that it still breaks sometimes.

Em 25/07/2017 19:24, "Ryan Sipes" <notifications@github.com> escreveu:

**Comment by isantop** [comment] 2017-10-31 16:13
_From @RicardoEPRodrigues on July 26, 2017 15:44_

I'm replacing TopIcons Plus with TopIcons and see if any problems arise.

**Comment by isantop** [comment] 2017-10-31 16:13
_From @RicardoEPRodrigues on August 22, 2017 21:7_

After a while of using different extensions I come to the conclusion that the extensions are very unstable, which is sometimes normal (with few people using the extension it can be hard to find bugs).

Yet I don't think the GNOME Shell should crash because of it. I'd rather it just killed of the extension than not loading the desktop at all.

I write this after having another freeze on the desktop. How can we prevent the Shell from crashing?

**Comment by isantop** [comment] 2017-10-31 16:13
_From @WatchMkr on August 28, 2017 22:16_

We've seen instability with extensions as well. The best route is to disable all extensions, then enable one by one over time. Two we've found to be stable are User Themes (with the Pop!_Theme), and the Suspend button extension. You can start with those at least.

One idea we're considering is a Shell safe mode whereby extensions are automatically turned off if the shell crashed.

I'm going to go ahead and close this bug. We're unable to replicate it with the standard extensions we're using in the distro. Let us know if you find which extension/s are causing teh problems.

**Comment by isantop** [comment] 2017-10-31 16:13
_From @RicardoEPRodrigues on September 11, 2017 13:1_

Hello again, I noticed something when the shell is starting.

Looking into `journalctl` and grepping `error` I see a lot of `Too many open files` errors:

```
Sep 11 13:47:47 pop-os gnome-software-service.desktop[3559]: 12:47:47:0420 Gs  suspend-button_laserb has error: GLib.FileError: Failed to open file “/home/ricardo/.local/share/gnome-shell/extensions/suspend-button@laserb/schemas/gschemas.compiled”: open() failed: Too many open files
Sep 11 13:47:47 pop-os gnome-shell[5920]: Extension "user-theme@gnome-shell-extensions.gcampax.github.com" had error: Gio.IOErrorEnum: Error opening file /home/ricardo/.local/share/gnome-shell/extensions/cpufreq@konkor/stylesheet.css: Too many open files
```

Could this be a reason to why the shell breaks? Maybe it's not related with the extensions, but because of the shell trying to load all of them at the same time.

**Comment by isantop** [comment] 2017-10-31 16:13
_From @jackpot51 on September 11, 2017 14:44_

That is interesting @RicardoEPRodrigues

**Comment by isantop** [comment] 2017-10-31 16:13
_From @RicardoEPRodrigues on September 11, 2017 17:20_

I'll try and see if this is a reoccurring issue.

For anyone that sees the shell hang, switch to a terminal (`Ctrl+Alt+F3` or `Ctrl+T` if the shell opens) and type

```
journalctl | grep "Too many open files"
```

If you see lots and lots of these errors please report it.

---

I ran the above command and noticed a lot of

```
Sep 11 13:47:47 pop-os gnome-shell[5920]: unable to create file '/run/user/1000/dconf/user': Too many open files.  dconf will not work properly.
```

I was wondering what does this mean.

**Comment by brs17** [comment] 2018-05-18 16:47
It looks like there has not been any recent updates to reproducing this issue or determining which extension(s) are causing the shell to crash. 

I am going to close this issue for now, if more information becomes available, please provide such information and I will reopen the issue.

**Closed by brs17** 2018-05-18 16:47 UTC
Labels: bug, needs testing
