### ISSUE TITLE
backport-iwlwifi-dkms fails to build on linux kernel 5.3

### ISSUE THREAD

**Issue by jamespotz** [pop-os/pop#689] opened 2019-10-12 00:49 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
backport-iwlwifi-dkms:
  Installed: 7906-0ubuntu1
  Candidate: 7906-0ubuntu1
  Version table:
 *** 7906-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu eoan/universe i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
```shell
sudo dpkg --configure -a
[sudo] password for user: 
Setting up backport-iwlwifi-dkms (7906-0ubuntu1) ...
Removing old backport-iwlwifi-7906 DKMS files...

------------------------------
Deleting module version: 7906
completely from the DKMS tree.
------------------------------
Done.
Loading new backport-iwlwifi-7906 DKMS files...
Building for 5.3.0-17-generic
Building initial module for 5.3.0-17-generic
ERROR (dkms apport): kernel package linux-headers-5.3.0-17-generic is not supported
Error! Bad return status for module build on kernel: 5.3.0-17-generic (x86_64)
Consult /var/lib/dkms/backport-iwlwifi/7906/build/make.log for more information.
dpkg: error processing package backport-iwlwifi-dkms (--configure):
 installed backport-iwlwifi-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 backport-iwlwifi-dkms

```

**Steps to reproduce (if you know):**
```shell
sudo dpkg ---configure -a
```

**Expected behavior:**
Installation success

**Other Notes:**

**Comment by crawfxrd** [comment] 2019-10-12 18:08
https://bugs.launchpad.net/ubuntu/+bug/1835858

**Comment by rotemgb** [comment] 2019-10-16 17:30
Sorry for the question, but I'm new to linux.. I have the same problem. How should I deal with it? should I downgrade back to kernel 5.1?

Thank you

**Comment by wpbryant** [comment] 2019-10-18 22:49
Yeah what are we supposed to do to fix this, bug says fixed in launchpad

**Comment by rotemgb** [comment] 2019-10-19 00:11
I'm not sure how, but it somehow works for me now.
I tried to downgrade my kernel back to 5.1, but before I managed to do it, the WiFi just worked on kernel 5.3.

I hope someone can help you with that (and solve the mystery lol)

**Comment by crawfxrd** [comment] 2019-10-19 01:15
@vicamo has a version that works for 19.10 in the PPA. If you would like to test it, you can [install it from the PPA](https://launchpad.net/~canonical-hwe-team/+archive/ubuntu/backport-iwlwifi/).

```
sudo add-apt-repository ppa:canonical-hwe-team/backport-iwlwifi
sudo apt-get update
```

**Comment by jamespotz** [comment] 2019-10-19 09:49
@crawfxrd I tried the ppa it succeeds but the wifi didnt work.

**Comment by JunkYardTM** [comment] 2019-10-20 07:24
I also have this problem and noticed pop store fails to install any package as a result.

![Screenshot from 2019-10-20 03-22-18](https://user-images.githubusercontent.com/4529670/67156167-0e233180-f2e9-11e9-8656-2a2969e073df.png)

**Comment by vicamo** [comment] 2019-10-20 10:41
Filed as launchpad [bug-1848922](https://bugs.launchpad.net/ubuntu/+source/backport-iwlwifi-dkms/+bug/1848922). Thank you.

**Comment by AfsharJoyceInfoLab** [comment] 2019-10-22 04:56
Any update on this issue?

**Comment by brihat9135** [comment] 2019-10-22 04:58
Any updates on this issue?

**Comment by RenouxMarais** [comment] 2019-10-22 07:44
Same issue here. I just commented so I can stay up to date when a fix is released.

**Comment by oodsway** [comment] 2019-10-22 10:21
I'm having the same issue after upgrade from 19.04 to 19.10.

**Comment by RenouxMarais** [comment] 2019-10-22 11:27
> @vicamo has a version that works for 19.10 in the PPA. If you would like to test it, you can [install it from the PPA](https://launchpad.net/~canonical-hwe-team/+archive/ubuntu/backport-iwlwifi/).
> 
> ```
> sudo add-apt-repository ppa:canonical-hwe-team/backport-iwlwifi
> sudo apt-get update
> ```

Actually, This solved my issue... Thanks!!!

**Comment by mmstick** [comment] 2019-10-22 15:53
I've just copied those packages into our PPA, so there's no need to have the PPA anymore.

**Comment by oodsway** [comment] 2019-10-22 18:11
@mmstick
Fixed it for me. Many thanks!

**Comment by jamespotz** [comment] 2019-10-23 01:51
Doesn't work on my end, both cannonical-hwe PPA and from our PPA
![Screenshot from 2019-10-23 09-22-57](https://user-images.githubusercontent.com/4239625/67349152-b51dfc80-f579-11e9-89b2-ffce953a6743.png)

**Comment by MonkeySon** [comment] 2019-10-23 09:47
@mmstick 
The problem is fixed for me too. Thanks!

**Comment by jamespotz** [comment] 2019-10-24 01:14
@vicamo Thanks but I've fixed the problem.
If anyone is having issues connecting to home wifi after installing `backport-iwlwifi-dkms`, the solution for me was changing my wifi to use `WPA2(AES)-PSK`.

**Closed** 2019-10-24 01:40 UTC

**Comment by nitinsareen** [comment] 2019-11-13 08:58
> @vicamo Thanks but I've fixed the problem.
> If anyone is having issues connecting to home wifi after installing `backport-iwlwifi-dkms`, the solution for me was changing my wifi to use `WPA2(AES)-PSK`.

I can confirm this but this doesn't work standalone. Had to downgrade to version-7906

**Comment by erikkubica** [comment] 2020-06-22 11:19
None of mentioned above worked for me (ubuntu 20, 5.6 kernel) dell xps 15 2019

```
Setting up backport-iwlwifi-dkms (8324-0ubuntu3~20.04.1) ...
Removing old backport-iwlwifi-8324 DKMS files...

------------------------------
Deleting module version: 8324
completely from the DKMS tree.
------------------------------
Done.
Loading new backport-iwlwifi-8324 DKMS files...
Building for 5.6.13-050613-generic
Building initial module for 5.6.13-050613-generic
ERROR (dkms apport): kernel package linux-headers-5.6.13-050613-generic is not supported
Error! Bad return status for module build on kernel: 5.6.13-050613-generic (x86_64)
Consult /var/lib/dkms/backport-iwlwifi/8324/build/make.log for more information.
dpkg: error processing package backport-iwlwifi-dkms (--configure):
 installed backport-iwlwifi-dkms package post-installation script subprocess returned error exit status 10
Setting up xdotool (1:3.20160805.1-4) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9) ...
Errors were encountered while processing:
 backport-iwlwifi-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by vicamo** [comment] 2020-06-23 15:08
@erikkubica I'm working on https://bugs.launchpad.net/ubuntu/+source/backport-iwlwifi-dkms/+bug/1884634, which will upgrade focal/groovy to 8613. Or, [if you just can't wait](https://vicamo.gitlab.io/-/backport-iwlwifi-dkms/-/jobs/607930036/artifacts/aptly/index.html).

**Comment by erikkubica** [comment] 2020-06-24 04:22
@vicamo thanks, I can live with the error message while it's done :)

**Comment by jefte23** [comment] 2021-06-12 21:43
I have the same error... is the process still in the process of being corrected?


Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
backport-iwlwifi-dkms is already the newest version (8613-0ubuntu1).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
1 pacotes não totalmente instalados ou removidos.
Depois desta operação, 0 B adicionais de espaço em disco serão usados.
Você quer continuar? [S/n] s
Configurando backport-iwlwifi-dkms (8613-0ubuntu1) ...
Removing old backport-iwlwifi-8613 DKMS files...

------------------------------
Deleting module version: 8613
completely from the DKMS tree.
------------------------------
Done.
Loading new backport-iwlwifi-8613 DKMS files...
Building for 5.11.0-7614-generic
Building initial module for 5.11.0-7614-generic
ERROR (dkms apport): kernel package linux-headers-5.11.0-7614-generic is not supported
Error! Bad return status for module build on kernel: 5.11.0-7614-generic (x86_64)
Consult /var/lib/dkms/backport-iwlwifi/8613/build/make.log for more information.
dpkg: erro ao processar o pacote backport-iwlwifi-dkms (--configure):
 o subprocesso instalado, do pacote backport-iwlwifi-dkms, o script post-installation retornou erro do status de saída 10
Erros foram encontrados durante o processamento de:
 backport-iwlwifi-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by vicamo** [comment] 2021-06-15 07:41
> Building for 5.11.0-7614-generic
> Building initial module for 5.11.0-7614-generic

I don't own this project, but I'd suggest you to file a new bug instead and @ me there.

**Comment by ryman56** [comment] 2023-02-04 17:22
Hello, I need help with accessing my wifi drivers. I get the same error when doing an update. I can't turn on my wifi on pop os.
sudo dpkg --configure -a                                                                                                         ─╯
Setting up backport-iwlwifi-dkms (9858-0ubuntu3.2) ...
Removing old backport-iwlwifi-9858 DKMS files...
Deleting module backport-iwlwifi-9858 completely from the DKMS tree.
Loading new backport-iwlwifi-9858 DKMS files...
Building for 6.0.12-76060006-generic
Building initial module for 6.0.12-76060006-generic
ERROR (dkms apport): kernel package linux-headers-6.0.12-76060006-generic is not supported
Error! Bad return status for module build on kernel: 6.0.12-76060006-generic (x86_64)
Consult /var/lib/dkms/backport-iwlwifi/9858/build/make.log for more information.
dpkg: error processing package backport-iwlwifi-dkms (--configure):
 installed backport-iwlwifi-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 backport-iwlwifi-dkms
