### ISSUE TITLE
waking up (from suspend) briefly shows the desktop and applications

### ISSUE THREAD

**Issue by ikjelle** [pop-os/pop#1899] opened 2021-09-06 17:28 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 

**Issue/Bug Description:**
After I wake up my laptop from the suspend, I am briefly able to see the windows on the desktop (Like the applications that were open before you suspended). Then after +-5 seconds it switches to the login screen. This is enough time to read information. 

It also sometimes registers input. (but I couldn't open terminals with the shortcut, so not everything might be possible)

**Steps to reproduce (if you know):**
1. Suspend the session (press the power button)
2. Wait until it is suspended
3. Wake the laptop up (keyboard press)
4. See your desktop and windows, like it is not locked, for a couple seconds
5. After 5 seconds it goes to the login screen

*I run this OS on my laptop, not sure if it should matter.

**Expected behavior:**
I think you should not be able to see the desktop and windows as they could be showing private or sensitive data.

**Other Notes:**

It think it could be that the session doesn't get locked before the suspension, but that it happens afterwards. (but I have no knowledge about this)

Other things that happens after I suspend the system:

##### Window order changes after waking up
I also think its weird that the applications windows are out of order.
I.e. I have the application FeatherPad (for notes) behind my web browser but it always(I think) goes in front of the browser after I wake up my laptop. 

##### Black screen after waking up
Also before the login screen appears, the screen is black. You then first have to give an input to show the login screen (no delay, just 1 extra input action, not problematic). 
Although I would suspect it goes to the login screen directly. Because I already made a conscious decision to wake it up, an extra input should be unnecessary. (my opinion)

**Comment by leviport** [comment] 2021-09-07 15:48
Duplicate of https://github.com/pop-os/pop/issues/134

**Closed by leviport** 2021-09-07 15:48 UTC
