### ISSUE TITLE
Alt+left/right arrows switch between tty consoles (Gnome Shell vanishes), cannot disable

### ISSUE THREAD

**Issue by colans** [pop-os/pop#340] opened 2018-08-21 16:20 UTC
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

gnome-shell:
  Installed: 3.28.2-0ubuntu0.18.04.1
  Candidate: 3.28.2-0ubuntu0.18.04.1
  Version table:
 *** 3.28.2-0ubuntu0.18.04.1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.28.1-0ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

**Issue/Bug Description:**

Alt+left/right arrows switch between TTY consoles and Gnome Shell vanishes.  This cannot be disabled.

For more information, see the upstream ticket [Alt+left/right arrows switch between tty consoles (Gnome Shell vanishes), cannot disable](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1508146).

**Steps to reproduce (if you know):**

Hit the Alt - Left arrow in Firefox to navigate to the previous page.  Instead, the TTY switches to the previous console.

**Expected behavior:**

Focus stays on Firefox, and the previous page is loaded.

**Other Notes:**

The workaround is to hit Alt - Right arrow, which navigates back to the active console.  The previous page will be loaded, after a second or two.

**Comment by brs17** [comment] 2018-09-06 20:34
That is an interesting issue that I have not seen before. Glad it is known and being worked on upstream. We'll keep an eye out for the issue and try and figure out the cause.

@bittercold You can follow along with the progress made upstream to fix the plymoth/gdm issue here: https://github.com/pop-os/pop/issues/292

**Comment by jackpot51** [comment] 2018-09-12 19:36
This should be fixed in Pop!_OS in plymouth `0.9.3-1ubuntu7.pop0`

**Closed by jackpot51** 2018-09-12 19:36 UTC
Labels: upstream

**Comment by glemieux** [comment] 2018-09-13 18:08
@jackpot51  How do we track when that update will be out?

**Comment by mmstick** [comment] 2018-09-13 18:31
@glemieux It was pushed out a long time ago.

```
# apt-cache policy plymouth
plymouth:
  Installed: 0.9.3-1ubuntu7.pop0
  Candidate: 0.9.3-1ubuntu7.pop0
  Version table:
 *** 0.9.3-1ubuntu7.pop0 101
        101 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     0.9.3-1ubuntu7 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```
