### ISSUE TITLE
Night Light color temperature reverts after being set.

### ISSUE THREAD

**Issue by PeytonHanel** [pop-os/pop#1286] opened 2020-10-11 02:52 UTC
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

I try to set the color temperature to be as red as possible in my night light settings, but after a few seconds it reverts to a previous setting. Watch the GIF I attached and you will how I set the color to be more red. After a few seconds, the whole screen becomes less red, but the slider doesn't move at all.

![night](https://user-images.githubusercontent.com/26446761/95669174-53f88b80-0b32-11eb-970e-adcab0a4f6ad.gif)

**Comment by leviport** [comment] 2020-10-12 14:04
Were you setting it at a time that your schedule would normally have it turned off? I believe the intended behavior is to momentarily demonstrate the level after you change the setting, then revert it to what it's scheduled to be.

**Comment by leviport** [comment] 2020-10-15 14:38
I'm going to assume what you were seeing was caused by night light scheduling and close this issue. If you believe it is still a bug and my description isn't what is happening, let me know and I can reopen this issue.

**Closed by leviport** 2020-10-15 14:38 UTC
