### ISSUE TITLE
Activities Bug on Dell Latitude E7470

### ISSUE THREAD

**Issue by usamakhan8300** [pop-os/pop#1814] opened 2021-07-15 04:27 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
After update activities do not work properly. If Press activities then no application work. when log out then log in without press activities all apps work fine.
**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by vsarin92** [comment] 2021-07-15 07:50
Yea, facing the exact same issue here. Except I can't get it to work even after logging out then logging back in. I don't think it is hardware specific, because I have a System76 Galago Pro, purchased a few years ago

**Comment by kjcole** [comment] 2021-07-15 11:45
Same behavior on a new Oryx Pro purchased one month ago.

**Comment by jacobgkau** [comment] 2021-07-15 13:37
Duplicate of https://github.com/pop-os/shell/issues/1072.

**Closed by jacobgkau** 2021-07-15 13:37 UTC
