### ISSUE TITLE
focus changes when dragging window to another workspace

### ISSUE THREAD

**Issue by RafalSkolasinski** [pop-os/pop#2404] opened 2022-05-11 19:39 UTC
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop shell extension / Gnome

**Issue/Bug Description:**

When moving to another workspace with dragging window a focus changes and effectively if crossing few workspaces you end up with a different window...

**Steps to reproduce (if you know):**

1. Disable pop cosmic extension
2. Leave pop shell extension on
3. Set workspaces only on primary monitor
4. Have windows open on couple workspaces + auxiliary monitor
5. Use keyboard shortcuts to move window to adjacent workspaces

![image](https://user-images.githubusercontent.com/10928117/167931510-92a35b81-479b-4ed6-b69f-0e80f1550309.png)
![image](https://user-images.githubusercontent.com/10928117/167931532-d5d6671d-9d6e-436c-b3d0-2f2da1277cf0.png)

**Expected behavior:**

You keep dragging the same window all the time...

**Other Notes:**

Disabling pop shell gets expected behaviour.

**Comment by RafalSkolasinski** [comment] 2022-05-11 20:54
Still happens without disabling Pop COSMIC

**Comment by linuxgnuru** [comment] 2022-05-11 21:24
duplicate of https://github.com/pop-os/shell/issues/1415

**Closed by linuxgnuru** 2022-05-11 21:24 UTC
