### ISSUE TITLE
Changing hostname makes sudo commands take a long time [fix in description]

### ISSUE THREAD

**Issue by 31337-4554551n** [pop-os/pop#2744] opened 2022-12-31 22:21 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"

**Issue/Bug Description:**
sudo takes a long time to run if the hostname isn't in the /etc/hosts file
When changing the hostname in the gui, this file isn't modified, so sudo commands start taking a long time
adding
127.0.0.1 newhostname
To hosts file fixes this

**Steps to reproduce (if you know):**
Change hostname in gui
run a sudo command

**Expected behavior:**
it runs at regular speed

**Fix**
When the hostname is changed via the gui, to also add it to the hosts file
For bonus points, remove the old entry

**Comment by jacobgkau** [comment] 2023-01-02 04:49
Duplicate of https://github.com/pop-os/systemd/issues/5.

**Closed by jacobgkau** 2023-01-02 04:49 UTC
