### ISSUE TITLE
Applications menu is too big

### ISSUE THREAD

**Issue by gustavesck** [pop-os/pop#2521] opened 2022-07-11 13:02 UTC
Pop!_OS 22.04 LTS

My screen resolution is 1360x768.

<img src="https://i.imgur.com/IgkZ0Nw.png">

**Comment by leviport** [comment] 2022-07-11 15:49
Duplicate of https://github.com/pop-os/cosmic/issues/314

**Closed by leviport** 2022-07-11 15:49 UTC
