### ISSUE TITLE
Pop OS freezes 'randomly', after opening programs, and when launching some games

### ISSUE THREAD

**Issue by samuel-lucas6** [pop-os/pop#1357] opened 2020-11-02 14:00 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

This was an issue on 20.04 as well.
 
**Issue/Bug Description:**
I've had freezing issues on Pop OS ever since I installed it over 6 months ago. I've reinstalled it three times and they continued. My system used to randomly freeze several times a day (5-8 times a day I would say) forcing me to reset each time. It has been a lot better recently (the number of random freezes decreased to maybe 1-2 every couple of days after a few months on 20.04), but I'm still experiencing problems:

- When I launch a Steam game it often freezes the system within the first minute of playing forcing me to restart (new since 20.10 - this didn't used to be a problem on 20.04).
- The OS sometimes freezes soon or immediately after opening programs (on 20.04 and 20.10). For example, I opened the terminal when writing another GitHub [issue](https://github.com/pop-os/pop/issues/1356) and the OS froze, forcing me to reset.
- I've had about 3-4 freezes so far today. It mostly seems to occur after opening programs.

**Steps to reproduce (if you know):**

**Expected behavior:**
Pop OS shouldn't be freezing. 

**Other Notes:**
I haven't had any issues on Windows, and I didn't have this issue on other distros I've tried. I know I should have reported this earlier, but I just never got around to it until now.

**Comment by mmstick** [comment] 2020-11-02 14:30
Duplicate of #1172

**Closed by mmstick** 2020-11-02 14:30 UTC
