### ISSUE TITLE
20.04 GDM and Lock Screen Elements are Off Center on HiDPI Displays

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/pop#873] opened 2020-03-15 16:38 UTC
Login dialog is to the right of center. This is on a HiDPI glap2 - just assuming it's HiDPI related.

**Comment by leviport** [comment] 2020-03-16 13:24
I believe this to be a duplicate of https://github.com/pop-os/gtk-theme/issues/431 and it does not appear to be limited to HiDPI displays. I'll assign @isantop on that one and close this one.

**Closed by leviport** 2020-03-16 13:24 UTC
Labels: 20.04
