### ISSUE TITLE
The sudo command has an unusually long delay before password prompt

### ISSUE THREAD

**Issue by dwangoac** [pop-os/pop#199] opened 2018-04-15 04:47 UTC
**Distribution:**
`Pop!_OS 18.04 LTS (Testing)`
 
**Steps:**
Issue any command with sudo in a manner that will prompt for a password (i.e. log in to a new session and type `sudo su` or similar).

**Result:**
After pressing enter there is a considerable delay before the password prompt appears.

**Expected:**
The password prompt should appear immediately after a sudo command, mirroring the behavior of Debian and Ubuntu.

**Additional information:**
I have not done a root-cause analysis of what causes the delay but my best guess is some ancilary code is being called that is choking in some way. The usability issue is the primary concern here as it makes the system feel "slow" needlessly. The issue is present both when in an X terminal as well as at a text terminal.

**Comment by Clae224** [comment] 2018-06-04 00:43
This happened to me after needing to reinstall some packages which the system depended on. A crappy workaround for me was to just reinstall.

**Comment by tommystanton** [comment] 2018-06-20 23:35
I'm currently experiencing this same behavior on Pop!_OS 18.04 LTS.

**Comment by Clae224** [comment] 2018-06-21 07:11
Have you tried [these](https://serverfault.com/questions/38114/why-does-sudo-command-take-long-to-execute#41820) solutions?

**Comment by Clae224** [comment] 2018-06-21 09:06
@tommystanton You should search for your problem first and only post if you've tried all the applicable solutions online. That page I linked was the first result I found.

**Comment by olucasfreitas** [comment] 2021-03-27 21:43
I'm experiencing this problem in pop os 20.04 and 20.10, both on the intel ISO and  Nvidia one. I've even tried different computers and it continues, if someone has something that can help me, please contact, this has been bugging me since the last LTS rolled out

**Comment by valerius21** [comment] 2021-09-17 10:56
Hi there, 

using the latest popos install with nvidia drivers (`7134421a04f6c8c062c4b4051b068c287d3a4058768da004e03a710bbf49be8d
`) Pop!_OS 21.04 ISO Image (NVIDIA), I can confirm this issue.

It only occurs when using the `NOPASSWD` keyword in the sudoers file (accessed via `visudo`) removing it, and therefore using the `sudo` command exclusively with a password solves the performance issue.

**Comment by Indomitable** [comment] 2021-12-12 18:49
Hi, Installed Pop OS few days ago and it still has this issue. What fixed it was: Adding your host name (you can take it from `cat /etc/hostname`) to the `/etc/hosts` which should look like 
```
127.0.0.1	localhost   VALUE_OF_HOSTNAME
::1		localhost   VALUE_OF_HOSTNAME
```

**Comment by jacobgkau** [comment] 2021-12-13 17:34
I'm closing this as a duplicate of https://github.com/pop-os/systemd/issues/5 and adding some further information there.

**Closed by jacobgkau** 2021-12-13 17:34 UTC

**Comment by chalapathi-ct** [comment] 2025-01-19 05:55
> Hi, Installed Pop OS few days ago and it still has this issue. What fixed it was: Adding your host name (you can take it from `cat /etc/hostname`) to the `/etc/hosts` which should look like
> 
> ```
> 127.0.0.1	localhost   VALUE_OF_HOSTNAME
> ::1		localhost   VALUE_OF_HOSTNAME
> ```

Not the commands are executing instantaneously.
