### ISSUE TITLE
Recent update broke system boot

### ISSUE THREAD

**Issue by msf235** [pop-os/pop#2604] opened 2022-09-04 16:47 UTC
**Distribution (run `cat /etc/os-release`):**
(this is run from the recovery partition)
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Unknown

**Issue/Bug Description:**
System will not boot. The booting is stuck on my BIOS's loading screen graphic (the screen for decrypting the device does not appear). However, the recovery partition does boot.

**Steps to reproduce (if you know):**
```
sudo apt update
sudo apt upgrade
sudo reboot
```

**Expected behavior:**
The OS will boot to the disk decryption password screen.

**Other Notes:**
The recovery partition boots, and the system boots after a fresh install. However, booting after doing a system update fails. This leads me to believe that a recent update has broken the installation.

My computer is an Intel NUC phantom canyon. The specifications are here: https://simplynuc.com/wp-content/uploads/2022/06/NUC11PH_TechProdSpec.pdf. In particular, the graphics card is an Nvidia RTX 2060.

**Comment by msf235** [comment] 2022-09-05 00:32
I am able to avoid this problem by not encrypting my disk when I do a fresh reinstall.

**Comment by leviport** [comment] 2022-09-06 15:08
This sounds like a duplicate of https://github.com/pop-os/plymouth-theme/issues/31 to me. The solution we're currently investigating is adding Nvidia to the initramfs.

**Comment by msf235** [comment] 2022-09-06 20:57
I agree that this is probably a duplicate of the issue you linked.

**Closed** 2022-09-06 20:58 UTC
