### ISSUE TITLE
Battery level drops to from true value to 1% randomly when not plugged in to a/c.

### ISSUE THREAD

**Issue by jesseregier** [pop-os/pop#1524] opened 2021-02-04 22:35 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

System specs:
Host: Lenovo ThinkPad X1E
Kernel: 5.8.0-7630-generic
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 16GB

**Issue/Bug Description:**
Some time after unplugging the laptop from a/c power the battery level will drop from its true value (somewhere between 10% and 100% depending on how long it has been unplugged) to 1%. This will cause the laptop to shut down within 30 seconds or so. If I plug it back in to a/c power during this 30s window the battery will display its true value and begin charging again. Unplugging from a/c will begin the cycle again.

**Steps to reproduce (if you know):**
Unplug the laptop and wait.

**Expected behavior:**
I expect the battery to drain until it is actually depleted and then turn off the laptop.

**Other Notes:**
This phenomenon will happen randomly some time after unplugging it. Sometimes the battery will drain normally, often it will jump to 1% at some point in the discharge cycle. The battery functioned normally until the OS was updated from 20.04 to 20.10.

**Comment by leviport** [comment] 2021-02-04 22:39
I believe this is a duplicate of https://github.com/pop-os/pop/issues/1354

Let me know if I'm mistaken and I can reopen

**Closed by leviport** 2021-02-04 22:39 UTC
