### ISSUE TITLE
DUALSHOCK4 changes orientation & disables orientation setting

### ISSUE THREAD

**Issue by ghost** [pop-os/pop#127] opened 2018-01-31 09:26 UTC
**Reporter info**

```
 * Distribution - Pop!_OS 17.10
 * Related Application and/or Package Version - Bluetooth
```

**Issue/Bug Description**

Sony DUALSHOCK4 controller rotates display on (wireless) connection, and disables the "orientation" settings (Settings-->Devices-->Displays-->Built-in display-->Orientation) in the process.

Screen orientation can only be corrected by turning DUALSHOCK4 controller off and then correcting the orientation (Settings-->Devices-->Displays-->Built-in display-->Orientation)(the option to do so is restored as soon as DUALSHOCK4 is switched off).

**Steps to reproduce (if you know)**

"Pair" a DUALSHOCK4 controller (hold down "Share" and the "PlayStation" logo button); the issue will present itself immediately. Once the DUALSHOCK4 controller is switched off (hold the "PlayStation" logo button until the LED switches off), turn the DUALSHOCK4 controller back on and the issue will occur again.

**Expected behavior**

That DUALSHOCK4 controller connects to computer wirelessly, ready for usage as an input device in supported games.

**Other Notes**

Another user (not myself) has posted a video showing the issue over here:
https://youtu.be/mcD5SfELvMk

Based on this user's video, the issue also affects the Sony DUALSHOCK3 controller.

**Comment by cassidyjames** [comment] 2018-01-31 16:44
That's… incredible. This looks like a bug in the GNOME accelerometer code.

**Comment by cassidyjames** [comment] 2018-01-31 16:56
@gregoryopera couple of quick questions if you get a chance:

1. Does your computer have a built-in accelerometer, i.e., when you physically rotate it does the display orientation change?

2. Do you know if this can this be reproduced in Ubuntu or other GNOME-based OSes?

**Comment by cassidyjames** [comment] 2018-01-31 17:12
It looks like there was code to fix this upstream back in August. It's not immediately clear why this is not in Pop!_OS, or when it will be.

https://github.com/hadess/iio-sensor-proxy/commit/401d59e54b3123860180d4401e09df8a1e1bc6c3

**Comment by gregoryopera** [comment] 2018-01-31 17:12
I have the ASUS X556UV, which does not have an accelerometer... The DUALSHOCK4 controller however, does.

Unfortunately, I do not have other Ubuntu or GNOME-based operating systems to test this with though (everything is either running Pop!_OS or Apple MacOS).

**Comment by cassidyjames** [comment] 2018-01-31 17:14
@gregoryopera no worries, and thanks for the response! That's helpful and we should have enough information to investigate.

**Comment by sramkrishna** [comment] 2018-02-21 18:17
we should make this part of testing if possible.

**Comment by bflanagin** [comment] 2022-02-07 22:46
Closing due to age and specificity of issue. If this problem persists feel free to reopen the ticket.

**Closed by bflanagin** 2022-02-07 22:46 UTC
Labels: confirmed, upstream
