### ISSUE TITLE
Workspaces overview not showing apps on secondary display

### ISSUE THREAD

**Issue by lukasz-aw** [pop-os/pop#2528] opened 2022-07-14 22:05 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Issue/Bug Description:**
Workspaces overview is not showing windows open on secondary screen.
When having multiple windows open on primary and secondary display after invoking workspace overview I should see all opened windows on both primary and secondary screen.
After invoking workspace overview secondary display windows are hidden and I am not able to see open windows and switch to them.

Regular
![image](https://user-images.githubusercontent.com/7473720/179096473-ad0def52-8497-47bd-b97d-292eab4aaacf.png)

Workspace overview
![image](https://user-images.githubusercontent.com/7473720/179096510-9296baa5-9218-4df2-ad3a-282543aaaa2e.png)

**Steps to reproduce (if you know):**
1.Connect more than one display to your PC
2.In desktop options select Super Key Action = Workspaces
3.In workspaces select Multi-monitor Behavior = Workspaces on Primary Display Only
4. Open several windows on primary and secondary monitor.
5. Click Super Key to open workspaces overview.

**Expected behavior:**
All open windows should be shown on both primary and secondary screen.

**Comment by leviport** [comment] 2022-07-14 22:09
I think this might be a duplicate of https://github.com/pop-os/gnome-shell/issues/102

If you change your workspace picker position to the left side of the screen, do the previews stay on the second monitor as expected?

**Comment by lukasz-aw** [comment] 2022-07-14 22:12
Thanks @leviport Yes, when I changed picket to the left then it is working fine.

**Comment by leviport** [comment] 2022-07-14 22:13
Thanks for confirming. I'll close this as a duplicate of https://github.com/pop-os/gnome-shell/issues/102

**Closed by leviport** 2022-07-14 22:13 UTC
