### ISSUE TITLE
Cannot Restart or Shut down from Lock Screen

### ISSUE THREAD

**Issue by robbaran** [pop-os/pop#750] opened 2019-11-15 23:41 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Clicking "Restart" or "Shut Down" from the Lock Screen does nothing.

**Steps to reproduce (if you know):**
Restart system. Wait until lock screen. Click upper-right menu. Click Power button. Click "Restart".

**Expected behavior:**
I expect the system to either restart or shutdown when "Restart" or "Shut Down" is clicked. Instead, the lock screen simply persists unchanged.

**Other Notes:**

**Comment by brs17** [comment] 2019-11-18 16:58
This is a duplicate of https://github.com/pop-os/pop/issues/708

**Closed by brs17** 2019-11-18 16:58 UTC
