### ISSUE TITLE
Natural scrolling stopped working since recent upates

### ISSUE THREAD

**Issue by allentje** [pop-os/pop#1305] opened 2020-10-19 12:52 UTC
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
Since installing pop os system updates the natural scrolling mouse setting seems to revert to regular scrolling seemingly randomly and on startup.
Even though natural scrolling is shown to be enabled it does not natural scroll.
I have to deactivate and then reactivate natural scrolling to get it to work again.

**Expected behavior:**
When natural scrolling is set in the settings then it should natural scroll.

**Comment by jacobgkau** [comment] 2020-10-19 14:24
Thank you for the report! I'm closing this issue because it's a duplicate of https://github.com/pop-os/gnome-control-center/issues/120.

**Closed by jacobgkau** 2020-10-19 14:24 UTC

**Comment by allentje** [comment] 2020-10-19 14:28
Thanks for the speedy reply!
