### ISSUE TITLE
Square artifacts in the corners of the dock

### ISSUE THREAD

**Issue by ClosetCoder** [pop-os/pop#1773] opened 2021-07-04 00:58 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Unable to tie to a specific application as of yet, since they can appear on a reboot.

**Issue/Bug Description:**
Square artifacts appear in all four corners of the dock simultaneously

**Steps to reproduce (if you know):**
Unable to narrow it down as of yet, seems random on reboot or wake from suspend

**Expected behavior:**
No artifacts in the corners of the dock

**Other Notes:**
Image included hear showing artifacts
![Screenshot from 2021-06-30 22-02-54](https://user-images.githubusercontent.com/14336939/124370090-26a3be80-dc28-11eb-89db-02479d5e2e74.png)

**Comment by leviport** [comment] 2021-07-06 15:07
Duplicate of https://github.com/pop-os/cosmic-dock/issues/33

**Closed by leviport** 2021-07-06 15:07 UTC
