### ISSUE TITLE
selected line on gedit appears completely white

### ISSUE THREAD

**Issue by raenii** [pop-os/pop#353] opened 2018-09-09 18:27 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gedit:
  Installed: 3.28.1-1ubuntu1
  Candidate: 3.28.1-1ubuntu1
  Version table:
 *** 3.28.1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
on the pop-dark-slim theme, the selected line on gedit appears nearly completely white, making it next to impossible to read what i'm typing.

**Steps to reproduce (if you know):**
turn on the pop-dark-slim theme and open gedit.

**Expected behavior:**
selected line nearly entirely white, the same colour as the text.

**Comment by brs17** [comment] 2018-09-10 18:30
I can confirm this does happen. I have included a screenshot of what it looks like.

![screenshot from 2018-09-10 12-27-06](https://user-images.githubusercontent.com/7460774/45316731-1c532b80-b4f5-11e8-9efa-be271fb75e6f.png)

@isantop, I know a new version is in the works, regardless of fixing this before the release of the new version, let's make sure this doesn't happen in the new version.

**Comment by waveneko** [comment] 2018-09-13 15:43
> I can confirm this does happen. I have included a screenshot of what it looks like.
> 
> ![screenshot from 2018-09-10 12-27-06](https://user-images.githubusercontent.com/7460774/45316731-1c532b80-b4f5-11e8-9efa-be271fb75e6f.png)
> 
> @isantop, I know a new version of the theme is in the works, regardless of fixing this before the release of the new version, let's make sure this doesn't happen in the new version.

apparently, using the pop dark theme inside of gedit fixes the issue.

**Comment by isantop** [comment] 2018-09-13 17:14
Yeah, this is a difficult problem to fix because the way the default color scheme in GtkSourceView is calculated from the current theme is heavily biased towards light themes. This issue also happens with Adwaita-Dark and gedit, which is why the Pop and Pop-Dark SourceView themes were created for use with Gedit.

**Comment by isantop** [comment] 2019-05-23 17:08
This has been fixed in 19.04 with the Dark theme toggle in appearance settings, which now swaps the default sourceview theme for gedit when the theme is changed.

**Closed** 2021-06-22 20:59 UTC
Labels: bug, confirmed
