### ISSUE TITLE
Pos OS Graphic bug application launcher

### ISSUE THREAD

**Issue by pavl0v95** [pop-os/pop#1835] opened 2021-07-28 21:58 UTC
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
When I start the system and click on application launcher icon the menu is zoomed and icon very big. Turns to normal when i go to settings and changed icon layout of dock. When i restart the OS the issue is always here.

 

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by Goku-04** [comment] 2021-07-29 11:50
![image](https://user-images.githubusercontent.com/65329453/127486892-3dd04de7-67c4-4e59-b3ae-a6638d2e2daa.png)
Can confirm this visual bug
Appeared yesterday when I fresh installed pop os

**Comment by pavl0v95** [comment] 2021-07-29 12:30
Yes, it's this

**Comment by leviport** [comment] 2021-07-29 15:02
Duplicate of https://github.com/pop-os/pop/issues/1786

**Closed by leviport** 2021-07-29 15:02 UTC
