### ISSUE TITLE
~/.local/share not in $XDG_DATA_DIRS

### ISSUE THREAD

**Issue by egrath** [pop-os/pop#1740] opened 2021-06-21 09:24 UTC
**Distribution:** 21.04 (latest BETA)

 **Issue/Bug Description:**
The path <code>~/.local/share</code> is not in $XDG_DATA_DIRS, so created .desktop files by the user or applications like Google Chrome do not show up in the Menu.

**Steps to reproduce (if you know):**
Just create a syntactically correct .desktop file under <code>~/.local/share/applications</code>, it won't show up in the Applications list or when Searching for it.

**Expected behavior:**
Show the Application defined by the .desktop file.

**Comment by jacobgkau** [comment] 2021-06-21 14:11
Thank you for the report. I'm closing this as a duplicate of https://github.com/pop-os/beta/issues/183.

**Closed by jacobgkau** 2021-06-21 14:11 UTC
