### ISSUE TITLE
Box following cursor when zoom enabled GNOME

### ISSUE THREAD

**Issue by faizjamil** [pop-os/pop#1192] opened 2020-08-15 02:43 UTC
**Distribution (run `cat /etc/os-release`):**
 
Pop_OS 20.04 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

GNOME 3.36.2 & 3.36.3

**Issue/Bug Description:**
When zoom is on and magnification is set to 1.00 moving around the cursor results in a transparent box

**Steps to reproduce (if you know):**
Boot the latest Pop_OS ISO or install Pop_OS 20.04 with GNOME 3.36.2/3.36.3
Turn on Zoom (in Universal Access)
Set the magnification to 1.00
Move cursor around

**Expected behavior:**

Box follows cursor and lingers for about a minute at least

**Other Notes:**
GIF of the bug in question:
https://gfycat.com/arcticfeistybat

**Comment by leviport** [comment] 2020-08-17 13:36
Duplicate of https://github.com/pop-os/pop/issues/1059

**Closed by leviport** 2020-08-17 13:36 UTC
