### ISSUE TITLE
Unable to change desktop background

### ISSUE THREAD

**Issue by garybowers** [pop-os/pop#2066] opened 2021-12-15 14:41 UTC
**Distribution (run `cat /etc/os-release`):**  
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-control-center:
  Installed: 1:40.0-1ubuntu5pop0~1637613403~21.10~2dafb76

**Issue/Bug Description:**
On new wallpaper selection, wallpaper is not set on desktop

**Steps to reproduce (if you know):**
1/ Open gnome-control-center
2/ Choose desktop / background
3/ Select background

**Expected behavior:**
Desktop background is changed upon selecting new wallpaper

**Other Notes:**

**Comment by leviport** [comment] 2021-12-15 19:01
This was a [bug](https://github.com/pop-os/beta/issues/230) early on, but it's been fixed for a while. Can you confirm that everything is fully up-to-date?

**Comment by garybowers** [comment] 2021-12-15 19:05
This is on a fresh install (from scratch) of 21.10

**Comment by combe15** [comment] 2021-12-17 00:20
fresh install here, same issue

<pre>cat /etc/os-release
NAME=&quot;Pop!_OS&quot;
VERSION=&quot;21.10&quot;
ID=pop
ID_LIKE=&quot;ubuntu debian&quot;
PRETTY_NAME=&quot;Pop!_OS 21.10&quot;
VERSION_ID=&quot;21.10&quot;
HOME_URL=&quot;https://pop.system76.com&quot;
SUPPORT_URL=&quot;https://support.system76.com&quot;
BUG_REPORT_URL=&quot;https://github.com/pop-os/pop/issues&quot;
PRIVACY_POLICY_URL=&quot;https://system76.com/privacy&quot;
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
</pre>

**Comment by combe15** [comment] 2021-12-17 00:55
Update: Background is stuck to default, but lock-screen's and workspaces' background was changed.
![image](https://user-images.githubusercontent.com/11339091/146470828-616f85cc-2035-42e3-8c3e-1c93b6927c82.png)
![image](https://user-images.githubusercontent.com/11339091/146470880-b717c446-77a8-4297-9abf-c4dffad0416d.png)
Hope this helps

**Comment by leviport** [comment] 2021-12-17 16:55
Can you try restarting Gnome Shell (Alt+F2, `r`, enter) to see if the default wallpaper still appears afterwards?

**Comment by garybowers** [comment] 2021-12-17 19:20
That does work

**Comment by garybowers** [comment] 2021-12-17 19:20
But I don't see that as a solution there's clearly a bug somewhere, if I know where to look I'm happy to try and find some logs.

**Comment by frizikk** [comment] 2021-12-18 06:42
fresh install 

`NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os`

**Comment by csimpi** [comment] 2021-12-19 01:41
This bug is still happening with fresh install 21.10. According to the same reports and support questions on the discord server.

**Comment by ajrances** [comment] 2021-12-19 01:45
just reboot and it will be fixed. We have the same bug that might be from patches and you need a reboot to fix some things

**Comment by garybowers** [comment] 2021-12-19 09:42
@ajrances Rebooting isn't a solution - it's a workaround, even after restarting gnome/pop when you change the background and click on Workspaces it shows the old background - it's clearly a bug, please don't suggest rebooting is the solution.

**Comment by unenergizer** [comment] 2021-12-24 01:20
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

------

OS: Pop!_OS 21.10 x86_64 
Kernel: 5.15.8-76051508-generic 
Uptime: 7 mins 
Packages: 1839 (dpkg), 9 (flatpak) 
Shell: bash 5.1.8 
Resolution: 1920x1080, 1920x1080, 105 
DE: GNOME 40.5 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 5800X (16) @ 3.800GH 
GPU: NVIDIA GeForce GTX 970 
Memory: 2356MiB / 32066MiB

------

This is after a fresh install. Wallpaper doesn't set unless I restart. Restarting kills the rewarding experience of changing your background to something nice new and flashy.

That being said, still, thank you for all your heard work. Love what is going on here. :heart:

**Comment by devsecfranklin** [comment] 2021-12-28 14:46
> cat /etc/os-release

This corrected the issue in the running session for me.

**Comment by devsecfranklin** [comment] 2021-12-28 14:47
> Can you try restarting Gnome Shell (Alt+F2, `r`, enter) to see if the default wallpaper still appears afterwards?

This corrected the issue in the running session for me. 

```
franklin ߷ ~/workspace ➤ cat /etc/os-release                  
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```

**Comment by ganakee** [comment] 2022-01-03 16:41
I am also seeing this on an upgraded copy. This started sometime between about 20 December and 3 January 2022 if that helps. It was not an issue initially for me with an upgrade from 21.04 to 21.10. All upgrades applied in both POP Shop and manually via APT.

I did some testing. The normal stuff parallels what others reported here.

1. Settings...
2. Background...
3. Select any background (single click, double click etc.). The new background shows selected but does not apply.
4. Reboot.
5. On login, the formerly selected background now applies.

1. Tried same... (1-3 above)
2. Logout....
3. Login....
4. The formerly selected now applies.

ADDITIONAL INFORMATION: 
Then I used the ALT+F2 then 'r' to run the GNOME shell reset command as noted above by @devsecfranklin . The desktop seemed to restart and applies the selected background without logout or reboot. **BUT NOW GNOME Settings works OK and as normal. In other words, ALT+F2 r  seems to "fix" the issue not just once but for each time.**

Also note that Settings...Desktop...appears to default to the
![Screenshot from 2022-01-03 11 34 10](https://user-images.githubusercontent.com/23140586/147955876-3e2af6e8-7797-43d1-b48f-20dbd5fe3939.png)
 General Tab (showing GENERAL highlighted and selected) but Settings is actually showing the Desktop Background tab's display. Not sure if this is linked to the issue but saw this as I tested. Not sure if I explained what I see other than the tabs seem wrongly selected--maybe causing a subtle config issue (you are not really configuring the tab you think that you are)?

**Comment by ganakee** [comment] 2022-01-04 16:18
I did some more testing on a laptop that I also run POPOS on. The laptop, same version of POPOS, does NOT exhibit this issue.

The primary difference between the workstation (above) and the laptop is that the workstation (showing the problem see @ganakee ) runs the NVidia driver. The laptop just uses generic--no discrete graphics.

**Comment by yatima1460** [comment] 2022-01-06 22:45
I have the same problem, setting a wallpaper does nothing, but logout/login or using ALT+F2 'r' afterwards changes it correctly

**Comment by coyoterj** [comment] 2022-01-08 22:13
> I have the same problem, setting a wallpaper does nothing, but restarting or using ALT+F2 'r' afterwards changes it correctly

Me too.

NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**Comment by JamesMowery** [comment] 2022-01-15 21:29
Confirming I have the same issue. Running X11 as I have an Nvidia card.

> james@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**Comment by wlinna** [comment] 2022-01-16 11:39
I have the same issue. The easiest way for me to "apply" the change is to change display configuration (such as turning fractional scaling on and off again).

I installed Pop!_OS 21.10 on Jan 13 2022. 
My GPU is Intel Skylake GT2 [HD Graphics 520]. The desktop runs on X11.

I haven't experienced this issue on Pop!_OS 20.10 or 21.04. I'm not sure if I experienced this issue immediately after the  fresh installation or if it appeared afterwards.

**Comment by Daasin** [comment] 2022-01-18 17:36
Also have a similar Issue with Wallpapers not updating until I change display mirroring or refresh rate? 

Tried different kernels, different drivers, different app to change the wallpaper, it just wont refresh until I force it with another change. Applies to other desktop settings aswell which seemed odd if nobody has had that issue yet

It seems to be temporarily mitigated by switching how multiple monitors are shared with the keyboard shortcut, I think it was external only but that still displays to both displays and seems to revert all my changes like fractional and hiDPI daemon, refresh rate, nvidia settings,  interlaced vs progressive etc. GTX 1080, 475 Driver, PopOS 21.10, Had the issue since release and have been keeping up to date since then.

**Comment by Daasin** [comment] 2022-01-18 18:25
Also have a similar Issue with Wallpapers not updating until I change display mirroring or refresh rate? 

Tried different kernels, different drivers, different app to change the wallpaper, it just wont refresh until I force it with another change. 

- **Note:** ***Applies to other desktop settings aswell, the background was just the more easily seen place it applies (or doesn't till switching another display setting on or off), which seemed odd if nobody has had issues in the others yet***

It seems to be temporarily mitigated by switching how multiple monitors are shared with the keyboard shortcut, I think it was external only but that still displays to both displays and seems to revert all my changes like fractional *(Which also seems to make Steam UI Tiny on both screens)* and hiDPI daemon, refresh rate, nvidia xvideo sync settings, interlaced vs progressive, which display is primary in xerver, etc. 

Config is GTX 1080, 475 Driver, PopOS 21.10, on all kernels so far even with 5.16.1 manually installed. Had this issue since release and have consistently been keeping up-to-date since then. 

Same as: https://github.com/pop-os/shell/issues/1276 
Similar occurrence as: issues face with #1336 

Sorry about prev edit & deletion, but Hopefully this information helps rule some causes out or find a common cause with other issues :)

**Comment by tunix** [comment] 2022-01-20 23:46
Just had a refreshed install. Still having this issue in 21.10.

```
cat /etc/os-release                                                                                                                                                                                                                                                        ─╯

NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```

**Comment by uncivilgentleman** [comment] 2022-01-22 03:45
I can confirm this bug.  I'm also running a fresh install of 21.10 on a Lemur Pro (LEMP10).

**Comment by uncivilgentleman** [comment] 2022-01-22 15:58
I figured out how to reliably reproduce the bug.  Plug in a second monitor.

**Comment by gurubobnz** [comment] 2022-01-24 19:24
Upgraded from 22.04 to 22.10 last night, changed background, can confirm all of what is said above. When problem exhibits itself I can briefly see the new desktop background as I switch to different workspaces, then the original (unwanted) background shows.

**Comment by xanderificnl** [comment] 2022-01-24 20:53
Confirmed. Restarting gnome-shell w/ <kbd>alt</kbd><kbd>f2</kbd> <kbd>r</kbd> resolves it.

**Comment by garybowers** [comment] 2022-01-24 20:56
can confirm restarting gnome does NOT 'resolve' the issue - it comes back if you want to change the wallpaper later - it restarts the shell with the correct wallpaper but the bug still persists.

**Comment by xanderificnl** [comment] 2022-01-24 20:59
Indeed. The problem is merely bypassed for the current session (or at least, it's for me. I'm able to switch backgrounds on the fly atm.)

**Comment by tunix** [comment] 2022-01-24 21:15
It looks like the problem is somewhere in Cosmic Workspaces extension. I disabled most of the system extensions and restarted GNOME Shell with `alt+f2+r`. Then started enabling extensions one by one, change wallpapers and change between overview, restart GNOME Shell again etc... Until enabling Cosmic Workspaces extension, everything is fine. After enabling the extension and restart GNOME, this behavior starts to occur.

**Comment by uncivilgentleman** [comment] 2022-01-25 14:59
The bug is present on Wayland as well as Xorg. On wayland the `alt+f2+r` band-aid doesn't work as Wayland doesn't support it.

**Comment by Cereal-Killa** [comment] 2022-02-01 12:40
I have found a workaround, by updating Gnome the extension "Desktop Icons" the desktop background seems to update fine on my machine, running on a RTX 2060. (https://extensions.gnome.org/extension/1465/desktop-icons/)

1) Browse to https://extensions.gnome.org/local/
2) Install the Firefox addon from there, it will allow it to scan your extensions.
3) It will scan your extensions and let you know "Desktop Icons" has an update.
4) Update it using the update icon next to it.
5) You may get an error, disregard it and reboot the computer.
6) The wallpaper changes accordingly.

**Comment by mortalglitch** [comment] 2022-02-07 14:10
I experience this as well. 
Nvidia graphics.
Changing the background works fine during for awhile after a fresh boot, after some time this issue creeps in, hard to say how long as I normally only swap backgrounds once every week or so. 
Alt + F2 -> R does seem to workaround to show the background.

I do run many gpu intensive programs so Nvidia drivers are likely getting quite a workout. 

> System Data:
> OS: Pop!_OS 21.10 x86_64
> CPU: Intel i7-9700K (8) @ 4.900GHz
> GPU: NVIDIA GeForce GTX 1070 Mobile
> Kernel: 5.15.15-76051515-generic

Not sure if relevant but running three monitors at the time of the last instance.

**Comment by ganakee** [comment] 2022-02-08 19:05
Tried the Desktop Icons suggestion by @Cereal-Killa . After reboot, switching backgrounds works without the Alt+F2+r trick. I will monitor and see if this "sticks"--the Alt-F2+r trick works for a while and then fails.
 
Running NVidia card.

**Comment by Daasin** [comment] 2022-02-08 20:56
Changing how monitors are mirrored from keyboard (even if it doesn't seem to do much on on external only for PC's with dedicated Nvidia graphics cards) 

Is a temp workaround for me ...well that and flicking fractional scaling on & off to force a refresh

**Comment by Daasin** [comment] 2022-02-08 21:01
Also have a similar Issue with Wallpapers not updating until I change display mirroring or refresh rate? 

Tried different kernels, different drivers, different app to change the wallpaper, it just wont refresh until I force it with another change. 

- **Note:** ***Applies to other desktop settings aswell, the background was just the more easily seen place it applies (or doesn't till switching another display setting on or off), which seemed odd if nobody has had issues in the others yet***

It seems to be temporarily mitigated by switching how multiple monitors are shared with the keyboard shortcut, I think it was external only but that still displays to both displays and seems to revert all my changes like fractional *(Which also seems to make Steam UI Tiny on both screens)* and hiDPI daemon, refresh rate, nvidia xvideo sync settings, interlaced vs progressive, which display is primary in NV-xServer, etc. 

Config is GTX 1080, 475 Driver, PopOS 21.10, on all kernels so far even with 5.16.5 manually installed. Had this issue since release and have consistently been keeping up-to-date since then. 

Same as: https://github.com/pop-os/shell/issues/1276 
Similar occurrence as: issues faced with #1336 

Sorry about prev edit & deletion, but Hopefully this information helps rule some causes out or find a common cause with other issues :)

**Comment by ganakee** [comment] 2022-02-11 17:50
I verify that for my system, the Desktop Icons workaround by @Cereal-Killa  works and fixes the issue even after multiple reboots. The Desktop Icons update workaround does not require re-doing the workaround repeatedly like the Alt+F2+r workaround requires.

@Cereal-Killa 's workaround involves the Desktop Icons NG extension. [https://gitlab.com/rastersoft/desktop-icons-ng](url) In addition to the Firefox plugin option (apparently needed to upgrade), see GNOME Extensions by using the `Super Key+Extensions` and look for Desktop Icons NG (DING).


Running NVidia card.

NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**Comment by Kasazn** [comment] 2022-02-14 13:41
kasazn@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os


Happening on a fresh install.

**Comment by garybowers** [comment] 2022-02-15 08:25
Any update on this? @leviport it's a 2 month old issue... or at least point us to the root cause so I can have a go at trying to fix it. Can you confirm if it's ding?

**Comment by Cereal-Killa** [comment] 2022-02-15 20:02
> 

https://github.com/pop-os/desktop-icons-ng/pull/23

**Comment by Kasazn** [comment] 2022-02-21 01:12
I ran apt update, upgrade, full-upgrade. Now desktop wallpapers changes as the user intended. Tested and working.

**Closed** 2022-02-21 17:35 UTC

**Comment by jokbon** [comment] 2022-04-28 20:23
I have this isusue on 22.04 LTS 
PLEASE FIX!
I clicked on image on firefox, clicked set as desktop background, it bringed pop os thingy for setting backgrounds.
but when i clicked to apply the background, old got stuck.

**Comment by jokbon** [comment] 2022-04-28 20:24
Got pop os hour ago from official website. I also clicked to update it. :(

**Comment by leviport** [comment] 2022-04-28 21:53
@jokbon I've confirmed that the "set desktop background" option in Firefox does not work, but this issue is about something else entirely. If you save the image, you can set it as your background afterwards. I've opened an issue to track the bug you've reported here: https://github.com/pop-os/pop/issues/2322

**Comment by LUCKsBane0** [comment] 2023-04-28 08:17
Okay, so for anyone who still needs this fixed: Install dconf editor, then go to: org.gnome.desktop.background. Choose picture-uri-dark. Under custom value put in ur file link (you can see the correct link in picture-uri. Hope I could help.
