### ISSUE TITLE
Clicking Device Firmware for Dell Dock Crashes Settings Panel

### ISSUE THREAD

**Issue by AustinReed** [pop-os/pop#3109] opened 2023-08-19 02:49 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
firmware-manager:
  Installed: 0.1.2~1683137852~22.04~c9367bb
  Candidate: 0.1.2~1683137852~22.04~c9367bb
  Version table:
 *** 0.1.2~1683137852~22.04~c9367bb 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

Whenever I go to the Firmware section under settings it crashes when I click on any of the Device Firmware descriptions

**Steps to reproduce (if you know):**

```
(base) austin@pop-os:/etc/apt/sources.list.d$ RUST_BACKTRACE=full gnome-control-center
unknown device key: Protocol (v): Variant("tw.com.emc.elantp")
unknown device key: VersionRaw (v): Variant(2)
unknown device key: CompositeId (v): Variant("9ea595d5c08261179bd1362ac3e05c97142c9251")
unknown device key: Protocol (v): Variant("com.dell.dock")
unknown device key: CompositeId (v): Variant("9ea595d5c08261179bd1362ac3e05c97142c9251")
unknown device key: Protocol (v): Variant("com.dell.dock")
unknown device key: VersionRaw (v): Variant(257)
unknown device key: CompositeId (v): Variant("9ea595d5c08261179bd1362ac3e05c97142c9251")
unknown device key: Protocol (v): Variant("com.dell.dock")
unknown device key: VersionRaw (v): Variant(257)
unknown device key: CompositeId (v): Variant("9ea595d5c08261179bd1362ac3e05c97142c9251")
unknown device key: Protocol (v): Variant("com.synaptics.mst")
unknown device key: Protocol (v): Variant("com.dell.dock")
unknown device key: VersionRaw (v): Variant(16665)
unknown device key: Protocol (v): Variant("org.usb.dfu")
unknown device key: VersionRaw (v): Variant(1)
unknown device key: Protocol (v): Variant("org.nvmexpress")
unknown device key: VersionRaw (v): Variant(4222214849179136)
unknown device key: CompositeId (v): Variant("4bde70ba4e39b28f9eab1628f9dd6e6244c03027")
unknown device key: Protocol (v): Variant("com.intel.thunderbolt")
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
unknown release key: ReleaseId (v)
unknown release key: Created (v)
unknown release key: Locations (v)
unknown release key: Urgency (v)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Invalid return value: expected (), got gboolean", filename: "/build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/closure.rs", function: "glib::closure", line: 365 }', /build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/object.rs:2968:50
stack backtrace:
   0:     0x7fb77c96f59a - <unknown>
   1:     0x7fb77c996f6e - <unknown>
   2:     0x7fb77c96b675 - <unknown>
   3:     0x7fb77c96f365 - <unknown>
   4:     0x7fb77c970b1f - <unknown>
   5:     0x7fb77c97085b - <unknown>
   6:     0x7fb77c9710c8 - <unknown>
   7:     0x7fb77c970fc9 - <unknown>
   8:     0x7fb77c96fa06 - <unknown>
   9:     0x7fb77c970cd2 - <unknown>
  10:     0x7fb77c4ef4a3 - <unknown>
  11:     0x7fb77c4ef953 - <unknown>
  12:     0x7fb77c535438 - <unknown>
  13:     0x7fb77c5379c0 - <unknown>
  14:     0x7fb77e791745 - g_cclosure_marshal_VOID__OBJECTv
  15:     0x7fb77e7b0700 - g_signal_emit_valist
  16:     0x7fb77e7b0863 - g_signal_emit
  17:     0x7fb77de46a89 - <unknown>
  18:     0x7fb77dff0be5 - <unknown>
  19:     0x7fb77e7b0700 - g_signal_emit_valist
  20:     0x7fb77e7b0863 - g_signal_emit
  21:     0x7fb77de07ffc - <unknown>
  22:     0x7fb77e797866 - g_cclosure_marshal_VOID__BOXEDv
  23:     0x7fb77e7b0700 - g_signal_emit_valist
  24:     0x7fb77e7b0863 - g_signal_emit
  25:     0x7fb77ddffacb - <unknown>
  26:     0x7fb77de0783b - <unknown>
  27:     0x7fb77de08443 - <unknown>
  28:     0x7fb77ddcef90 - gtk_event_controller_handle_event
  29:     0x7fb77dfa0045 - <unknown>
  30:     0x7fb77dfe6eb8 - <unknown>
  31:     0x7fb77e7b0700 - g_signal_emit_valist
  32:     0x7fb77e7b0863 - g_signal_emit
  33:     0x7fb77dfae724 - <unknown>
  34:     0x7fb77de51680 - <unknown>
  35:     0x7fb77de5252a - gtk_main_do_event
  36:     0x7fb77e4ca743 - <unknown>
  37:     0x7fb77e501f56 - <unknown>
  38:     0x7fb77e699d3b - g_main_context_dispatch
  39:     0x7fb77e6ef258 - <unknown>
  40:     0x7fb77e6973e3 - g_main_context_iteration
  41:     0x7fb77e8befb5 - g_application_run
  42:     0x55a55f43fd83 - main
  43:     0x7fb77b229d90 - <unknown>
  44:     0x7fb77b229e40 - __libc_start_main
  45:     0x55a55f43ff65 - _start
  46:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
```
(base) austin@pop-os:/etc/apt/sources.list.d$ sudo apt update
sudo apt upgrade
sudo apt dist-upgrade
sudo apt autoremove
[sudo] password for austin: 
Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Hit:2 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease                 
Hit:3 http://apt.pop-os.org/proprietary jammy InRelease                                
Hit:4 http://apt.pop-os.org/release jammy InRelease
Hit:5 http://apt.pop-os.org/ubuntu jammy InRelease
Hit:6 http://apt.pop-os.org/ubuntu jammy-security InRelease
Hit:7 http://apt.pop-os.org/ubuntu jammy-updates InRelease
Hit:8 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

````
(base) austin@pop-os:/etc/apt/sources.list.d$ journalctl -xe | grep firmware-manager
Aug 18 19:31:25 pop-os gnome-lock-panel.desktop[123823]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Invalid return value: expected (), got gboolean", filename: "/build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/closure.rs", function: "glib::closure", line: 365 }', /build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/object.rs:2968:50
Aug 18 19:31:45 pop-os gnome-control-center.desktop[124417]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Invalid return value: expected (), got gboolean", filename: "/build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/closure.rs", function: "glib::closure", line: 365 }', /build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/object.rs:2968:50
Aug 18 19:32:17 pop-os gnome-control-center.desktop[124549]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Invalid return value: expected (), got gboolean", filename: "/build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/closure.rs", function: "glib::closure", line: 365 }', /build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/object.rs:2968:50
Aug 18 19:33:43 pop-os gnome-control-center.desktop[124762]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Invalid return value: expected (), got gboolean", filename: "/build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/closure.rs", function: "glib::closure", line: 365 }', /build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/object.rs:2968:50
Aug 18 19:37:26 pop-os sudo[125128]:   austin : TTY=pts/4 ; PWD=/etc/apt/sources.list.d ; USER=root ; COMMAND=/usr/bin/apt remove --purge firmware-manager
Aug 18 19:37:27 pop-os sudo[125133]:   austin : TTY=pts/4 ; PWD=/etc/apt/sources.list.d ; USER=root ; COMMAND=/usr/bin/apt install firmware-manager
Aug 18 19:38:15 pop-os gnome-control-center.desktop[125008]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Invalid return value: expected (), got gboolean", filename: "/build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/closure.rs", function: "glib::closure", line: 365 }', /build/firmware-manager-rLY3OS/firmware-manager-0.1.2~1683137852~22.04~c9367bb/vendor/glib/src/object.rs:2968:50
(base) austin@pop-os:/etc/apt/sources.list.d$ 
```

**Expected behavior:**
Expected not to crash 


**Other Notes:**

**Comment by leviport** [comment] 2023-08-21 15:07
Duplicate of https://github.com/pop-os/gnome-control-center/issues/236

**Closed by leviport** 2023-08-21 15:07 UTC
