### ISSUE TITLE
Using a active PPA repository, Flatpak transition dialog should not appear

### ISSUE THREAD

**Issue by Arg0s1080** [pop-os/pop#1121] opened 2020-07-03 09:31 UTC
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
- Transition to Flatpak dialog
- keepassxc

```
keepassxc:
  Instalados: 2.5.4-1ppa1~focal1
  Candidato:  2.5.4-1ppa1~focal1
  Tabla de versión:
 *** 2.5.4-1ppa1~focal1 500
        500 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.3+dfsg.1-1build1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
```

**Issue/Bug Description:**
When the system starts this dialog appears:
![image](https://i.imgur.com/IbXwJTE.png)

**Steps to reproduce (if you know):**
- Always

**Expected behavior:**
Using a ppa repository that keeps a package updated flatpak transition dialog should not appear

**Other Notes:**
- Latest version of [keepassxc](https://keepassxc.org) on July 3, 2020: `2.5.4` 
![image](https://i.imgur.com/P7E4kVE.png)
-  Version of "my" keepassxc installed by ppa on July 3, 2020: `2.5.4`
```
keepassxc --version
KeePassXC 2.5.4
```
- Version of keepassxc flatpak on July3, 2020: `2.5.4`
```
$ flatpak search keepassxc
Name      Description                                                               Application ID           Version  Branch  Remotes
KeePassXC Community-driven port of the Windows application “KeePass Password Safe”  org.keepassxc.KeePassXC  2.5.4    stable  flathub
```

**Comment by leviport** [comment] 2020-07-06 14:14
Duplicate of https://github.com/pop-os/transition/issues/11

**Closed by leviport** 2020-07-06 14:14 UTC
