### ISSUE TITLE
Pop Shop crashes on startup

### ISSUE THREAD

**Issue by JasonInOttawa** [pop-os/pop#3228] opened 2024-02-13 13:00 UTC
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Pop Shop crashes shortly after startup with a segmentation fault, both by the launcher and running it in terminal.

io.elementary.appcenter 

** (io.elementary.appcenter:5818): CRITICAL **: 07:54:22.481: app_center_widgets_banner_construct: assertion 'package != NULL' failed

(io.elementary.appcenter:5818): GLib-GObject-CRITICAL **: 07:54:22.482: g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failed

(io.elementary.appcenter:5818): Gtk-CRITICAL **: 07:54:22.482: gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.appcenter:5818): GLib-CRITICAL **: 07:54:23.106: g_strsplit: assertion 'string != NULL' failed
Segmentation fault (core dumped)

**Steps to reproduce (if you know):**

Start Pop Shop

**Expected behavior:**

Pop Shop should start.

**Other Notes:**

Please let me know if you need anything else

**Comment by leviport** [comment] 2024-02-13 14:11
Duplicate of https://github.com/pop-os/shop/issues/418

**Closed by leviport** 2024-02-13 14:11 UTC
