### ISSUE TITLE
the bottom of the "show application" window have a problem

### ISSUE THREAD

**Issue by AlexeiDubard** [pop-os/pop#2289] opened 2022-04-21 09:10 UTC
Hello,

yesterday, I installed pop!_os 21.10 (i know it's not stable yet)
and i just found a very small bug in the desktop,

when you press the "Show application" button the bottom 
goes into the dock and it disappears. (i don't changed the size of the dock).
 
![1](https://user-images.githubusercontent.com/78496624/164420484-7aeacee5-9940-4d3d-9de6-e11a6a2f79ed.png)

**Comment by leviport** [comment] 2022-04-21 13:31
I believe this is a duplicate of https://github.com/pop-os/cosmic/issues/314, but could you confirm that the overlap between the application library and the dock is what you're referring to?

**Comment by AlexeiDubard** [comment] 2022-04-21 16:35
I have the same bug as the issue you've mensionned, 
i will close the issue

**Closed** 2022-04-21 16:35 UTC
