### ISSUE TITLE
'Workspaces' mode is impossible to exit

### ISSUE THREAD

**Issue by RainmakerRaw** [pop-os/pop#1723] opened 2021-06-08 18:09 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-shell (I think?).
3.38.4-1ubuntu1pop0~1617377074~21.04~aac7e56

**Issue/Bug Description:**
When clicking 'Workspaces' on the upper top left of the menu bar, the workspace overview mode launches but is impossible to exit by any means other than a reboot, restarting the X session (Fn + F2 + r) or by logging out and back in. Currently open windows/apps are selectable (they highlight with an orange border) and you can move between them, but you can't actually 'choose' one or exit the overview without a restart of the session or the machine. 

**Steps to reproduce (if you know):**
1. Press 'Workspaces' on the top bar, or the button on the dock.
2. The workspaces overview launches. 
3. The mode can't be exited.

**Expected behavior:**
Upon selecting an app/window, that app/window should become foreground and the Workspaces overview mode should exit.

**Other Notes:**
Posted a question about this on [Reddit](https://www.reddit.com/r/pop_os/comments/nv7od6/cosmic_beta_stuck_in_workspaces_mode/), and others are also confirming they experience this. I searched open (and closed) Issues but didn't see one. Thanks in advance.

**Comment by leviport** [comment] 2021-06-08 18:14
Duplicate of https://github.com/pop-os/beta/issues/144

**Closed by leviport** 2021-06-08 18:14 UTC
