### ISSUE TITLE
Minimize button not working for windows from containers

### ISSUE THREAD

**Issue by brinn** [pop-os/pop#1502] opened 2021-01-21 18:42 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

apt policy gnome
gnome:
  Installed: (none)
  Candidate: 1:3.30+3
  Version table:
     1:3.30+3 500
        500 mirror://mirrors.ubuntu.com/mirrors.txt groovy/universe amd64 Packages

apt policy pop-shell
pop-shell:
  Installed: 1.1.0~1610693127~20.10~1557528
  Candidate: 1.1.0~1610693127~20.10~1557528
  Version table:
 *** 1.1.0~1610693127~20.10~1557528 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

Since installing the latest updates and restarting the desktop, the minimize button does not work anymore for windows of containerized applications. The short key Super + H works fine.

**Steps to reproduce (if you know):**
1. Start a GUI application in a LXD container (e.g. Firefox).
2. Click on the "minimize button" of the window ("-").
3. Nothing happens. 

**Expected behavior:**
The window is minimized.

**Other Notes:**
The observed behavior is independent of the application. It only depends on the application being started from a container. The bug was introduced with one of the recent updates (about last 5 days).

**Comment by leviport** [comment] 2021-01-21 18:45
Duplicate of https://github.com/pop-os/shell/issues/842

**Closed by leviport** 2021-01-21 18:45 UTC
