### ISSUE TITLE
"Active hint" for previous workspace appears when switching to new workspace with mouse

### ISSUE THREAD

**Issue by dnkrk** [pop-os/pop#1063] opened 2020-05-27 03:32 UTC
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 

**Issue/Bug Description:**
When switching workspaces with the mouse, the orange bounding box for the active window on the previous workspace appears on the new workspace.

![Screenshot from 2020-05-26 20-24-38](https://user-images.githubusercontent.com/48140369/82974848-c441ae80-9f8f-11ea-9798-50fffc9f79e1.png)

**Steps to reproduce (if you know):**
1. Turn on "Tile Windows" and "Show Active Hint" in the upper right corner
2. Have a window open and highlighted with the Active Hint
3. Press Super
4. On right-hand pane, click on the lowest workspace to create a new, blank workspace
5. Observe orange rectangle

**Expected behavior:**
Same thing as what happens when you change to a new workspace using Super+Ctrl+Down: active window hint disappears with its respective window, and new workspace is completely blank.

**Comment by leviport** [comment] 2020-05-27 14:43
Duplicate of https://github.com/pop-os/shell/issues/366

**Closed by leviport** 2020-05-27 14:43 UTC
