### ISSUE TITLE
Workspaces interface missing from secondary monitor when invoked.

### ISSUE THREAD

**Issue by mj-crabtree** [pop-os/pop#3309] opened 2024-06-12 10:59 UTC
**Distribution:**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version:**
Not entirely sure. Perhaps gnome-shell-*? [Here's a gist](https://gist.github.com/mj-crabtree/d32201d2d9cb1f76cb69376e044dba2c). Let me know if I should be looking up the policy for something else.

**Issue/Bug Description:**
Workspace representations fail to appear on secondary monitor when invoking the interface using super+tab.

**Steps to reproduce:**
Invoke the Workspaces interface using the super+tab shortcut.

**Expected behavior:**
A representation of each available workspace appears on both the primary and secondary monitors.

**Other Notes:**
- A [screenshot](https://imgur.com/a/0rxAn0W) of my desktop environment with the Workspaces interface invoked.
- A [screenshot](https://imgur.com/a/EsHJsoA) of the Workspaces panel in the system settings application.
- A [Reddit thread](https://www.reddit.com/r/pop_os/comments/1d51k00/workspaces_only_shows_the_workspaces_on_the_main/) with others experiencing a similar (if not the same) issue.

**Comment by leviport** [comment] 2024-06-12 14:12
Duplicate of https://github.com/pop-os/cosmic-workspaces/issues/87

**Closed by leviport** 2024-06-12 14:12 UTC
