### ISSUE TITLE
Cant update anything

### ISSUE THREAD

**Issue by C4T4P1LL4** [pop-os/pop#2587] opened 2022-08-22 00:16 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

just trying to update using the package manager

**Issue/Bug Description:**

I haven't been able to update anything. 

**Steps to reproduce (if you know):**

I have kde plasma on pop os. 
I get a popup that asks me if I want to update (using the discover app). 
I hit update, it starts downloading some stuff then...
Error Package failed to install:
Error while installing package: 0.0000

**Expected behavior:**

 It should just update my software without errors.

**Other Notes:**
I've tried only updating single packages and it gives the same thing.
I think this happened after I had followed some instructions on PCEM for linux but it could've been before that so it may or may not even be relevant to note that.

**Comment by leviport** [comment] 2022-08-22 17:07
Looks like a duplicate of https://github.com/pop-os/pop/issues/2556

There are commands in that thread that should fix it for you

**Closed by leviport** 2022-08-22 17:07 UTC

**Comment by C4T4P1LL4** [comment] 2022-08-23 14:42
That did correct my problem, thank you, leviport.
