### ISSUE TITLE
content of a window distorts when resizing

### ISSUE THREAD

**Issue by mma520** [pop-os/pop#1331] opened 2020-10-26 14:32 UTC
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by mma520** [comment] 2020-10-26 14:33
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**Comment by leviport** [comment] 2020-10-26 15:09
Thank you for the report. Could you describe the distortion a little more, and perhaps provide screenshots?

**Comment by chrisberry08** [comment] 2020-10-27 02:08
Not OP, but I might be experiencing something similar. Recording attached:
![example](https://user-images.githubusercontent.com/1624489/97248215-ab0b8b00-17d7-11eb-93e8-a16c50a2aa34.gif)

**Comment by leviport** [comment] 2020-11-10 16:56
I believe this issue is a duplicate of https://github.com/pop-os/shell/issues/677

**Closed by leviport** 2020-11-10 16:56 UTC
