### ISSUE TITLE
Focus-follows-mouse in 20.04 always raises hovered window

### ISSUE THREAD

**Issue by chungwu** [pop-os/pop#964] opened 2020-05-02 18:52 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Gnome settings for window focus no longer works as before; when focus-mode set to "sloppy" and auto-raise set to "false", hovered windows are still auto-raised.

**Steps to reproduce (if you know):**

$ gsettings get org.gnome.desktop.wm.preferences focus-mode
'sloppy'

$ gsettings get org.gnome.desktop.wm.preferences auto-raise
false

$ gsettings get org.gnome.desktop.wm.preferences raise-on-click
true

With these settings, hovering over windows raise them immediately.  Setting auto-raise-delay also has no effect.

**Expected behavior:**
Hovering over windows would let the window receive focus, but not raise it

**Other Notes:**
Worked fine in 19.10; no longer works after upgrading to 20.04.

**Comment by leviport** [comment] 2020-05-04 17:34
Duplicate of https://github.com/pop-os/beta/issues/53

**Closed by leviport** 2020-05-04 17:34 UTC
