### ISSUE TITLE
[Allen & Heath Qu-Pac] regression since 0.3.53+ / no audio inputs unless manual selection of config profile ("Pro") in pulse audio control

### ISSUE THREAD

**Issue by ianhundere** [pop-os/pop#2535] opened 2022-07-20 03:26 UTC
**Distribution (run `cat /etc/os-release`):**
 
 Pop!_OS 22.04 LTS
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
wireplumber or pipewire ?
```
❯ apt policy pipewire
pipewire:
  Installed: 0.3.56-0pop1~1658257572~22.04~7667c5c
  Candidate: 0.3.55-0pop1~1657666602~22.04~100cfa9
  Version table:
 *** 0.3.56-0pop1~1658257572~22.04~7667c5c 100
        100 /var/lib/dpkg/status
     0.3.55-0pop1~1657666602~22.04~100cfa9 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
❯ apt policy wireplumber
wireplumber:
  Installed: 0.4.9-1pop1~1654129452~22.04~a750cb3
  Candidate: 0.4.9-1pop1~1654129452~22.04~a750cb3
  Version table:
 *** 0.4.9-1pop1~1654129452~22.04~a750cb3 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.4.8-4 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
```
wireplumber is a bit out of date as `0.4.11` is the latest.

**Issue/Bug Description:**
since updating to pipewire `0.3.53` i have had to go to pulseaudio volume control and unselect / reselect the config profile for my interface ("Pro"). otherwise inputs don't work in my daw, bitwig `4.3.2`.

**Steps to reproduce (if you know):**

reset interface / no inputs in daw (bitwig 4.3.2)

**Expected behavior:**
you shouldn't need to reselect a profile

**Other Notes:**
more info: 
- https://github.com/pop-os/pipewire/issues/16
- https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2567
maybe i should open a wireplumber issue? i wanna wait until i've tried `0.4.11` tho.

**Comment by leviport** [comment] 2022-07-20 14:05
Duplicate of https://github.com/pop-os/pipewire/issues/16

In https://github.com/pop-os/pipewire/issues/16#issuecomment-1189534086, @mmstick meant that you should report it to Pipewire developers.

**Closed** 2022-07-20 14:06 UTC

**Comment by ianhundere** [comment] 2022-07-20 14:32
and how do i do that ?

**Comment by jacobgkau** [comment] 2022-07-20 14:49
> and how do i do that ?

On the upstream PipeWire Gitlab: https://gitlab.freedesktop.org/pipewire/pipewire

It looks like another user already created an issue upstream about 8 hours ago (they linked to it in https://github.com/pop-os/pipewire/issues/16#issuecomment-1189914280): https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2577

**Comment by ianhundere** [comment] 2022-07-20 15:07
oh yah, i posted there already:
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2567
