### ISSUE TITLE
Mouse Scrolling (Natural Scrolling) consistency issue

### ISSUE THREAD

**Issue by SamuelTissot** [pop-os/pop#1315] opened 2020-10-23 12:29 UTC
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
**Issue/Bug Description:**

The mouse scrolling configuration `Natural Scrolling` (found in the `settings/Mouse & Trackpad` section) is not honoured after a wake-up. However, the toggle in the settings still shows as `Natural Scrolling ON`. Basically, the scrolling reverts to "normal" after a wake up even if the settings still shows `Natural Scrolling ON`

![image](https://user-images.githubusercontent.com/11725094/97002540-1b7c8880-1508-11eb-8ce5-84d976ec0cb9.png)

This affects the trackpad and the mouse (Logitech MX Master S2)

To remedy the issue I need to toggle the `Natural Scrolling` ON/OFF and everything works again as expected.

**Steps to reproduce (if you know):**

Toggle `Natural Scrolling` ON put the computer to sleep. Wake Scrolling is now on `Normal` mode

**Expected behavior:**

That the `Natural Scrolling` setting is consistent all the time

**Other Notes:**

**Comment by jacobgkau** [comment] 2020-10-23 14:17
Thank you for the report. The specific devices affected seem to vary a little, but this is a duplicate of https://github.com/pop-os/gnome-control-center/issues/120.

**Closed by jacobgkau** 2020-10-23 14:17 UTC
