### ISSUE TITLE
When moving a window to another workspace, the window loses focus

### ISSUE THREAD

**Issue by Sullux** [pop-os/pop#2407] opened 2022-05-13 16:14 UTC
**Distribution (run `cat /etc/os-release`):**
 22.04
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Window Switcher

**Issue/Bug Description:**
When moving a window to another workspace, the window loses focus.

**Steps to reproduce (if you know):**
* Activate the "Workspaces on Primary Display Only" setting.
* Set the "Number of Workspaces" to at least 3.
* Open any window on your secondary display (may not be necessary to repro?).
* Open a different window on Workspace 1 of your primary display (hereafter "The Window").
* Using your keyboard, move The Window down two workspaces
* Actual behavior: the window loses focus after the first movement. You have to switch to a different window and back in order to move it to the next workspace (or click on it with your mouse).

**Expected behavior:**
The window retains focus after the workspace change so that it can either be moved to the next workspace or interacted with.

**Other Notes:**
It may sound niche, but this is a disastrous bug that completely destroys my ability to use this distro. I may have to switch distros just because of this bug. I need to be able to move windows from workspace to workspace constantly throughout the day, so this is literally the primary feature of the OS for me and at present it is so broken as to be unusable.

**Comment by jacobgkau** [comment] 2022-05-13 16:17
Duplicate of https://github.com/pop-os/shell/issues/1415, a fix is coming soon.

**Closed by jacobgkau** 2022-05-13 16:17 UTC
