### ISSUE TITLE
HiDPI toggle missing from 19.10

### ISSUE THREAD

**Issue by davidbailey00** [pop-os/pop#513] opened 2019-04-21 20:05 UTC
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
hidpi-daemon:
  Installed: 18.04.4~1533160664~19.04~85d4567
  Candidate: 18.04.4~1533160664~19.04~85d4567
  Version table:
 *** 18.04.4~1533160664~19.04~85d4567 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

As of 19.04, the HiDPI daemon toggle switch is no longer visible in the Displays section of the Settings app. It can still be toggled using the command line, as described on the System76 website.

**Steps to reproduce (if you know):**

Open Settings -> Devices -> Displays

**Expected behavior:**

The HiDPI daemon toggle is visible.

**Actual behavior:**

It is not:
![image](https://user-images.githubusercontent.com/4248177/56474948-2e2c8200-6479-11e9-8ff2-cf1d8cfe0968.png)

**Other Notes:**

n/a

**Comment by brs17** [comment] 2019-04-22 02:59
Thank you for filing this issue @davidbailey00 , this is a known issue and a duplicate of https://github.com/pop-os/gnome-control-center/issues/19

**Closed by brs17** 2019-04-22 02:59 UTC
