### ISSUE TITLE
"View split on left" keyboard shortcut does not work when set

### ISSUE THREAD

**Issue by BenjaFriend** [pop-os/pop#641] opened 2019-08-18 16:33 UTC
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
cat /etc/default/keyboard 
XKBLAYOUT=us
BACKSPACE=guess
```

**Issue/Bug Description:**
"View split on left" keyboard shortcut setting does not work.

**Steps to reproduce (if you know):**
1. Go to keyboard settings (Settings > Devices > Keyboard)
2. Set your "View split on left" action to `Super + Left`
3. Notice that this action does not work

**Expected behavior:**

The active window would show on the left side of the screen when the action is pressed

**Other Notes:**
Here is an image of my keyboard settings, as you can see nothing else is bound to this shortcut: 
![image](https://user-images.githubusercontent.com/14983811/63227365-9420e000-c1b3-11e9-9ff3-c6b864070219.png)

I tried setting this action on a live boot of vanilla Ubuntu and the keyboard shortcut worked fine. The action also works in Windows 10, which makes me think that this is a Pop-specific issue. 

"View split on right" works fine when I set it to `Super + Right`

**Comment by blumberg** [comment] 2019-08-27 06:39
Same thing here. Sometimes just after setting the shortcut it works, but doesn't last a reboot. One day it worked for left side and not for rigth after the reboot.

I use Windows at work, at home, Fedora in one machine and Pop!_OS in another, having same keycombo accross all of them make my life slightly better.

**Comment by crawfxrd** [comment] 2019-12-24 17:00
Duplicate of #409

**Closed by crawfxrd** 2019-12-24 17:00 UTC
