### ISSUE TITLE
Keyboard Shortcut Super + / does not work on German Keyboardlayout

### ISSUE THREAD

**Issue by pwfraley** [pop-os/pop#1345] opened 2020-10-29 10:59 UTC
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

This also applies to 20.04

Using the Super + / always starts the 7th application on the dock.  In order to get to the / you have to press SHIFT + 7 on a german keyboard.

Install Pop OS 20.04 or 20.10 with a german keyboard layout and try SUPER + / (which is SUPER + SHIFT + 7 on a german keyboard)

**Expected behavior:**
Should start the Launcher

**Other Notes:**

**Comment by leviport** [comment] 2020-10-29 14:21
Duplicate of https://github.com/pop-os/shell/issues/196

**Closed by leviport** 2020-10-29 14:21 UTC
