### ISSUE TITLE
Minor aesthetic error: terminal skips line when out of focus

### ISSUE THREAD

**Issue by wmutschl** [pop-os/pop#383] opened 2018-11-05 17:29 UTC
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```
  
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Gnome Terminal 3.30.1

**Issue/Bug Description:**
When the terminal is out of focus it skips a line, when I click inside the terminal it skips back, see attached gif.

**Steps to reproduce (if you know):**
See attached gif

**Expected behavior:**
No skips.

**Other Notes:**

![terminalskip](https://user-images.githubusercontent.com/36013296/48015164-ae0f9b80-e128-11e8-838f-2252992aa13e.gif)

**Comment by brs17** [comment] 2018-11-05 21:18
Duplicate of https://github.com/pop-os/gtk-theme/issues/217

Fixed here: https://github.com/pop-os/gtk-theme/pull/225

**Closed by brs17** 2018-11-05 21:18 UTC
