### ISSUE TITLE
Firefox windows not being displayed correctly

### ISSUE THREAD

**Issue by ShrugMcShrug** [pop-os/pop#2120] opened 2021-12-26 13:59 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
firefox:
  Installed: 95.0.1+build2-0ubuntu0.21.10.1
  Candidate: 95.0.1+build2-0ubuntu0.21.10.1
  Version table:
 *** 95.0.1+build2-0ubuntu0.21.10.1 500
        500 http://us.archive.ubuntu.com/ubuntu impish-security/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu impish-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     93.0+build1-0ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu impish/main amd64 Packages

**Issue/Bug Description:**
After I updated to 21.10, a Firefox window fails to draw correctly about half of the time. In addition, if I hover my cursor over certain parts of a page, the window starts to spazz and has trouble drawing the window correctly. 

**Steps to reproduce (if you know):**
Start Firefox either from the icon or from terminal, it does the same thing.

**Expected behavior:**
The new Firefox window will draw whatever the current state of the screen is. 
So for example, if I have a terminal open and I click the Firefox icon, a window will appear with a distorted version of my desktop with a terminal open.

**Other Notes:**

**Comment by parichaya** [comment] 2021-12-27 02:20
Hi, I was just searing for this. I just installed the latest Pop OS (21.10) on my Lemur Pro and after installing my applications and getting everything setup, I notice that sometimes after restarting my machine and logging in, when I click Firefox, it opens but I cannot see it clearly. As in the desktop area where the Firefox window was supposed to appear becomes translucent, and when I hover my mouse over it, I can interact with it (clicking where the menu would have appeared opens the menu drop down, etc.) but I cannot actually see the Firefox window. This behavior is repeated. And then after 10 minutes when I click on Firefox, it just opens up all nice and fine. I am not sure what the root cause is.

**Comment by ShrugMcShrug** [comment] 2021-12-27 16:11
> I just installed the latest Pop OS (21.10) on my Lemur Pro

I have a Gazelle 15. I didn't think of this at first but do you have an nvidia card? I do and I'm not sure if this is related.

**Comment by kporkka** [comment] 2021-12-27 18:19
Same issue, Firefox (latest), shows as an empty frame. Popos latest version 21.10. Lenovo Thinkpad P15 gen1 latest firmware. A a major issue.

![image](https://user-images.githubusercontent.com/26165318/147497532-0c550303-e413-4c95-b5da-31fb68eda695.png)

**Comment by kporkka** [comment] 2021-12-27 18:40
Installed the Flatpak version and it works fine so far (the deb version does not)

**Comment by kporkka** [comment] 2021-12-27 19:01
My sysinfo
![image](https://user-images.githubusercontent.com/26165318/147500040-2723f3f6-032d-4c3f-98f7-bab9ec29572c.png)

**Comment by parichaya** [comment] 2021-12-28 04:36
> > I just installed the latest Pop OS (21.10) on my Lemur Pro
> 
> I have a Gazelle 15. I didn't think of this at first but do you have an nvidia card? I do and I'm not sure if this is related.

No, I have the lemp10 and it only has the Iris Xe graphics :)

**Comment by parichaya** [comment] 2021-12-28 04:37
> Installed the Flatpak version and it works fine so far (the deb version does not)

Can we still install gnome extensions using the Flatpak version?

**Comment by ShrugMcShrug** [comment] 2021-12-28 12:00
> Installed the Flatpak version and it works fine so far (the deb version does not)

You have the straight up Debian version or the Pop(deb) version from the Pop Shop? I'm not sure how much difference there is between the two. I'll try the flatpak version a bit later. Any issues encountered since you commented?

**Comment by kporkka** [comment] 2021-12-28 12:05
The PopShop version I think, don't how to tell which one it is. Hope the Flatpak works for you, no issues here (knock on wood).

**Comment by ShrugMcShrug** [comment] 2021-12-28 16:45
@kporkka @parichaya 
Unfortunately, the flatpak fix doesn't work for me. Thanks for suggesting!

**Comment by fauxerious** [comment] 2021-12-30 21:41
I had this issue upon upgrading from 21.04 to 21.10 on my lemp10. I resolved it via an OS Refresh. Not ideal, but it's what worked for me.

**Comment by ShrugMcShrug** [comment] 2021-12-31 12:51
> 

I'll give that a shot one of these days. It took me awhile to upgrade so I'm not sure if I need to block off a large chunk of time to watch it. Thank for the tip!

**Comment by mnieminen** [comment] 2022-01-09 02:51
I'm having the same problem after updating to Pop_OS 20.10. Firefox launches with garbled and misdrawn windows about 50% of the time. It's worse when clicking links in emails that should open in the default browser, set to Firefox. Tried with both Flatpak and Pop_OS versions of Firefox with the same results.

**Comment by DiogoMoreira0610** [comment] 2022-01-12 15:52
I have same problem here... garbled and misdrawn windows at most time

**Comment by kennethjuulwannebo** [comment] 2022-02-13 22:35
I have the same issue on my Dell XPS 15
![image](https://user-images.githubusercontent.com/59299574/153778161-1723597c-012d-496f-a3f6-d73bea121e4b.png)

This seems to only happen when I use integrated graphics (for battery life) and when hardware acceleration is enabled in Firefox, disabling it makes Firefox stutter.
![image](https://user-images.githubusercontent.com/59299574/153778227-1e1054eb-2437-4996-b7ec-cfa1f7ac1970.png)

**Comment by BrianWalters** [comment] 2022-03-02 20:11
I had the same issue as above on a System76 Gazelle running Pop!_OS 21.10. It seems to be an issue with integrated graphics + hardware acceleration. If you are using NVIDIA graphics it seems to be fine. If you are using integrated graphics you need to turn off hardware acceleration in Firefox.

**Comment by leviport** [comment] 2022-03-10 15:39
Duplicate of https://github.com/pop-os/pop/issues/2182

**Closed by leviport** 2022-03-10 15:39 UTC

**Comment by chriswininger** [comment] 2022-03-23 13:12
Thanks not much new to add but just throwing out another data point. I am seeing this in a Thinkpad p15s gen2.

I like other have been running on integrated graphics for battery life and am using the popOS deb.

This was not always the case for me. It had been working fine for a quite a while with both integrated graphics and nvidia. As other have stated it starts working for me again if I wait a few minutes after rebooting.

I am not sure what kicked off this issue. It seems to have started with a recent firefox updated.

My firefox version is: 98.0.1 (64-bit).

Other system info:

OS: Pop!_OS 21.10 x86_64 
Host: 20W60020US ThinkPad P15s Gen 2i 
Kernel: 5.16.11-76051611-generic 
Shell: bash 5.1.8 
Resolution: 3840x2160 
DE: GNOME 40.5 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 3361MiB / 31825MiB
