### ISSUE TITLE
Problem in installing vim

### ISSUE THREAD

**Issue by soma2000-lang** [pop-os/pop#2732] opened 2022-12-23 16:42 UTC
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

![Screenshot from 2022-12-23 22-08-58](https://user-images.githubusercontent.com/56045049/209369937-10a168f2-1402-4d1f-addf-30e5ab7eca9c.png)

![Screenshot from 2022-12-23 22-08-20](https://user-images.githubusercontent.com/56045049/209370058-8e55d802-5108-4dc5-a78a-c1ee2da7639b.png)

**Comment by jacobgkau** [comment] 2022-12-23 16:49
The current version of `vim` is `2:8.2.3995-1ubuntu2.1`. I don't know where you got `2:8.1.0837-0york0~16.04` from.

Your screenshots indicate that you are experiencing a package manager issue (caused by prior action on the system) unrelated to the `vim` package in particular. I would recommend running the six commands at the top of this support article: https://support.system76.com/articles/package-manager-pop 

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by isantop** [comment] 2022-12-23 16:49
It looks like your software sources might be broken. Can you send the output of this command:

```
apt-manage list -av
```

**Comment by jacobgkau** [comment] 2022-12-23 16:53
I'm closing this as a duplicate of your other issue, https://github.com/pop-os/system76-driver/issues/261. Please do not open multiple issues across multiple repositories for the same problem.

**Comment by soma2000-lang** [comment] 2022-12-23 16:54
Yes sure @jacobgkau 
![image](https://user-images.githubusercontent.com/56045049/209372558-15d22928-349e-4204-b0b3-8f5286745117.png)

**Closed by jacobgkau** 2022-12-23 16:53 UTC
Labels: support request, needs more info

**Comment by jacobgkau** [comment] 2022-12-23 16:59
I posted the three source files that you should have in your other issue, https://github.com/pop-os/pop/issues/2733#issuecomment-1364114367. If you add those and run `sudo apt update`, then you should get farther. Please post any further info in the other issue.
