### ISSUE TITLE
PopOS! does not recognize when it is being charged.

### ISSUE THREAD

**Issue by iagonca** [pop-os/pop#2920] opened 2023-06-17 13:42 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
The system does not recognize when the power source is connected. When the OS wakes up, it recognizes that the battery is being charged, and everything works normally. But after some time, the issue returns, and the system no longer recognizes that it is being charged. When connected, it shows "Not charging." When disconnected, everything works normally.
My device still charges normaly.

**Expected behavior:**
Pop_OS! should recognize that the power adapter is connected and display it in the menu, updating the icon and providing an estimated time remaining to finish charging.

**Other Notes:**
Device model: Lenovo Yoga 910
![image](https://github.com/pop-os/pop/assets/66425831/3f1d3bc5-f470-4178-9eec-399197150973)
*when connected

![image](https://github.com/pop-os/pop/assets/66425831/02fa78a3-a59d-41e9-b886-ad1dbd6a2420)
*when disconnected

**Comment by gamatoro** [comment] 2023-09-06 07:56
Have you checked your power source? Maybe dirty electricity or anything similiar to that? Does it charge normally on your (if you have one available) windows device?

**Comment by ssalentin** [comment] 2024-08-24 22:22
I am having the same problem after a fresh install of Pop!_OS 22.04 LTS on both a Thinkpad T480S and Thinkpad X270.
For me, charging is not recognized immediately, but might switch to the correct status after a longer time (1 minute or longer).

After I am plugging in a power source, I can immediately see in /sys/class/power_supply/BAT0/status that the status here changes to Charging after a few seconds and also the notebooks charge normally.

So for me this also seems to be a problem with updating the charging status in the OS.

**Comment by leviport** [comment] 2024-08-26 17:53
I believe this is a duplicate of https://github.com/pop-os/pop/issues/1205

**Closed by leviport** 2024-08-26 17:53 UTC
