### ISSUE TITLE
The tile windows is not working with MPV application

### ISSUE THREAD

**Issue by sylock** [pop-os/pop#1510] opened 2021-01-25 19:33 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
mpv:
  Installed: 2:0.33.0~groovy
  Candidate: 2:0.33.0~groovy
  Version table:
 *** 2:0.33.0~groovy 500
        500 http://ppa.launchpad.net/mc3man/mpv-tests/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.32.0-2ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages

The project homepage is here:
https://mpv.io/

**Issue/Bug Description:**
When the "Tile Windows" option is enabled, the size of the window of the MPV application is resized too much. So the right part of the window is out of the desktop area and unreachable. So do the cross icon to close the window.

**Steps to reproduce (if you know):**

* Install MPV from the PPA: https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests
* Enable the "Tile Windows" functionnality
* start MPV

**Expected behavior:**
The MPV software window is resized correctly. The right edge of the windows is not outside of the display area.

**Other Notes:**

**Comment by mmstick** [comment] 2021-01-25 19:35
Duplicate of https://github.com/pop-os/shell/issues/85

**Closed by mmstick** 2021-01-25 19:35 UTC
