### ISSUE TITLE
Remember tiled layout when retiling

### ISSUE THREAD

**Issue by joelostblom** [pop-os/pop#1728] opened 2021-06-11 17:54 UTC
First of of all, the tiling layout is great overall, thanks for supporting this workflow. Coming from i3, this is one of the things that made me stick with pop and not switch to i3 when I got my lemp10.

Sometimes when I work in tiling mode, I want to switch to the normal mode temporarily. If this was just for a single window I could click the exception menu button, but usually I need it for multiple windows for a short amount of time and then go back into tiled mode. The issue is when going back to tiled mode, the layout is reset instead of returned to what I had just before disabling tiling. This  happens for tiled position on the screen, stacking, etc, and across *all* desktops. This is quite disruptive as I need to spend time repositioning windows on multiple desktop and it would be great if the tiled layout was recorded and returned to after retiling.

Here is an example where I switch desktops and then hit the until/tile shortcut. You can see that windows are both repositioned and unstacked:

![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/4560057/121728649-6997c980-caa2-11eb-9d7d-d1c89fd62bbf.gif)

**Distribution (run `cat /etc/os-release`):**
 ```
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**Comment by mmstick** [comment] 2021-06-11 18:48
Duplicate of https://github.com/pop-os/shell/issues/735

**Closed by mmstick** 2021-06-11 18:48 UTC

**Comment by mmstick** [comment] 2021-06-11 18:51
This is already planned for the future. It will just require some work to create associations necessary to reconstruct the trees.

**Comment by joelostblom** [comment] 2021-06-11 19:10
Ah cool, didn't notice there was a separate shell repo so only searched in this one, thanks!
