### ISSUE TITLE
Activities corner click doesn't register at top-left pixel

### ISSUE THREAD

**Issue by JamesSwift** [pop-os/pop#747] opened 2019-11-13 23:01 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Gnome Shell

**Issue/Bug Description:**
When I click the activities button in the top left, it normally opens fine. But occasionally I find it doesn't open on the first click. After some experimentation I discovered that if the mouse pointer is at the very top-left pixel then no matter how many times you click, the menu isn't activated. Move the mouse by one pixel in any direction and it works.

**Steps to reproduce (if you know):**
Drag mouse fully up and fully left. Click.

**Expected behavior:**
Activities menu should open

**Other Notes:**

**Comment by brs17** [comment] 2019-11-14 14:04
This issue is a duplicate of https://github.com/pop-os/gnome-shell/issues/9

**Closed by brs17** 2019-11-14 14:04 UTC
