### ISSUE TITLE
App Menu Navigation Bug

### ISSUE THREAD

**Issue by MonaMoonlight** [pop-os/pop#143] opened 2018-02-26 15:14 UTC
**Reporter info**

```
 * Distribution - Pop!_OS 17.10 (Artful Aardvark)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**
It's possible to get momentarily stuck navigating the applications view using only the keyboard, upon pressing the right cursor key.

**Steps to reproduce (if you know)**
Any time you right-click on a program icon in the app menu to, for instance, open a new window, the next time you try to navigate the app menu with the arrow keys, and any icon you have right-clicked on is highlighted, pressing the right cursor key will bring up the right-click menu instead of navigating to the next icon.

This can affect multiple icons at the same time, potentially making it impossible to navigate the app menu with just the cursor keys.

**Expected behavior**
It is expected that pressing the right cursor key in this situation would not bring up a menu, but instead navigate to the icon immediately to the right.

**Other Notes**
It is possible to press Esc to back out of the right-click menu, but the issue will remain until you log out and then in again.

Keeping Ctrl pressed while using the cursor keys prevents the right-click menu from opening while the issue is in effect, but only logging out and in again solves the issue, until you open the right-click menu again.

**Comment by brs17** [comment] 2018-03-07 18:12
I can confirm that this is a consistent issue on Pop!_OS. This seems to be an issue with setting the focus in the application menu. I would be curious if this is also happening upstream in Ubuntu 17.10. From there we can confirm if this is an upstream issue.

**Comment by bflanagin** [comment] 2022-02-08 20:48
Given the age of this ticket and the design direction Pop!_OS is taking the issue is now obsolete. Thank you for your report.

Closing ticket.

**Closed by bflanagin** 2022-02-08 20:48 UTC
Labels: bug
