### ISSUE TITLE
Super key not working when switching the keyboard to Italian

### ISSUE THREAD

**Issue by aretor** [pop-os/pop#952] opened 2020-05-01 19:31 UTC
**Distribution (run `cat /etc/os-release`):**
Pop!_Os 20.04 LTS 

**Issue/Bug Description:**
When switching to a secondary language, with <kbd>Super</kbd> + <kbd>Space</kbd>, the <kbd>Super</kbd> key does not work anymore. When switching again to the primary language everything works as intended.

**Steps to reproduce (if you know):**
Add two languages (En-US and Italian, in my case). Switch to the secondary language and you'll notice that the key won't work (I can't enter the menu).

**Expected behavior:**
I expect the <kbd>Super</kbd> key to work in the same way, regardless of the language chosen.

**Other Notes:**
I was able to reproduce the error even when changing the primary and secondary language (Italian and En-US) and even when adding a third language (Japanese or En-UK). In the latter case the key does not work with both the second and third language.

**Comment by tmpr** [comment] 2020-05-02 08:15
I have the same problem with the combination of En-UK Colemak and German QWERTZ.

**Comment by sdkmor** [comment] 2020-05-02 13:55
I have the same problem with the combination of En-US (intl. w/ dead keys) and Portuguese (Brazil).
The problem also occurs when changing input sources on the top bar.
Nevertheless, changing input sources order directly on Settings/Region & Language works.

**Comment by defecador** [comment] 2020-05-03 18:16
in European keyboards also not super + / Probably because / = shift + 7 but Super + shift + 7 is also not working. would be perfect to have the possibility to change this shortcut

**Comment by leviport** [comment] 2020-05-04 18:23
Duplicate of https://github.com/pop-os/beta/issues/98

**Closed by leviport** 2020-05-04 18:23 UTC
