### ISSUE TITLE
VLC updates showing up under Operating System Updates

### ISSUE THREAD

**Issue by cunctator00** [pop-os/pop#289] opened 2018-05-24 09:54 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

VLC updates showing up under Operating System Updates

**Steps to reproduce (if you know):**

**Expected behavior:**

not to show up under Operating System Updates

**Other Notes:**

**Comment by Clae224** [comment] 2018-06-04 00:46
Duplicate of #280. You've already posted there so there's no point in having a new bug for it...

**Closed** 2018-06-06 16:56 UTC
