### ISSUE TITLE
GNOME Zoom in and Zoom out shortcuts don't work.

### ISSUE THREAD

**Issue by Xeboc** [pop-os/pop#74] opened 2017-11-15 17:42 UTC
Feedback about default keyboard shortcuts:

> I notice some of the basic Ubuntu Gnome shortcuts don't seem to work on the Pop! e.g. Ctrl + and - for zooming, Alt F4 to close a window, F10 for program menu. Did you intentionally disable these?

> On your keyboard shortcuts page, I cannot see an ordinary Zoom method, only one combined with the magnifier which I do not want. Does this mean I need to create my own? What is Pop! intending people to do for regular zooming in and out which I need to do often because of my eyesight or fitting on a half screen size for example? I did find Ctrl + and - very workable in the absence of zooming function on the touchpad.

**Comment by jackpot51** [comment] 2017-11-15 17:51
Super W to close windows
Alt Super 8 to enable zooming
Alt Super + and Alt Super - for zooming
Super F10 for application menu

**Comment by Xeboc** [comment] 2017-11-15 19:02
What about zoom when the magnifier isn't active?  That is the specific complaint of this vision limited customer.

**Comment by filipszu** [comment] 2018-01-21 05:07
The show desktop shortcut is also not working
Super + d

**Comment by brs17** [comment] 2018-01-21 18:20
I can confirm <kbd>Super</kbd> + <kbd>d</kbd> does not show the desktop

**Comment by brs17** [comment] 2018-03-08 21:15
@filipszu Looks like by default <kbd>Super</kbd> + <kbd>d</kbd> is disabled/does not exist in Pop!_OS as the intended use of GNOME is to switch workspaces. Adding this keyboard shortcut to `Hide all normal windows` very well may do what you're looking for.

Seems like keyboard shortcuts all work as expected. Closing issue.

**Closed by brs17** 2018-03-08 21:15 UTC
Labels: bite-sized
