### ISSUE TITLE
Mouse cursor invisible after using touchscreen

### ISSUE THREAD

**Issue by Potjoe-97** [pop-os/pop#2328] opened 2022-04-29 13:16 UTC
**Distribution (run `cat /etc/os-release`):** "Pop!_OS 22.04 LTS"

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:** Mouse cursor is invisible when using alternatively touchscreen and touchpad. Mouse cursor is visible using the touchpad. But, if the touchscreen is used, then using the touchpad again does not display the cursor, which stays invisible. To make it visible again, mouse has to be moved all the way up to the top bar (with clock / notifications center / settings). The cursor appears when it reaches the top bar. 

**Steps to reproduce (if you know):** Using a Lenovo T490 with Touchscreen. From login : the cursor is visible using the touchpad or trackpoint (lenovo specific red dot). Touch the screen. Then, use the touchpad again : cursor is invisible. 

**Expected behavior:** When touchscreen is used, cursor should be invisible. But coming back to the touchpad should make it visible again instantly from its last position, and we should not have to guess-move to the top bar. 

**Other Notes:**

**Comment by ClementJ18** [comment] 2022-05-07 10:35
I have the same issue

**Comment by hm11235** [comment] 2022-05-08 18:23
Device- Dell Latitude 7200 2in 1. 
I observe the same problem but only with X11 windowing system. No issues with Wayland. 
If you have no particular reason to prefer X11 over Wayland, you can use Wayland until a proper fixed is found for the issue. 
To enable Wayland:
(sudo) edit the  `/etc/gdm3/custom.conf` file and comment out the `WaylandEnable=false` line, then reboot.

**Comment by gorghino** [comment] 2022-07-12 09:26
This happens to me as well.
At the moment I'm just using my touchpad. My mouse is off.

```
OS: Pop!_OS 22.04 LTS x86_64 
Host: Blade 15 Advanced Model (Early 2020) - RZ09-033 5.04 
Kernel: 5.17.15-76051715-generic 
Uptime: 23 hours, 47 mins 
Packages: 2047 (dpkg), 8 (flatpak), 8 (snap) 
Shell: bash 5.1.16 
Resolution: 2560x1440 
DE: GNOME 42.2 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-10875H (16) @ 5.100GHz 
GPU: NVIDIA GeForce RTX 2080 SUPER Mobile / Max-Q 
GPU: Intel CometLake-H GT2 [UHD Graphics] 
Memory: 4435MiB / 15860MiB 
```

**Comment by christophercalm** [comment] 2022-08-06 15:17
Just wanted to add that this is happening for me as well.

**Comment by chrislynch8** [comment] 2022-09-09 20:34
Have the same issue here using Lenovo Yoga 6

`OS: Pop!_OS 22.04 LTS x86_64 
Host: 82ND Yoga 6 13ALC6 
Kernel: 5.19.0-76051900-generic 
`

**Comment by tekchip** [comment] 2022-09-18 12:47
I have this issue as well. An additional piece of information and perhaps something useful for others.

If you hit the super key it opens the launcher with onscreen keyboard open as if in touchscreen mode. You can then use your touchpad to regain the mouse.

```
0S: Pop!_0S 22.04 LTS Xx86_64
Host: HP Spectre x360 Convertible 13
Kernel: 5.19.0-76051900-generic
```

**Comment by StarpTech** [comment] 2022-09-18 19:36
I had the same issue. It must be related to X11 because it works for me on Ubuntu 22.04 Wayland.

**Comment by rscircus** [comment] 2022-11-17 08:22
+1 on Thinkpad T14

**Comment by leviport** [comment] 2022-11-17 15:46
Duplicate of https://github.com/pop-os/pop/issues/2222

**Closed by leviport** 2022-11-17 15:46 UTC
