### ISSUE TITLE
Firefox title bar 

### ISSUE THREAD

**Issue by dhitchcock** [pop-os/pop#914] opened 2020-04-20 03:07 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

firefox:
  Installed: 75.0+build3-0ubuntu1
  Candidate: 75.0+build3-0ubuntu1
  Version table:
 *** 75.0+build3-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

If you disable the title bar in Firefox in 20.04, it doesn't actually go away and you have an awkward double close X in the corner.

**Steps to reproduce (if you know):**

Launch firefox (tried it with totally clean profile, rm ~/.mozilla) Right click tab bar, Customize, Uncheck Title Bar.  Also I'm in dark theme, not sure if happens in light.

![Screenshot from 2020-04-19 21-55-56](https://user-images.githubusercontent.com/2146072/79710198-e0b04400-8289-11ea-9129-12b8e0a3c14d.png)

**Expected behavior:**
Title Bar disappears.  

**Other Notes:**

I was just in 19.10 yesterday without this problem and it was the same major version of Firefox, not sure the exact package but it's something about 20.04.  I did a clean install of 20.04 also.

**Comment by leviport** [comment] 2020-04-20 16:03
This is a duplicate of https://github.com/pop-os/shell/issues/32 so I'll close this one for now. Thanks for reporting though!

**Closed by leviport** 2020-04-20 16:03 UTC
